! NOTE: Assertions have been autogenerated by /home/rpenacob/llvm-mono/mlir/utils/generate-test-checks.py
! RUN: bbc -fompss-2 -hlfir -emit-fir %s -o - | fir-opt --convert-hlfir-to-fir --cg-rewrite --fir-to-llvm-ir -o - 2>&1 | FileCheck %s --check-prefix=HLFIRToLLVMDialect
PROGRAM P
  IMPLICIT NONE
  INTEGER :: X
  !$OSS TASK
  X = 777
  !$OSS END TASK
END


! HLFIRToLLVMDialect-LABEL:   llvm.func @_QQmain() attributes {fir.bindc_name = "p"} {
! HLFIRToLLVMDialect:           %[[VAL_0:[-0-9A-Za-z._]+]] = llvm.mlir.constant(1 : i64) : i64
! HLFIRToLLVMDialect:           %[[VAL_1:[-0-9A-Za-z._]+]] = llvm.alloca %[[VAL_0]] x i32 {bindc_name = "x", in_type = i32, operand_segment_sizes = array<i32: 0, 0>, uniq_name = "_QFEx"} : (i64) -> !llvm.ptr<i32>
! HLFIRToLLVMDialect:           oss.task firstprivate(%[[VAL_1]], %[[VAL_1]] : !llvm.ptr<i32>, !llvm.ptr<i32>) {
! HLFIRToLLVMDialect:             %[[VAL_2:[-0-9A-Za-z._]+]] = llvm.mlir.constant(777 : i32) : i32
! HLFIRToLLVMDialect:             llvm.store %[[VAL_2]], %[[VAL_1]] : !llvm.ptr<i32>
! HLFIRToLLVMDialect:             oss.terminator
! HLFIRToLLVMDialect:           }
! HLFIRToLLVMDialect:           llvm.return
! HLFIRToLLVMDialect:         }

! HLFIRToLLVMDialect-LABEL:   llvm.mlir.global external constant @_QQEnvironmentDefaults() {addr_space = 0 : i32} : !llvm.ptr<struct<(i32, ptr<array<0 x struct<(ptr<i8>, ptr<i8>)>>>)>> {
! HLFIRToLLVMDialect:           %[[VAL_0:[-0-9A-Za-z._]+]] = llvm.mlir.null : !llvm.ptr<struct<(i32, ptr<array<0 x struct<(ptr<i8>, ptr<i8>)>>>)>>
! HLFIRToLLVMDialect:           llvm.return %[[VAL_0]] : !llvm.ptr<struct<(i32, ptr<array<0 x struct<(ptr<i8>, ptr<i8>)>>>)>>
! HLFIRToLLVMDialect:         }

