! NOTE: Assertions have been autogenerated by /home/rpenacob/llvm-mono/mlir/utils/generate-test-checks.py
! Test test checks we do not emit duplicates data-sharings

! RUN: flang-new -fc1 -emit-fir -fompss-2 -o - %s | FileCheck %s --check-prefix=FIRDialect

program task
    INTEGER :: I, J, K, U

    !$OSS TASK DO DEFAULT(FIRSTPRIVATE) PRIVATE(J, J) FIRSTPRIVATE(U, K, K)
    DO I=1, 10
    U = 1
    END DO
    !$OSS END TASK DO

    !$OSS TASKLOOP DEFAULT(FIRSTPRIVATE) PRIVATE(J, J) FIRSTPRIVATE(U, K, K)
    DO I=1, 10
    U = 1
    END DO
    !$OSS END TASKLOOP

    !$OSS TASKLOOP DO DEFAULT(FIRSTPRIVATE) PRIVATE(J, J) FIRSTPRIVATE(U, K, K)
    DO I=1, 10
    U = 1
    END DO
    !$OSS END TASKLOOP DO

end program




! FIRDialect-LABEL:   func.func @_QQmain() attributes {fir.bindc_name = "TASK"} {
! FIRDialect:           %[[CONSTANT_0:[-0-9A-Za-z._]+]] = arith.constant 1 : i64
! FIRDialect:           %[[CONSTANT_1:[-0-9A-Za-z._]+]] = arith.constant 10 : i32
! FIRDialect:           %[[CONSTANT_2:[-0-9A-Za-z._]+]] = arith.constant 1 : i32
! FIRDialect:           %[[DUMMY_SCOPE_0:[-0-9A-Za-z._]+]] = fir.dummy_scope : !fir.dscope
! FIRDialect:           %[[ALLOCA_0:[-0-9A-Za-z._]+]] = fir.alloca i32 {bindc_name = "i", uniq_name = "_QFEi"}
! FIRDialect:           %[[DECLARE_0:[-0-9A-Za-z._]+]] = fir.declare %[[ALLOCA_0]] {uniq_name = "_QFEi"} : (!fir.ref<i32>) -> !fir.ref<i32>
! FIRDialect:           %[[ALLOCA_1:[-0-9A-Za-z._]+]] = fir.alloca i32 {bindc_name = "j", uniq_name = "_QFEj"}
! FIRDialect:           %[[DECLARE_1:[-0-9A-Za-z._]+]] = fir.declare %[[ALLOCA_1]] {uniq_name = "_QFEj"} : (!fir.ref<i32>) -> !fir.ref<i32>
! FIRDialect:           %[[ALLOCA_2:[-0-9A-Za-z._]+]] = fir.alloca i32 {bindc_name = "k", uniq_name = "_QFEk"}
! FIRDialect:           %[[DECLARE_2:[-0-9A-Za-z._]+]] = fir.declare %[[ALLOCA_2]] {uniq_name = "_QFEk"} : (!fir.ref<i32>) -> !fir.ref<i32>
! FIRDialect:           %[[ALLOCA_3:[-0-9A-Za-z._]+]] = fir.alloca i32 {bindc_name = "u", uniq_name = "_QFEu"}
! FIRDialect:           %[[DECLARE_3:[-0-9A-Za-z._]+]] = fir.declare %[[ALLOCA_3]] {uniq_name = "_QFEu"} : (!fir.ref<i32>) -> !fir.ref<i32>
! FIRDialect:           %[[UNDEFINED_0:[-0-9A-Za-z._]+]] = fir.undefined !fir.oss<i32>
! FIRDialect:           %[[UNDEFINED_1:[-0-9A-Za-z._]+]] = fir.undefined !fir.oss<i32>
! FIRDialect:           %[[UNDEFINED_2:[-0-9A-Za-z._]+]] = fir.undefined !fir.oss<i32>
! FIRDialect:           %[[UNDEFINED_3:[-0-9A-Za-z._]+]] = fir.undefined !fir.oss<i32>
! FIRDialect:           %[[UNDEFINED_4:[-0-9A-Za-z._]+]] = fir.undefined !fir.oss<i32>
! FIRDialect:           %[[UNDEFINED_5:[-0-9A-Za-z._]+]] = fir.undefined !fir.oss<i32>
! FIRDialect:           %[[UNDEFINED_6:[-0-9A-Za-z._]+]] = fir.undefined !fir.oss<i32>
! FIRDialect:           %[[UNDEFINED_7:[-0-9A-Za-z._]+]] = fir.undefined !fir.oss<i32>
! FIRDialect:           oss.task_for lower_bound(%[[CONSTANT_2]] : i32) upper_bound(%[[CONSTANT_1]] : i32) step(%[[CONSTANT_2]] : i32) loop_type(%[[CONSTANT_0]] : i64) ind_var(%[[DECLARE_0]] : !fir.ref<i32>) private(%[[DECLARE_0]], %[[DECLARE_0]], %[[DECLARE_1]], %[[DECLARE_1]] : !fir.ref<i32>, !fir.ref<i32>, !fir.ref<i32>, !fir.ref<i32>) private_type(%[[UNDEFINED_0]], %[[UNDEFINED_1]], %[[UNDEFINED_2]], %[[UNDEFINED_3]] : !fir.oss<i32>, !fir.oss<i32>, !fir.oss<i32>, !fir.oss<i32>) firstprivate(%[[DECLARE_2]], %[[DECLARE_2]], %[[DECLARE_3]], %[[DECLARE_3]] : !fir.ref<i32>, !fir.ref<i32>, !fir.ref<i32>, !fir.ref<i32>) firstprivate_type(%[[UNDEFINED_4]], %[[UNDEFINED_5]], %[[UNDEFINED_6]], %[[UNDEFINED_7]] : !fir.oss<i32>, !fir.oss<i32>, !fir.oss<i32>, !fir.oss<i32>) default(deffirstprivate) {
! FIRDialect:             %[[CONSTANT_3:[-0-9A-Za-z._]+]] = arith.constant 1 : i32
! FIRDialect:             fir.store %[[CONSTANT_3]] to %[[DECLARE_3]] : !fir.ref<i32>
! FIRDialect:             oss.terminator
! FIRDialect:           }
! FIRDialect:           %[[UNDEFINED_8:[-0-9A-Za-z._]+]] = fir.undefined !fir.oss<i32>
! FIRDialect:           %[[UNDEFINED_9:[-0-9A-Za-z._]+]] = fir.undefined !fir.oss<i32>
! FIRDialect:           %[[UNDEFINED_10:[-0-9A-Za-z._]+]] = fir.undefined !fir.oss<i32>
! FIRDialect:           %[[UNDEFINED_11:[-0-9A-Za-z._]+]] = fir.undefined !fir.oss<i32>
! FIRDialect:           %[[UNDEFINED_12:[-0-9A-Za-z._]+]] = fir.undefined !fir.oss<i32>
! FIRDialect:           %[[UNDEFINED_13:[-0-9A-Za-z._]+]] = fir.undefined !fir.oss<i32>
! FIRDialect:           %[[UNDEFINED_14:[-0-9A-Za-z._]+]] = fir.undefined !fir.oss<i32>
! FIRDialect:           %[[UNDEFINED_15:[-0-9A-Za-z._]+]] = fir.undefined !fir.oss<i32>
! FIRDialect:           oss.taskloop lower_bound(%[[CONSTANT_2]] : i32) upper_bound(%[[CONSTANT_1]] : i32) step(%[[CONSTANT_2]] : i32) loop_type(%[[CONSTANT_0]] : i64) ind_var(%[[DECLARE_0]] : !fir.ref<i32>) private(%[[DECLARE_0]], %[[DECLARE_0]], %[[DECLARE_1]], %[[DECLARE_1]] : !fir.ref<i32>, !fir.ref<i32>, !fir.ref<i32>, !fir.ref<i32>) private_type(%[[UNDEFINED_8]], %[[UNDEFINED_9]], %[[UNDEFINED_10]], %[[UNDEFINED_11]] : !fir.oss<i32>, !fir.oss<i32>, !fir.oss<i32>, !fir.oss<i32>) firstprivate(%[[DECLARE_2]], %[[DECLARE_2]], %[[DECLARE_3]], %[[DECLARE_3]] : !fir.ref<i32>, !fir.ref<i32>, !fir.ref<i32>, !fir.ref<i32>) firstprivate_type(%[[UNDEFINED_12]], %[[UNDEFINED_13]], %[[UNDEFINED_14]], %[[UNDEFINED_15]] : !fir.oss<i32>, !fir.oss<i32>, !fir.oss<i32>, !fir.oss<i32>) default(deffirstprivate) {
! FIRDialect:             %[[CONSTANT_4:[-0-9A-Za-z._]+]] = arith.constant 1 : i32
! FIRDialect:             fir.store %[[CONSTANT_4]] to %[[DECLARE_3]] : !fir.ref<i32>
! FIRDialect:             oss.terminator
! FIRDialect:           }
! FIRDialect:           %[[UNDEFINED_16:[-0-9A-Za-z._]+]] = fir.undefined !fir.oss<i32>
! FIRDialect:           %[[UNDEFINED_17:[-0-9A-Za-z._]+]] = fir.undefined !fir.oss<i32>
! FIRDialect:           %[[UNDEFINED_18:[-0-9A-Za-z._]+]] = fir.undefined !fir.oss<i32>
! FIRDialect:           %[[UNDEFINED_19:[-0-9A-Za-z._]+]] = fir.undefined !fir.oss<i32>
! FIRDialect:           %[[UNDEFINED_20:[-0-9A-Za-z._]+]] = fir.undefined !fir.oss<i32>
! FIRDialect:           %[[UNDEFINED_21:[-0-9A-Za-z._]+]] = fir.undefined !fir.oss<i32>
! FIRDialect:           %[[UNDEFINED_22:[-0-9A-Za-z._]+]] = fir.undefined !fir.oss<i32>
! FIRDialect:           %[[UNDEFINED_23:[-0-9A-Za-z._]+]] = fir.undefined !fir.oss<i32>
! FIRDialect:           oss.taskloop_for lower_bound(%[[CONSTANT_2]] : i32) upper_bound(%[[CONSTANT_1]] : i32) step(%[[CONSTANT_2]] : i32) loop_type(%[[CONSTANT_0]] : i64) ind_var(%[[DECLARE_0]] : !fir.ref<i32>) private(%[[DECLARE_0]], %[[DECLARE_0]], %[[DECLARE_1]], %[[DECLARE_1]] : !fir.ref<i32>, !fir.ref<i32>, !fir.ref<i32>, !fir.ref<i32>) private_type(%[[UNDEFINED_16]], %[[UNDEFINED_17]], %[[UNDEFINED_18]], %[[UNDEFINED_19]] : !fir.oss<i32>, !fir.oss<i32>, !fir.oss<i32>, !fir.oss<i32>) firstprivate(%[[DECLARE_2]], %[[DECLARE_2]], %[[DECLARE_3]], %[[DECLARE_3]] : !fir.ref<i32>, !fir.ref<i32>, !fir.ref<i32>, !fir.ref<i32>) firstprivate_type(%[[UNDEFINED_20]], %[[UNDEFINED_21]], %[[UNDEFINED_22]], %[[UNDEFINED_23]] : !fir.oss<i32>, !fir.oss<i32>, !fir.oss<i32>, !fir.oss<i32>) default(deffirstprivate) {
! FIRDialect:             %[[CONSTANT_5:[-0-9A-Za-z._]+]] = arith.constant 1 : i32
! FIRDialect:             fir.store %[[CONSTANT_5]] to %[[DECLARE_3]] : !fir.ref<i32>
! FIRDialect:             oss.terminator
! FIRDialect:           }
! FIRDialect:           return
! FIRDialect:         }
! FIRDialect:         func.func private @_FortranAProgramStart(i32, !llvm.ptr, !llvm.ptr, !llvm.ptr)
! FIRDialect:         func.func private @_FortranAProgramEndStatement()

