! NOTE: Assertions have been autogenerated by /home/rpenacob/llvm-mono/mlir/utils/generate-test-checks.py
! Test test checks we do not emit duplicates data-sharings

! RUN: bbc -fompss-2 -emit-fir %s -o - | FileCheck %s --check-prefix=FIRDialect

program task
    INTEGER :: I, J, K

    !$OSS TASK DEFAULT(FIRSTPRIVATE) PRIVATE(J, J) FIRSTPRIVATE(I, K, K)
    I = 1
    !$OSS END TASK

end program


! FIRDialect-LABEL:   func.func @_QQmain() attributes {fir.bindc_name = "task"} {
! FIRDialect:           %[[VAL_0:[-0-9A-Za-z._]+]] = fir.alloca i32 {bindc_name = "i", uniq_name = "_QFEi"}
! FIRDialect:           %[[VAL_1:[-0-9A-Za-z._]+]] = fir.declare %[[VAL_0]] {uniq_name = "_QFEi"} : (!fir.ref<i32>) -> !fir.ref<i32>
! FIRDialect:           %[[VAL_2:[-0-9A-Za-z._]+]] = fir.alloca i32 {bindc_name = "j", uniq_name = "_QFEj"}
! FIRDialect:           %[[VAL_3:[-0-9A-Za-z._]+]] = fir.declare %[[VAL_2]] {uniq_name = "_QFEj"} : (!fir.ref<i32>) -> !fir.ref<i32>
! FIRDialect:           %[[VAL_4:[-0-9A-Za-z._]+]] = fir.alloca i32 {bindc_name = "k", uniq_name = "_QFEk"}
! FIRDialect:           %[[VAL_5:[-0-9A-Za-z._]+]] = fir.declare %[[VAL_4]] {uniq_name = "_QFEk"} : (!fir.ref<i32>) -> !fir.ref<i32>
! FIRDialect:           %[[VAL_6:[-0-9A-Za-z._]+]] = fir.undefined !fir.oss<i32>
! FIRDialect:           oss.task private(%[[VAL_3]], %[[VAL_3]] : !fir.ref<i32>, !fir.ref<i32>) private_type(%[[VAL_6]], %[[VAL_6]] : !fir.oss<i32>, !fir.oss<i32>) firstprivate(%[[VAL_1]], %[[VAL_1]], %[[VAL_5]], %[[VAL_5]] : !fir.ref<i32>, !fir.ref<i32>, !fir.ref<i32>, !fir.ref<i32>) firstprivate_type(%[[VAL_6]], %[[VAL_6]], %[[VAL_6]], %[[VAL_6]] : !fir.oss<i32>, !fir.oss<i32>, !fir.oss<i32>, !fir.oss<i32>) default( deffirstprivate) {
! FIRDialect:             %[[VAL_7:[-0-9A-Za-z._]+]] = arith.constant 1 : i32
! FIRDialect:             fir.store %[[VAL_7]] to %[[VAL_1]] : !fir.ref<i32>
! FIRDialect:             oss.terminator
! FIRDialect:           }
! FIRDialect:           return
! FIRDialect:         }

! FIRDialect-LABEL:   fir.global @_QQEnvironmentDefaults constant : !fir.ref<tuple<i32, !fir.ref<!fir.array<0xtuple<!fir.ref<i8>, !fir.ref<i8>>>>>> {
! FIRDialect:           %[[VAL_0:[-0-9A-Za-z._]+]] = fir.zero_bits !fir.ref<tuple<i32, !fir.ref<!fir.array<0xtuple<!fir.ref<i8>, !fir.ref<i8>>>>>>
! FIRDialect:           fir.has_value %[[VAL_0]] : !fir.ref<tuple<i32, !fir.ref<!fir.array<0xtuple<!fir.ref<i8>, !fir.ref<i8>>>>>>
! FIRDialect:         }

