! NOTE: Assertions have been autogenerated by /home/rpenacob/llvm-mono/mlir/utils/generate-test-checks.py
! RUN: flang-new -fc1 -emit-fir -fompss-2 -o - %s -flang-deprecated-no-hlfir | FileCheck %s --check-prefix=FIRDialect

! - [x] assumed-shape
! - [x] deferred-shape

! NOTE: assumed-shape do not have init/copy/deinit
! functions

PROGRAM P
  IMPLICIT NONE
  INTEGER :: ARRAY(10)
  INTEGER, ALLOCATABLE :: GLOB_ALLOC(:)
  INTEGER, POINTER :: GLOB_PTR(:)

  !$OSS TASK SHARED(GLOB_ALLOC, GLOB_PTR)
  GLOB_ALLOC(7) = 7
  GLOB_PTR(7) = 7
  !$OSS END TASK

  !$OSS TASK PRIVATE(GLOB_ALLOC, GLOB_PTR)
  GLOB_ALLOC(7) = 7
  GLOB_PTR(7) = 7
  !$OSS END TASK

  !$OSS TASK FIRSTPRIVATE(GLOB_ALLOC, GLOB_PTR)
  GLOB_ALLOC(7) = 7
  GLOB_PTR(7) = 7
  !$OSS END TASK

  CALL FOO(GLOB_ALLOC, GLOB_PTR, ARRAY)

CONTAINS

SUBROUTINE FOO(DUMMY_ALLOC, DUMMY_PTR, DUMMY_ARRAY)
  IMPLICIT NONE
  INTEGER, ALLOCATABLE :: DUMMY_ALLOC(:)
  INTEGER, POINTER :: DUMMY_PTR(:)
  INTEGER :: DUMMY_ARRAY(:)
  INTEGER, ALLOCATABLE :: LOCAL_ALLOC(:)
  INTEGER, POINTER :: LOCAL_PTR(:)

  !$OSS TASK SHARED(DUMMY_ALLOC, DUMMY_PTR, DUMMY_ARRAY)
  DUMMY_ALLOC(7) = 7
  DUMMY_PTR(7) = 7
  DUMMY_ARRAY(7) = 7
  !$OSS END TASK

  !$OSS TASK PRIVATE(DUMMY_ALLOC, DUMMY_PTR, DUMMY_ARRAY)
  DUMMY_ALLOC(7) = 7
  DUMMY_PTR(7) = 7
  DUMMY_ARRAY(7) = 7
  !$OSS END TASK

  !$OSS TASK FIRSTPRIVATE(DUMMY_ALLOC, DUMMY_PTR, DUMMY_ARRAY)
  DUMMY_ALLOC(7) = 7
  DUMMY_PTR(7) = 7
  DUMMY_ARRAY(7) = 7
  !$OSS END TASK

  !$OSS TASK SHARED(LOCAL_ALLOC, LOCAL_PTR)
  LOCAL_ALLOC(7) = 7
  LOCAL_PTR(7) = 7
  !$OSS END TASK

  !$OSS TASK PRIVATE(LOCAL_ALLOC, LOCAL_PTR)
  LOCAL_ALLOC(7) = 7
  LOCAL_PTR(7) = 7
  !$OSS END TASK

  !$OSS TASK FIRSTPRIVATE(LOCAL_ALLOC, LOCAL_PTR)
  LOCAL_ALLOC(7) = 7
  LOCAL_PTR(7) = 7
  !$OSS END TASK

END SUBROUTINE
END PROGRAM


! FIRDialect-LABEL:   func.func @_QQmain() attributes {fir.bindc_name = "P"} {
! FIRDialect:           %[[VAL_0:[-0-9A-Za-z._]+]] = fir.address_of(@_QFEarray) : !fir.ref<!fir.array<10xi32>>
! FIRDialect:           %[[VAL_1:[-0-9A-Za-z._]+]] = arith.constant 10 : index
! FIRDialect:           %[[VAL_2:[-0-9A-Za-z._]+]] = fir.address_of(@_QFEglob_alloc) : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>
! FIRDialect:           %[[VAL_3:[-0-9A-Za-z._]+]] = fir.address_of(@_QFEglob_ptr) : !fir.ref<!fir.box<!fir.ptr<!fir.array<?xi32>>>>
! FIRDialect:           %[[VAL_4:[-0-9A-Za-z._]+]] = fir.undefined !fir.oss<!fir.box<!fir.heap<!fir.array<?xi32>>>>
! FIRDialect:           %[[VAL_5:[-0-9A-Za-z._]+]] = fir.undefined !fir.oss<!fir.box<!fir.ptr<!fir.array<?xi32>>>>
! FIRDialect:           oss.task shared(%[[VAL_2]], %[[VAL_3]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>, !fir.ref<!fir.box<!fir.ptr<!fir.array<?xi32>>>>) shared_type(%[[VAL_4]], %[[VAL_5]] : !fir.oss<!fir.box<!fir.heap<!fir.array<?xi32>>>>, !fir.oss<!fir.box<!fir.ptr<!fir.array<?xi32>>>>) {
! FIRDialect:             %[[VAL_6:[-0-9A-Za-z._]+]] = arith.constant 7 : i32
! FIRDialect:             %[[VAL_7:[-0-9A-Za-z._]+]] = fir.load %[[VAL_2]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>
! FIRDialect:             %[[VAL_8:[-0-9A-Za-z._]+]] = arith.constant 0 : index
! FIRDialect:             %[[VAL_9:[-0-9A-Za-z._]+]]:3 = fir.box_dims %[[VAL_7]], %[[VAL_8]] : (!fir.box<!fir.heap<!fir.array<?xi32>>>, index) -> (index, index, index)
! FIRDialect:             %[[VAL_10:[-0-9A-Za-z._]+]] = fir.box_addr %[[VAL_7]] : (!fir.box<!fir.heap<!fir.array<?xi32>>>) -> !fir.heap<!fir.array<?xi32>>
! FIRDialect:             %[[VAL_11:[-0-9A-Za-z._]+]] = arith.constant 7 : i64
! FIRDialect:             %[[VAL_12:[-0-9A-Za-z._]+]] = fir.convert %[[VAL_9]]#0 : (index) -> i64
! FIRDialect:             %[[VAL_13:[-0-9A-Za-z._]+]] = arith.subi %[[VAL_11]], %[[VAL_12]] : i64
! FIRDialect:             %[[VAL_14:[-0-9A-Za-z._]+]] = fir.coordinate_of %[[VAL_10]], %[[VAL_13]] : (!fir.heap<!fir.array<?xi32>>, i64) -> !fir.ref<i32>
! FIRDialect:             fir.store %[[VAL_6]] to %[[VAL_14]] : !fir.ref<i32>
! FIRDialect:             %[[VAL_15:[-0-9A-Za-z._]+]] = arith.constant 7 : i32
! FIRDialect:             %[[VAL_16:[-0-9A-Za-z._]+]] = fir.load %[[VAL_3]] : !fir.ref<!fir.box<!fir.ptr<!fir.array<?xi32>>>>
! FIRDialect:             %[[VAL_17:[-0-9A-Za-z._]+]] = arith.constant 0 : index
! FIRDialect:             %[[VAL_18:[-0-9A-Za-z._]+]]:3 = fir.box_dims %[[VAL_16]], %[[VAL_17]] : (!fir.box<!fir.ptr<!fir.array<?xi32>>>, index) -> (index, index, index)
! FIRDialect:             %[[VAL_19:[-0-9A-Za-z._]+]] = arith.constant 7 : i64
! FIRDialect:             %[[VAL_20:[-0-9A-Za-z._]+]] = fir.convert %[[VAL_18]]#0 : (index) -> i64
! FIRDialect:             %[[VAL_21:[-0-9A-Za-z._]+]] = arith.subi %[[VAL_19]], %[[VAL_20]] : i64
! FIRDialect:             %[[VAL_22:[-0-9A-Za-z._]+]] = fir.coordinate_of %[[VAL_16]], %[[VAL_21]] : (!fir.box<!fir.ptr<!fir.array<?xi32>>>, i64) -> !fir.ref<i32>
! FIRDialect:             fir.store %[[VAL_15]] to %[[VAL_22]] : !fir.ref<i32>
! FIRDialect:             oss.terminator
! FIRDialect:           }
! FIRDialect:           %[[VAL_23:[-0-9A-Za-z._]+]] = oss.copy base(%[[VAL_2]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>) function(@compute.copy0) -> i32
! FIRDialect:           %[[VAL_24:[-0-9A-Za-z._]+]] = oss.copy base(%[[VAL_2]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>) function(@compute.deinit0) -> i32
! FIRDialect:           %[[VAL_25:[-0-9A-Za-z._]+]] = oss.copy base(%[[VAL_3]] : !fir.ref<!fir.box<!fir.ptr<!fir.array<?xi32>>>>) function(@compute.init0) -> i32
! FIRDialect:           %[[VAL_26:[-0-9A-Za-z._]+]] = oss.copy base(%[[VAL_3]] : !fir.ref<!fir.box<!fir.ptr<!fir.array<?xi32>>>>) function(@compute.deinit1) -> i32
! FIRDialect:           %[[VAL_27:[-0-9A-Za-z._]+]] = fir.undefined !fir.oss<!fir.box<!fir.ptr<!fir.array<?xi32>>>>
! FIRDialect:           %[[VAL_28:[-0-9A-Za-z._]+]] = fir.undefined !fir.oss<!fir.box<!fir.heap<!fir.array<?xi32>>>>
! FIRDialect:           oss.task private(%[[VAL_3]] : !fir.ref<!fir.box<!fir.ptr<!fir.array<?xi32>>>>) private_type(%[[VAL_27]] : !fir.oss<!fir.box<!fir.ptr<!fir.array<?xi32>>>>) firstprivate(%[[VAL_2]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>) firstprivate_type(%[[VAL_28]] : !fir.oss<!fir.box<!fir.heap<!fir.array<?xi32>>>>) copy(%[[VAL_23]] : i32) init(%[[VAL_25]] : i32) deinit(%[[VAL_24]], %[[VAL_26]] : i32, i32) {
! FIRDialect:             %[[VAL_29:[-0-9A-Za-z._]+]] = arith.constant 7 : i32
! FIRDialect:             %[[VAL_30:[-0-9A-Za-z._]+]] = fir.load %[[VAL_2]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>
! FIRDialect:             %[[VAL_31:[-0-9A-Za-z._]+]] = arith.constant 0 : index
! FIRDialect:             %[[VAL_32:[-0-9A-Za-z._]+]]:3 = fir.box_dims %[[VAL_30]], %[[VAL_31]] : (!fir.box<!fir.heap<!fir.array<?xi32>>>, index) -> (index, index, index)
! FIRDialect:             %[[VAL_33:[-0-9A-Za-z._]+]] = fir.box_addr %[[VAL_30]] : (!fir.box<!fir.heap<!fir.array<?xi32>>>) -> !fir.heap<!fir.array<?xi32>>
! FIRDialect:             %[[VAL_34:[-0-9A-Za-z._]+]] = arith.constant 7 : i64
! FIRDialect:             %[[VAL_35:[-0-9A-Za-z._]+]] = fir.convert %[[VAL_32]]#0 : (index) -> i64
! FIRDialect:             %[[VAL_36:[-0-9A-Za-z._]+]] = arith.subi %[[VAL_34]], %[[VAL_35]] : i64
! FIRDialect:             %[[VAL_37:[-0-9A-Za-z._]+]] = fir.coordinate_of %[[VAL_33]], %[[VAL_36]] : (!fir.heap<!fir.array<?xi32>>, i64) -> !fir.ref<i32>
! FIRDialect:             fir.store %[[VAL_29]] to %[[VAL_37]] : !fir.ref<i32>
! FIRDialect:             %[[VAL_38:[-0-9A-Za-z._]+]] = arith.constant 7 : i32
! FIRDialect:             %[[VAL_39:[-0-9A-Za-z._]+]] = fir.load %[[VAL_3]] : !fir.ref<!fir.box<!fir.ptr<!fir.array<?xi32>>>>
! FIRDialect:             %[[VAL_40:[-0-9A-Za-z._]+]] = arith.constant 0 : index
! FIRDialect:             %[[VAL_41:[-0-9A-Za-z._]+]]:3 = fir.box_dims %[[VAL_39]], %[[VAL_40]] : (!fir.box<!fir.ptr<!fir.array<?xi32>>>, index) -> (index, index, index)
! FIRDialect:             %[[VAL_42:[-0-9A-Za-z._]+]] = arith.constant 7 : i64
! FIRDialect:             %[[VAL_43:[-0-9A-Za-z._]+]] = fir.convert %[[VAL_41]]#0 : (index) -> i64
! FIRDialect:             %[[VAL_44:[-0-9A-Za-z._]+]] = arith.subi %[[VAL_42]], %[[VAL_43]] : i64
! FIRDialect:             %[[VAL_45:[-0-9A-Za-z._]+]] = fir.coordinate_of %[[VAL_39]], %[[VAL_44]] : (!fir.box<!fir.ptr<!fir.array<?xi32>>>, i64) -> !fir.ref<i32>
! FIRDialect:             fir.store %[[VAL_38]] to %[[VAL_45]] : !fir.ref<i32>
! FIRDialect:             oss.terminator
! FIRDialect:           }
! FIRDialect:           %[[VAL_46:[-0-9A-Za-z._]+]] = oss.copy base(%[[VAL_2]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>) function(@compute.copy1) -> i32
! FIRDialect:           %[[VAL_47:[-0-9A-Za-z._]+]] = oss.copy base(%[[VAL_2]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>) function(@compute.deinit2) -> i32
! FIRDialect:           %[[VAL_48:[-0-9A-Za-z._]+]] = oss.copy base(%[[VAL_3]] : !fir.ref<!fir.box<!fir.ptr<!fir.array<?xi32>>>>) function(@compute.copy2) -> i32
! FIRDialect:           %[[VAL_49:[-0-9A-Za-z._]+]] = oss.copy base(%[[VAL_3]] : !fir.ref<!fir.box<!fir.ptr<!fir.array<?xi32>>>>) function(@compute.deinit3) -> i32
! FIRDialect:           %[[VAL_50:[-0-9A-Za-z._]+]] = fir.undefined !fir.oss<!fir.box<!fir.heap<!fir.array<?xi32>>>>
! FIRDialect:           %[[VAL_51:[-0-9A-Za-z._]+]] = fir.undefined !fir.oss<!fir.box<!fir.ptr<!fir.array<?xi32>>>>
! FIRDialect:           oss.task firstprivate(%[[VAL_2]], %[[VAL_3]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>, !fir.ref<!fir.box<!fir.ptr<!fir.array<?xi32>>>>) firstprivate_type(%[[VAL_50]], %[[VAL_51]] : !fir.oss<!fir.box<!fir.heap<!fir.array<?xi32>>>>, !fir.oss<!fir.box<!fir.ptr<!fir.array<?xi32>>>>) copy(%[[VAL_46]], %[[VAL_48]] : i32, i32) deinit(%[[VAL_47]], %[[VAL_49]] : i32, i32) {
! FIRDialect:             %[[VAL_52:[-0-9A-Za-z._]+]] = arith.constant 7 : i32
! FIRDialect:             %[[VAL_53:[-0-9A-Za-z._]+]] = fir.load %[[VAL_2]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>
! FIRDialect:             %[[VAL_54:[-0-9A-Za-z._]+]] = arith.constant 0 : index
! FIRDialect:             %[[VAL_55:[-0-9A-Za-z._]+]]:3 = fir.box_dims %[[VAL_53]], %[[VAL_54]] : (!fir.box<!fir.heap<!fir.array<?xi32>>>, index) -> (index, index, index)
! FIRDialect:             %[[VAL_56:[-0-9A-Za-z._]+]] = fir.box_addr %[[VAL_53]] : (!fir.box<!fir.heap<!fir.array<?xi32>>>) -> !fir.heap<!fir.array<?xi32>>
! FIRDialect:             %[[VAL_57:[-0-9A-Za-z._]+]] = arith.constant 7 : i64
! FIRDialect:             %[[VAL_58:[-0-9A-Za-z._]+]] = fir.convert %[[VAL_55]]#0 : (index) -> i64
! FIRDialect:             %[[VAL_59:[-0-9A-Za-z._]+]] = arith.subi %[[VAL_57]], %[[VAL_58]] : i64
! FIRDialect:             %[[VAL_60:[-0-9A-Za-z._]+]] = fir.coordinate_of %[[VAL_56]], %[[VAL_59]] : (!fir.heap<!fir.array<?xi32>>, i64) -> !fir.ref<i32>
! FIRDialect:             fir.store %[[VAL_52]] to %[[VAL_60]] : !fir.ref<i32>
! FIRDialect:             %[[VAL_61:[-0-9A-Za-z._]+]] = arith.constant 7 : i32
! FIRDialect:             %[[VAL_62:[-0-9A-Za-z._]+]] = fir.load %[[VAL_3]] : !fir.ref<!fir.box<!fir.ptr<!fir.array<?xi32>>>>
! FIRDialect:             %[[VAL_63:[-0-9A-Za-z._]+]] = arith.constant 0 : index
! FIRDialect:             %[[VAL_64:[-0-9A-Za-z._]+]]:3 = fir.box_dims %[[VAL_62]], %[[VAL_63]] : (!fir.box<!fir.ptr<!fir.array<?xi32>>>, index) -> (index, index, index)
! FIRDialect:             %[[VAL_65:[-0-9A-Za-z._]+]] = arith.constant 7 : i64
! FIRDialect:             %[[VAL_66:[-0-9A-Za-z._]+]] = fir.convert %[[VAL_64]]#0 : (index) -> i64
! FIRDialect:             %[[VAL_67:[-0-9A-Za-z._]+]] = arith.subi %[[VAL_65]], %[[VAL_66]] : i64
! FIRDialect:             %[[VAL_68:[-0-9A-Za-z._]+]] = fir.coordinate_of %[[VAL_62]], %[[VAL_67]] : (!fir.box<!fir.ptr<!fir.array<?xi32>>>, i64) -> !fir.ref<i32>
! FIRDialect:             fir.store %[[VAL_61]] to %[[VAL_68]] : !fir.ref<i32>
! FIRDialect:             oss.terminator
! FIRDialect:           }
! FIRDialect:           %[[VAL_69:[-0-9A-Za-z._]+]] = fir.shape %[[VAL_1]] : (index) -> !fir.shape<1>
! FIRDialect:           %[[VAL_70:[-0-9A-Za-z._]+]] = fir.embox %[[VAL_0]](%[[VAL_69]]) : (!fir.ref<!fir.array<10xi32>>, !fir.shape<1>) -> !fir.box<!fir.array<10xi32>>
! FIRDialect:           %[[VAL_71:[-0-9A-Za-z._]+]] = fir.convert %[[VAL_70]] : (!fir.box<!fir.array<10xi32>>) -> !fir.box<!fir.array<?xi32>>
! FIRDialect:           fir.call @_QFPfoo(%[[VAL_2]], %[[VAL_3]], %[[VAL_71]]) fastmath<contract> : (!fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>, !fir.ref<!fir.box<!fir.ptr<!fir.array<?xi32>>>>, !fir.box<!fir.array<?xi32>>) -> ()
! FIRDialect:           return
! FIRDialect:         }

! FIRDialect-LABEL:   func.func private @_QFPfoo(
! FIRDialect-SAME:                               %[[VAL_0:[-0-9A-Za-z._]+]]: !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>> {fir.bindc_name = "dummy_alloc"},
! FIRDialect-SAME:                               %[[VAL_1:[-0-9A-Za-z._]+]]: !fir.ref<!fir.box<!fir.ptr<!fir.array<?xi32>>>> {fir.bindc_name = "dummy_ptr"},
! FIRDialect-SAME:                               %[[VAL_2:[-0-9A-Za-z._]+]]: !fir.box<!fir.array<?xi32>> {fir.bindc_name = "dummy_array"})
! FIRDialect:           %[[VAL_3:[-0-9A-Za-z._]+]] = fir.alloca !fir.box<!fir.heap<!fir.array<?xi32>>> {bindc_name = "local_alloc", uniq_name = "_QFFfooElocal_alloc"}
! FIRDialect:           %[[VAL_4:[-0-9A-Za-z._]+]] = fir.zero_bits !fir.heap<!fir.array<?xi32>>
! FIRDialect:           %[[VAL_5:[-0-9A-Za-z._]+]] = arith.constant 0 : index
! FIRDialect:           %[[VAL_6:[-0-9A-Za-z._]+]] = fir.shape %[[VAL_5]] : (index) -> !fir.shape<1>
! FIRDialect:           %[[VAL_7:[-0-9A-Za-z._]+]] = fir.embox %[[VAL_4]](%[[VAL_6]]) : (!fir.heap<!fir.array<?xi32>>, !fir.shape<1>) -> !fir.box<!fir.heap<!fir.array<?xi32>>>
! FIRDialect:           fir.store %[[VAL_7]] to %[[VAL_3]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>
! FIRDialect:           %[[VAL_8:[-0-9A-Za-z._]+]] = fir.alloca !fir.box<!fir.ptr<!fir.array<?xi32>>> {bindc_name = "local_ptr", uniq_name = "_QFFfooElocal_ptr"}
! FIRDialect:           %[[VAL_9:[-0-9A-Za-z._]+]] = fir.zero_bits !fir.ptr<!fir.array<?xi32>>
! FIRDialect:           %[[VAL_10:[-0-9A-Za-z._]+]] = arith.constant 0 : index
! FIRDialect:           %[[VAL_11:[-0-9A-Za-z._]+]] = fir.shape %[[VAL_10]] : (index) -> !fir.shape<1>
! FIRDialect:           %[[VAL_12:[-0-9A-Za-z._]+]] = fir.embox %[[VAL_9]](%[[VAL_11]]) : (!fir.ptr<!fir.array<?xi32>>, !fir.shape<1>) -> !fir.box<!fir.ptr<!fir.array<?xi32>>>
! FIRDialect:           fir.store %[[VAL_12]] to %[[VAL_8]] : !fir.ref<!fir.box<!fir.ptr<!fir.array<?xi32>>>>
! FIRDialect:           %[[VAL_13:[-0-9A-Za-z._]+]] = fir.undefined !fir.oss<!fir.box<!fir.heap<!fir.array<?xi32>>>>
! FIRDialect:           %[[VAL_14:[-0-9A-Za-z._]+]] = fir.undefined !fir.oss<!fir.box<!fir.ptr<!fir.array<?xi32>>>>
! FIRDialect:           %[[VAL_15:[-0-9A-Za-z._]+]] = fir.undefined !fir.oss<!fir.box<!fir.array<?xi32>>>
! FIRDialect:           oss.task shared(%[[VAL_0]], %[[VAL_1]], %[[VAL_2]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>, !fir.ref<!fir.box<!fir.ptr<!fir.array<?xi32>>>>, !fir.box<!fir.array<?xi32>>) shared_type(%[[VAL_13]], %[[VAL_14]], %[[VAL_15]] : !fir.oss<!fir.box<!fir.heap<!fir.array<?xi32>>>>, !fir.oss<!fir.box<!fir.ptr<!fir.array<?xi32>>>>, !fir.oss<!fir.box<!fir.array<?xi32>>>) {
! FIRDialect:             %[[VAL_16:[-0-9A-Za-z._]+]] = arith.constant 7 : i32
! FIRDialect:             %[[VAL_17:[-0-9A-Za-z._]+]] = fir.load %[[VAL_0]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>
! FIRDialect:             %[[VAL_18:[-0-9A-Za-z._]+]] = arith.constant 0 : index
! FIRDialect:             %[[VAL_19:[-0-9A-Za-z._]+]]:3 = fir.box_dims %[[VAL_17]], %[[VAL_18]] : (!fir.box<!fir.heap<!fir.array<?xi32>>>, index) -> (index, index, index)
! FIRDialect:             %[[VAL_20:[-0-9A-Za-z._]+]] = fir.box_addr %[[VAL_17]] : (!fir.box<!fir.heap<!fir.array<?xi32>>>) -> !fir.heap<!fir.array<?xi32>>
! FIRDialect:             %[[VAL_21:[-0-9A-Za-z._]+]] = arith.constant 7 : i64
! FIRDialect:             %[[VAL_22:[-0-9A-Za-z._]+]] = fir.convert %[[VAL_19]]#0 : (index) -> i64
! FIRDialect:             %[[VAL_23:[-0-9A-Za-z._]+]] = arith.subi %[[VAL_21]], %[[VAL_22]] : i64
! FIRDialect:             %[[VAL_24:[-0-9A-Za-z._]+]] = fir.coordinate_of %[[VAL_20]], %[[VAL_23]] : (!fir.heap<!fir.array<?xi32>>, i64) -> !fir.ref<i32>
! FIRDialect:             fir.store %[[VAL_16]] to %[[VAL_24]] : !fir.ref<i32>
! FIRDialect:             %[[VAL_25:[-0-9A-Za-z._]+]] = arith.constant 7 : i32
! FIRDialect:             %[[VAL_26:[-0-9A-Za-z._]+]] = fir.load %[[VAL_1]] : !fir.ref<!fir.box<!fir.ptr<!fir.array<?xi32>>>>
! FIRDialect:             %[[VAL_27:[-0-9A-Za-z._]+]] = arith.constant 0 : index
! FIRDialect:             %[[VAL_28:[-0-9A-Za-z._]+]]:3 = fir.box_dims %[[VAL_26]], %[[VAL_27]] : (!fir.box<!fir.ptr<!fir.array<?xi32>>>, index) -> (index, index, index)
! FIRDialect:             %[[VAL_29:[-0-9A-Za-z._]+]] = arith.constant 7 : i64
! FIRDialect:             %[[VAL_30:[-0-9A-Za-z._]+]] = fir.convert %[[VAL_28]]#0 : (index) -> i64
! FIRDialect:             %[[VAL_31:[-0-9A-Za-z._]+]] = arith.subi %[[VAL_29]], %[[VAL_30]] : i64
! FIRDialect:             %[[VAL_32:[-0-9A-Za-z._]+]] = fir.coordinate_of %[[VAL_26]], %[[VAL_31]] : (!fir.box<!fir.ptr<!fir.array<?xi32>>>, i64) -> !fir.ref<i32>
! FIRDialect:             fir.store %[[VAL_25]] to %[[VAL_32]] : !fir.ref<i32>
! FIRDialect:             %[[VAL_33:[-0-9A-Za-z._]+]] = arith.constant 7 : i32
! FIRDialect:             %[[VAL_34:[-0-9A-Za-z._]+]] = arith.constant 7 : i64
! FIRDialect:             %[[VAL_35:[-0-9A-Za-z._]+]] = arith.constant 1 : i64
! FIRDialect:             %[[VAL_36:[-0-9A-Za-z._]+]] = arith.subi %[[VAL_34]], %[[VAL_35]] : i64
! FIRDialect:             %[[VAL_37:[-0-9A-Za-z._]+]] = fir.coordinate_of %[[VAL_2]], %[[VAL_36]] : (!fir.box<!fir.array<?xi32>>, i64) -> !fir.ref<i32>
! FIRDialect:             fir.store %[[VAL_33]] to %[[VAL_37]] : !fir.ref<i32>
! FIRDialect:             oss.terminator
! FIRDialect:           }
! FIRDialect:           %[[VAL_38:[-0-9A-Za-z._]+]] = oss.copy base(%[[VAL_0]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>) function(@compute.copy3) -> i32
! FIRDialect:           %[[VAL_39:[-0-9A-Za-z._]+]] = oss.copy base(%[[VAL_0]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>) function(@compute.deinit4) -> i32
! FIRDialect:           %[[VAL_40:[-0-9A-Za-z._]+]] = oss.copy base(%[[VAL_1]] : !fir.ref<!fir.box<!fir.ptr<!fir.array<?xi32>>>>) function(@compute.init1) -> i32
! FIRDialect:           %[[VAL_41:[-0-9A-Za-z._]+]] = oss.copy base(%[[VAL_1]] : !fir.ref<!fir.box<!fir.ptr<!fir.array<?xi32>>>>) function(@compute.deinit5) -> i32
! FIRDialect:           %[[VAL_42:[-0-9A-Za-z._]+]] = fir.undefined !fir.oss<!fir.box<!fir.ptr<!fir.array<?xi32>>>>
! FIRDialect:           %[[VAL_43:[-0-9A-Za-z._]+]] = fir.undefined !fir.oss<!fir.box<!fir.array<?xi32>>>
! FIRDialect:           %[[VAL_44:[-0-9A-Za-z._]+]] = fir.undefined !fir.oss<!fir.box<!fir.heap<!fir.array<?xi32>>>>
! FIRDialect:           oss.task private(%[[VAL_1]], %[[VAL_2]] : !fir.ref<!fir.box<!fir.ptr<!fir.array<?xi32>>>>, !fir.box<!fir.array<?xi32>>) private_type(%[[VAL_42]], %[[VAL_43]] : !fir.oss<!fir.box<!fir.ptr<!fir.array<?xi32>>>>, !fir.oss<!fir.box<!fir.array<?xi32>>>) firstprivate(%[[VAL_0]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>) firstprivate_type(%[[VAL_44]] : !fir.oss<!fir.box<!fir.heap<!fir.array<?xi32>>>>) copy(%[[VAL_38]] : i32) init(%[[VAL_40]] : i32) deinit(%[[VAL_39]], %[[VAL_41]] : i32, i32) {
! FIRDialect:             %[[VAL_45:[-0-9A-Za-z._]+]] = arith.constant 7 : i32
! FIRDialect:             %[[VAL_46:[-0-9A-Za-z._]+]] = fir.load %[[VAL_0]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>
! FIRDialect:             %[[VAL_47:[-0-9A-Za-z._]+]] = arith.constant 0 : index
! FIRDialect:             %[[VAL_48:[-0-9A-Za-z._]+]]:3 = fir.box_dims %[[VAL_46]], %[[VAL_47]] : (!fir.box<!fir.heap<!fir.array<?xi32>>>, index) -> (index, index, index)
! FIRDialect:             %[[VAL_49:[-0-9A-Za-z._]+]] = fir.box_addr %[[VAL_46]] : (!fir.box<!fir.heap<!fir.array<?xi32>>>) -> !fir.heap<!fir.array<?xi32>>
! FIRDialect:             %[[VAL_50:[-0-9A-Za-z._]+]] = arith.constant 7 : i64
! FIRDialect:             %[[VAL_51:[-0-9A-Za-z._]+]] = fir.convert %[[VAL_48]]#0 : (index) -> i64
! FIRDialect:             %[[VAL_52:[-0-9A-Za-z._]+]] = arith.subi %[[VAL_50]], %[[VAL_51]] : i64
! FIRDialect:             %[[VAL_53:[-0-9A-Za-z._]+]] = fir.coordinate_of %[[VAL_49]], %[[VAL_52]] : (!fir.heap<!fir.array<?xi32>>, i64) -> !fir.ref<i32>
! FIRDialect:             fir.store %[[VAL_45]] to %[[VAL_53]] : !fir.ref<i32>
! FIRDialect:             %[[VAL_54:[-0-9A-Za-z._]+]] = arith.constant 7 : i32
! FIRDialect:             %[[VAL_55:[-0-9A-Za-z._]+]] = fir.load %[[VAL_1]] : !fir.ref<!fir.box<!fir.ptr<!fir.array<?xi32>>>>
! FIRDialect:             %[[VAL_56:[-0-9A-Za-z._]+]] = arith.constant 0 : index
! FIRDialect:             %[[VAL_57:[-0-9A-Za-z._]+]]:3 = fir.box_dims %[[VAL_55]], %[[VAL_56]] : (!fir.box<!fir.ptr<!fir.array<?xi32>>>, index) -> (index, index, index)
! FIRDialect:             %[[VAL_58:[-0-9A-Za-z._]+]] = arith.constant 7 : i64
! FIRDialect:             %[[VAL_59:[-0-9A-Za-z._]+]] = fir.convert %[[VAL_57]]#0 : (index) -> i64
! FIRDialect:             %[[VAL_60:[-0-9A-Za-z._]+]] = arith.subi %[[VAL_58]], %[[VAL_59]] : i64
! FIRDialect:             %[[VAL_61:[-0-9A-Za-z._]+]] = fir.coordinate_of %[[VAL_55]], %[[VAL_60]] : (!fir.box<!fir.ptr<!fir.array<?xi32>>>, i64) -> !fir.ref<i32>
! FIRDialect:             fir.store %[[VAL_54]] to %[[VAL_61]] : !fir.ref<i32>
! FIRDialect:             %[[VAL_62:[-0-9A-Za-z._]+]] = arith.constant 7 : i32
! FIRDialect:             %[[VAL_63:[-0-9A-Za-z._]+]] = arith.constant 7 : i64
! FIRDialect:             %[[VAL_64:[-0-9A-Za-z._]+]] = arith.constant 1 : i64
! FIRDialect:             %[[VAL_65:[-0-9A-Za-z._]+]] = arith.subi %[[VAL_63]], %[[VAL_64]] : i64
! FIRDialect:             %[[VAL_66:[-0-9A-Za-z._]+]] = fir.coordinate_of %[[VAL_2]], %[[VAL_65]] : (!fir.box<!fir.array<?xi32>>, i64) -> !fir.ref<i32>
! FIRDialect:             fir.store %[[VAL_62]] to %[[VAL_66]] : !fir.ref<i32>
! FIRDialect:             oss.terminator
! FIRDialect:           }
! FIRDialect:           %[[VAL_67:[-0-9A-Za-z._]+]] = oss.copy base(%[[VAL_0]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>) function(@compute.copy4) -> i32
! FIRDialect:           %[[VAL_68:[-0-9A-Za-z._]+]] = oss.copy base(%[[VAL_0]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>) function(@compute.deinit6) -> i32
! FIRDialect:           %[[VAL_69:[-0-9A-Za-z._]+]] = oss.copy base(%[[VAL_1]] : !fir.ref<!fir.box<!fir.ptr<!fir.array<?xi32>>>>) function(@compute.copy5) -> i32
! FIRDialect:           %[[VAL_70:[-0-9A-Za-z._]+]] = oss.copy base(%[[VAL_1]] : !fir.ref<!fir.box<!fir.ptr<!fir.array<?xi32>>>>) function(@compute.deinit7) -> i32
! FIRDialect:           %[[VAL_71:[-0-9A-Za-z._]+]] = fir.undefined !fir.oss<!fir.box<!fir.heap<!fir.array<?xi32>>>>
! FIRDialect:           %[[VAL_72:[-0-9A-Za-z._]+]] = fir.undefined !fir.oss<!fir.box<!fir.ptr<!fir.array<?xi32>>>>
! FIRDialect:           %[[VAL_73:[-0-9A-Za-z._]+]] = fir.undefined !fir.oss<!fir.box<!fir.array<?xi32>>>
! FIRDialect:           oss.task firstprivate(%[[VAL_0]], %[[VAL_1]], %[[VAL_2]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>, !fir.ref<!fir.box<!fir.ptr<!fir.array<?xi32>>>>, !fir.box<!fir.array<?xi32>>) firstprivate_type(%[[VAL_71]], %[[VAL_72]], %[[VAL_73]] : !fir.oss<!fir.box<!fir.heap<!fir.array<?xi32>>>>, !fir.oss<!fir.box<!fir.ptr<!fir.array<?xi32>>>>, !fir.oss<!fir.box<!fir.array<?xi32>>>) copy(%[[VAL_67]], %[[VAL_69]] : i32, i32) deinit(%[[VAL_68]], %[[VAL_70]] : i32, i32) {
! FIRDialect:             %[[VAL_74:[-0-9A-Za-z._]+]] = arith.constant 7 : i32
! FIRDialect:             %[[VAL_75:[-0-9A-Za-z._]+]] = fir.load %[[VAL_0]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>
! FIRDialect:             %[[VAL_76:[-0-9A-Za-z._]+]] = arith.constant 0 : index
! FIRDialect:             %[[VAL_77:[-0-9A-Za-z._]+]]:3 = fir.box_dims %[[VAL_75]], %[[VAL_76]] : (!fir.box<!fir.heap<!fir.array<?xi32>>>, index) -> (index, index, index)
! FIRDialect:             %[[VAL_78:[-0-9A-Za-z._]+]] = fir.box_addr %[[VAL_75]] : (!fir.box<!fir.heap<!fir.array<?xi32>>>) -> !fir.heap<!fir.array<?xi32>>
! FIRDialect:             %[[VAL_79:[-0-9A-Za-z._]+]] = arith.constant 7 : i64
! FIRDialect:             %[[VAL_80:[-0-9A-Za-z._]+]] = fir.convert %[[VAL_77]]#0 : (index) -> i64
! FIRDialect:             %[[VAL_81:[-0-9A-Za-z._]+]] = arith.subi %[[VAL_79]], %[[VAL_80]] : i64
! FIRDialect:             %[[VAL_82:[-0-9A-Za-z._]+]] = fir.coordinate_of %[[VAL_78]], %[[VAL_81]] : (!fir.heap<!fir.array<?xi32>>, i64) -> !fir.ref<i32>
! FIRDialect:             fir.store %[[VAL_74]] to %[[VAL_82]] : !fir.ref<i32>
! FIRDialect:             %[[VAL_83:[-0-9A-Za-z._]+]] = arith.constant 7 : i32
! FIRDialect:             %[[VAL_84:[-0-9A-Za-z._]+]] = fir.load %[[VAL_1]] : !fir.ref<!fir.box<!fir.ptr<!fir.array<?xi32>>>>
! FIRDialect:             %[[VAL_85:[-0-9A-Za-z._]+]] = arith.constant 0 : index
! FIRDialect:             %[[VAL_86:[-0-9A-Za-z._]+]]:3 = fir.box_dims %[[VAL_84]], %[[VAL_85]] : (!fir.box<!fir.ptr<!fir.array<?xi32>>>, index) -> (index, index, index)
! FIRDialect:             %[[VAL_87:[-0-9A-Za-z._]+]] = arith.constant 7 : i64
! FIRDialect:             %[[VAL_88:[-0-9A-Za-z._]+]] = fir.convert %[[VAL_86]]#0 : (index) -> i64
! FIRDialect:             %[[VAL_89:[-0-9A-Za-z._]+]] = arith.subi %[[VAL_87]], %[[VAL_88]] : i64
! FIRDialect:             %[[VAL_90:[-0-9A-Za-z._]+]] = fir.coordinate_of %[[VAL_84]], %[[VAL_89]] : (!fir.box<!fir.ptr<!fir.array<?xi32>>>, i64) -> !fir.ref<i32>
! FIRDialect:             fir.store %[[VAL_83]] to %[[VAL_90]] : !fir.ref<i32>
! FIRDialect:             %[[VAL_91:[-0-9A-Za-z._]+]] = arith.constant 7 : i32
! FIRDialect:             %[[VAL_92:[-0-9A-Za-z._]+]] = arith.constant 7 : i64
! FIRDialect:             %[[VAL_93:[-0-9A-Za-z._]+]] = arith.constant 1 : i64
! FIRDialect:             %[[VAL_94:[-0-9A-Za-z._]+]] = arith.subi %[[VAL_92]], %[[VAL_93]] : i64
! FIRDialect:             %[[VAL_95:[-0-9A-Za-z._]+]] = fir.coordinate_of %[[VAL_2]], %[[VAL_94]] : (!fir.box<!fir.array<?xi32>>, i64) -> !fir.ref<i32>
! FIRDialect:             fir.store %[[VAL_91]] to %[[VAL_95]] : !fir.ref<i32>
! FIRDialect:             oss.terminator
! FIRDialect:           }
! FIRDialect:           %[[VAL_96:[-0-9A-Za-z._]+]] = fir.undefined !fir.oss<!fir.box<!fir.heap<!fir.array<?xi32>>>>
! FIRDialect:           %[[VAL_97:[-0-9A-Za-z._]+]] = fir.undefined !fir.oss<!fir.box<!fir.ptr<!fir.array<?xi32>>>>
! FIRDialect:           oss.task shared(%[[VAL_3]], %[[VAL_8]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>, !fir.ref<!fir.box<!fir.ptr<!fir.array<?xi32>>>>) shared_type(%[[VAL_96]], %[[VAL_97]] : !fir.oss<!fir.box<!fir.heap<!fir.array<?xi32>>>>, !fir.oss<!fir.box<!fir.ptr<!fir.array<?xi32>>>>) {
! FIRDialect:             %[[VAL_98:[-0-9A-Za-z._]+]] = arith.constant 7 : i32
! FIRDialect:             %[[VAL_99:[-0-9A-Za-z._]+]] = fir.load %[[VAL_3]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>
! FIRDialect:             %[[VAL_100:[-0-9A-Za-z._]+]] = arith.constant 0 : index
! FIRDialect:             %[[VAL_101:[-0-9A-Za-z._]+]]:3 = fir.box_dims %[[VAL_99]], %[[VAL_100]] : (!fir.box<!fir.heap<!fir.array<?xi32>>>, index) -> (index, index, index)
! FIRDialect:             %[[VAL_102:[-0-9A-Za-z._]+]] = fir.box_addr %[[VAL_99]] : (!fir.box<!fir.heap<!fir.array<?xi32>>>) -> !fir.heap<!fir.array<?xi32>>
! FIRDialect:             %[[VAL_103:[-0-9A-Za-z._]+]] = arith.constant 7 : i64
! FIRDialect:             %[[VAL_104:[-0-9A-Za-z._]+]] = fir.convert %[[VAL_101]]#0 : (index) -> i64
! FIRDialect:             %[[VAL_105:[-0-9A-Za-z._]+]] = arith.subi %[[VAL_103]], %[[VAL_104]] : i64
! FIRDialect:             %[[VAL_106:[-0-9A-Za-z._]+]] = fir.coordinate_of %[[VAL_102]], %[[VAL_105]] : (!fir.heap<!fir.array<?xi32>>, i64) -> !fir.ref<i32>
! FIRDialect:             fir.store %[[VAL_98]] to %[[VAL_106]] : !fir.ref<i32>
! FIRDialect:             %[[VAL_107:[-0-9A-Za-z._]+]] = arith.constant 7 : i32
! FIRDialect:             %[[VAL_108:[-0-9A-Za-z._]+]] = fir.load %[[VAL_8]] : !fir.ref<!fir.box<!fir.ptr<!fir.array<?xi32>>>>
! FIRDialect:             %[[VAL_109:[-0-9A-Za-z._]+]] = arith.constant 0 : index
! FIRDialect:             %[[VAL_110:[-0-9A-Za-z._]+]]:3 = fir.box_dims %[[VAL_108]], %[[VAL_109]] : (!fir.box<!fir.ptr<!fir.array<?xi32>>>, index) -> (index, index, index)
! FIRDialect:             %[[VAL_111:[-0-9A-Za-z._]+]] = arith.constant 7 : i64
! FIRDialect:             %[[VAL_112:[-0-9A-Za-z._]+]] = fir.convert %[[VAL_110]]#0 : (index) -> i64
! FIRDialect:             %[[VAL_113:[-0-9A-Za-z._]+]] = arith.subi %[[VAL_111]], %[[VAL_112]] : i64
! FIRDialect:             %[[VAL_114:[-0-9A-Za-z._]+]] = fir.coordinate_of %[[VAL_108]], %[[VAL_113]] : (!fir.box<!fir.ptr<!fir.array<?xi32>>>, i64) -> !fir.ref<i32>
! FIRDialect:             fir.store %[[VAL_107]] to %[[VAL_114]] : !fir.ref<i32>
! FIRDialect:             oss.terminator
! FIRDialect:           }
! FIRDialect:           %[[VAL_115:[-0-9A-Za-z._]+]] = oss.copy base(%[[VAL_3]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>) function(@compute.copy6) -> i32
! FIRDialect:           %[[VAL_116:[-0-9A-Za-z._]+]] = oss.copy base(%[[VAL_3]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>) function(@compute.deinit8) -> i32
! FIRDialect:           %[[VAL_117:[-0-9A-Za-z._]+]] = oss.copy base(%[[VAL_8]] : !fir.ref<!fir.box<!fir.ptr<!fir.array<?xi32>>>>) function(@compute.init2) -> i32
! FIRDialect:           %[[VAL_118:[-0-9A-Za-z._]+]] = oss.copy base(%[[VAL_8]] : !fir.ref<!fir.box<!fir.ptr<!fir.array<?xi32>>>>) function(@compute.deinit9) -> i32
! FIRDialect:           %[[VAL_119:[-0-9A-Za-z._]+]] = fir.undefined !fir.oss<!fir.box<!fir.ptr<!fir.array<?xi32>>>>
! FIRDialect:           %[[VAL_120:[-0-9A-Za-z._]+]] = fir.undefined !fir.oss<!fir.box<!fir.heap<!fir.array<?xi32>>>>
! FIRDialect:           oss.task private(%[[VAL_8]] : !fir.ref<!fir.box<!fir.ptr<!fir.array<?xi32>>>>) private_type(%[[VAL_119]] : !fir.oss<!fir.box<!fir.ptr<!fir.array<?xi32>>>>) firstprivate(%[[VAL_3]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>) firstprivate_type(%[[VAL_120]] : !fir.oss<!fir.box<!fir.heap<!fir.array<?xi32>>>>) copy(%[[VAL_115]] : i32) init(%[[VAL_117]] : i32) deinit(%[[VAL_116]], %[[VAL_118]] : i32, i32) {
! FIRDialect:             %[[VAL_121:[-0-9A-Za-z._]+]] = arith.constant 7 : i32
! FIRDialect:             %[[VAL_122:[-0-9A-Za-z._]+]] = fir.load %[[VAL_3]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>
! FIRDialect:             %[[VAL_123:[-0-9A-Za-z._]+]] = arith.constant 0 : index
! FIRDialect:             %[[VAL_124:[-0-9A-Za-z._]+]]:3 = fir.box_dims %[[VAL_122]], %[[VAL_123]] : (!fir.box<!fir.heap<!fir.array<?xi32>>>, index) -> (index, index, index)
! FIRDialect:             %[[VAL_125:[-0-9A-Za-z._]+]] = fir.box_addr %[[VAL_122]] : (!fir.box<!fir.heap<!fir.array<?xi32>>>) -> !fir.heap<!fir.array<?xi32>>
! FIRDialect:             %[[VAL_126:[-0-9A-Za-z._]+]] = arith.constant 7 : i64
! FIRDialect:             %[[VAL_127:[-0-9A-Za-z._]+]] = fir.convert %[[VAL_124]]#0 : (index) -> i64
! FIRDialect:             %[[VAL_128:[-0-9A-Za-z._]+]] = arith.subi %[[VAL_126]], %[[VAL_127]] : i64
! FIRDialect:             %[[VAL_129:[-0-9A-Za-z._]+]] = fir.coordinate_of %[[VAL_125]], %[[VAL_128]] : (!fir.heap<!fir.array<?xi32>>, i64) -> !fir.ref<i32>
! FIRDialect:             fir.store %[[VAL_121]] to %[[VAL_129]] : !fir.ref<i32>
! FIRDialect:             %[[VAL_130:[-0-9A-Za-z._]+]] = arith.constant 7 : i32
! FIRDialect:             %[[VAL_131:[-0-9A-Za-z._]+]] = fir.load %[[VAL_8]] : !fir.ref<!fir.box<!fir.ptr<!fir.array<?xi32>>>>
! FIRDialect:             %[[VAL_132:[-0-9A-Za-z._]+]] = arith.constant 0 : index
! FIRDialect:             %[[VAL_133:[-0-9A-Za-z._]+]]:3 = fir.box_dims %[[VAL_131]], %[[VAL_132]] : (!fir.box<!fir.ptr<!fir.array<?xi32>>>, index) -> (index, index, index)
! FIRDialect:             %[[VAL_134:[-0-9A-Za-z._]+]] = arith.constant 7 : i64
! FIRDialect:             %[[VAL_135:[-0-9A-Za-z._]+]] = fir.convert %[[VAL_133]]#0 : (index) -> i64
! FIRDialect:             %[[VAL_136:[-0-9A-Za-z._]+]] = arith.subi %[[VAL_134]], %[[VAL_135]] : i64
! FIRDialect:             %[[VAL_137:[-0-9A-Za-z._]+]] = fir.coordinate_of %[[VAL_131]], %[[VAL_136]] : (!fir.box<!fir.ptr<!fir.array<?xi32>>>, i64) -> !fir.ref<i32>
! FIRDialect:             fir.store %[[VAL_130]] to %[[VAL_137]] : !fir.ref<i32>
! FIRDialect:             oss.terminator
! FIRDialect:           }
! FIRDialect:           %[[VAL_138:[-0-9A-Za-z._]+]] = oss.copy base(%[[VAL_3]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>) function(@compute.copy7) -> i32
! FIRDialect:           %[[VAL_139:[-0-9A-Za-z._]+]] = oss.copy base(%[[VAL_3]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>) function(@compute.deinit10) -> i32
! FIRDialect:           %[[VAL_140:[-0-9A-Za-z._]+]] = oss.copy base(%[[VAL_8]] : !fir.ref<!fir.box<!fir.ptr<!fir.array<?xi32>>>>) function(@compute.copy8) -> i32
! FIRDialect:           %[[VAL_141:[-0-9A-Za-z._]+]] = oss.copy base(%[[VAL_8]] : !fir.ref<!fir.box<!fir.ptr<!fir.array<?xi32>>>>) function(@compute.deinit11) -> i32
! FIRDialect:           %[[VAL_142:[-0-9A-Za-z._]+]] = fir.undefined !fir.oss<!fir.box<!fir.heap<!fir.array<?xi32>>>>
! FIRDialect:           %[[VAL_143:[-0-9A-Za-z._]+]] = fir.undefined !fir.oss<!fir.box<!fir.ptr<!fir.array<?xi32>>>>
! FIRDialect:           oss.task firstprivate(%[[VAL_3]], %[[VAL_8]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>, !fir.ref<!fir.box<!fir.ptr<!fir.array<?xi32>>>>) firstprivate_type(%[[VAL_142]], %[[VAL_143]] : !fir.oss<!fir.box<!fir.heap<!fir.array<?xi32>>>>, !fir.oss<!fir.box<!fir.ptr<!fir.array<?xi32>>>>) copy(%[[VAL_138]], %[[VAL_140]] : i32, i32) deinit(%[[VAL_139]], %[[VAL_141]] : i32, i32) {
! FIRDialect:             %[[VAL_144:[-0-9A-Za-z._]+]] = arith.constant 7 : i32
! FIRDialect:             %[[VAL_145:[-0-9A-Za-z._]+]] = fir.load %[[VAL_3]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>
! FIRDialect:             %[[VAL_146:[-0-9A-Za-z._]+]] = arith.constant 0 : index
! FIRDialect:             %[[VAL_147:[-0-9A-Za-z._]+]]:3 = fir.box_dims %[[VAL_145]], %[[VAL_146]] : (!fir.box<!fir.heap<!fir.array<?xi32>>>, index) -> (index, index, index)
! FIRDialect:             %[[VAL_148:[-0-9A-Za-z._]+]] = fir.box_addr %[[VAL_145]] : (!fir.box<!fir.heap<!fir.array<?xi32>>>) -> !fir.heap<!fir.array<?xi32>>
! FIRDialect:             %[[VAL_149:[-0-9A-Za-z._]+]] = arith.constant 7 : i64
! FIRDialect:             %[[VAL_150:[-0-9A-Za-z._]+]] = fir.convert %[[VAL_147]]#0 : (index) -> i64
! FIRDialect:             %[[VAL_151:[-0-9A-Za-z._]+]] = arith.subi %[[VAL_149]], %[[VAL_150]] : i64
! FIRDialect:             %[[VAL_152:[-0-9A-Za-z._]+]] = fir.coordinate_of %[[VAL_148]], %[[VAL_151]] : (!fir.heap<!fir.array<?xi32>>, i64) -> !fir.ref<i32>
! FIRDialect:             fir.store %[[VAL_144]] to %[[VAL_152]] : !fir.ref<i32>
! FIRDialect:             %[[VAL_153:[-0-9A-Za-z._]+]] = arith.constant 7 : i32
! FIRDialect:             %[[VAL_154:[-0-9A-Za-z._]+]] = fir.load %[[VAL_8]] : !fir.ref<!fir.box<!fir.ptr<!fir.array<?xi32>>>>
! FIRDialect:             %[[VAL_155:[-0-9A-Za-z._]+]] = arith.constant 0 : index
! FIRDialect:             %[[VAL_156:[-0-9A-Za-z._]+]]:3 = fir.box_dims %[[VAL_154]], %[[VAL_155]] : (!fir.box<!fir.ptr<!fir.array<?xi32>>>, index) -> (index, index, index)
! FIRDialect:             %[[VAL_157:[-0-9A-Za-z._]+]] = arith.constant 7 : i64
! FIRDialect:             %[[VAL_158:[-0-9A-Za-z._]+]] = fir.convert %[[VAL_156]]#0 : (index) -> i64
! FIRDialect:             %[[VAL_159:[-0-9A-Za-z._]+]] = arith.subi %[[VAL_157]], %[[VAL_158]] : i64
! FIRDialect:             %[[VAL_160:[-0-9A-Za-z._]+]] = fir.coordinate_of %[[VAL_154]], %[[VAL_159]] : (!fir.box<!fir.ptr<!fir.array<?xi32>>>, i64) -> !fir.ref<i32>
! FIRDialect:             fir.store %[[VAL_153]] to %[[VAL_160]] : !fir.ref<i32>
! FIRDialect:             oss.terminator
! FIRDialect:           }
! FIRDialect:           %[[VAL_161:[-0-9A-Za-z._]+]] = fir.load %[[VAL_3]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>
! FIRDialect:           %[[VAL_162:[-0-9A-Za-z._]+]] = fir.box_addr %[[VAL_161]] : (!fir.box<!fir.heap<!fir.array<?xi32>>>) -> !fir.heap<!fir.array<?xi32>>
! FIRDialect:           %[[VAL_163:[-0-9A-Za-z._]+]] = fir.convert %[[VAL_162]] : (!fir.heap<!fir.array<?xi32>>) -> i64
! FIRDialect:           %[[VAL_164:[-0-9A-Za-z._]+]] = arith.constant 0 : i64
! FIRDialect:           %[[VAL_165:[-0-9A-Za-z._]+]] = arith.cmpi ne, %[[VAL_163]], %[[VAL_164]] : i64
! FIRDialect:           fir.if %[[VAL_165]] {
! FIRDialect:             %[[VAL_166:[-0-9A-Za-z._]+]] = fir.load %[[VAL_3]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>
! FIRDialect:             %[[VAL_167:[-0-9A-Za-z._]+]] = fir.box_addr %[[VAL_166]] : (!fir.box<!fir.heap<!fir.array<?xi32>>>) -> !fir.heap<!fir.array<?xi32>>
! FIRDialect:             fir.freemem %[[VAL_167]] : !fir.heap<!fir.array<?xi32>>
! FIRDialect:             %[[VAL_168:[-0-9A-Za-z._]+]] = fir.zero_bits !fir.heap<!fir.array<?xi32>>
! FIRDialect:             %[[VAL_169:[-0-9A-Za-z._]+]] = arith.constant 0 : index
! FIRDialect:             %[[VAL_170:[-0-9A-Za-z._]+]] = fir.shape %[[VAL_169]] : (index) -> !fir.shape<1>
! FIRDialect:             %[[VAL_171:[-0-9A-Za-z._]+]] = fir.embox %[[VAL_168]](%[[VAL_170]]) : (!fir.heap<!fir.array<?xi32>>, !fir.shape<1>) -> !fir.box<!fir.heap<!fir.array<?xi32>>>
! FIRDialect:             fir.store %[[VAL_171]] to %[[VAL_3]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>
! FIRDialect:           }
! FIRDialect:           return
! FIRDialect:         }

! FIRDialect-LABEL:   fir.global internal @_QFEarray : !fir.array<10xi32> {
! FIRDialect:           %[[VAL_0:[-0-9A-Za-z._]+]] = fir.zero_bits !fir.array<10xi32>
! FIRDialect:           fir.has_value %[[VAL_0]] : !fir.array<10xi32>
! FIRDialect:         }

! FIRDialect-LABEL:   fir.global internal @_QFEglob_alloc : !fir.box<!fir.heap<!fir.array<?xi32>>> {
! FIRDialect:           %[[VAL_0:[-0-9A-Za-z._]+]] = fir.zero_bits !fir.heap<!fir.array<?xi32>>
! FIRDialect:           %[[VAL_1:[-0-9A-Za-z._]+]] = arith.constant 0 : index
! FIRDialect:           %[[VAL_2:[-0-9A-Za-z._]+]] = fir.shape %[[VAL_1]] : (index) -> !fir.shape<1>
! FIRDialect:           %[[VAL_3:[-0-9A-Za-z._]+]] = fir.embox %[[VAL_0]](%[[VAL_2]]) : (!fir.heap<!fir.array<?xi32>>, !fir.shape<1>) -> !fir.box<!fir.heap<!fir.array<?xi32>>>
! FIRDialect:           fir.has_value %[[VAL_3]] : !fir.box<!fir.heap<!fir.array<?xi32>>>
! FIRDialect:         }

! FIRDialect-LABEL:   fir.global internal @_QFEglob_ptr : !fir.box<!fir.ptr<!fir.array<?xi32>>> {
! FIRDialect:           %[[VAL_0:[-0-9A-Za-z._]+]] = fir.zero_bits !fir.ptr<!fir.array<?xi32>>
! FIRDialect:           %[[VAL_1:[-0-9A-Za-z._]+]] = arith.constant 0 : index
! FIRDialect:           %[[VAL_2:[-0-9A-Za-z._]+]] = fir.shape %[[VAL_1]] : (index) -> !fir.shape<1>
! FIRDialect:           %[[VAL_3:[-0-9A-Za-z._]+]] = fir.embox %[[VAL_0]](%[[VAL_2]]) : (!fir.ptr<!fir.array<?xi32>>, !fir.shape<1>) -> !fir.box<!fir.ptr<!fir.array<?xi32>>>
! FIRDialect:           fir.has_value %[[VAL_3]] : !fir.box<!fir.ptr<!fir.array<?xi32>>>
! FIRDialect:         }

! FIRDialect-LABEL:   func.func @compute.copy0(
! FIRDialect-SAME:                             %[[VAL_0:[-0-9A-Za-z._]+]]: !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>,
! FIRDialect-SAME:                             %[[VAL_1:[-0-9A-Za-z._]+]]: !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>,
! FIRDialect-SAME:                             %[[VAL_2:[-0-9A-Za-z._]+]]: i64) -> i32 {
! FIRDialect:           %[[VAL_3:[-0-9A-Za-z._]+]] = fir.zero_bits !fir.heap<!fir.array<?xi32>>
! FIRDialect:           %[[VAL_4:[-0-9A-Za-z._]+]] = arith.constant 0 : index
! FIRDialect:           %[[VAL_5:[-0-9A-Za-z._]+]] = fir.shape %[[VAL_4]] : (index) -> !fir.shape<1>
! FIRDialect:           %[[VAL_6:[-0-9A-Za-z._]+]] = fir.embox %[[VAL_3]](%[[VAL_5]]) : (!fir.heap<!fir.array<?xi32>>, !fir.shape<1>) -> !fir.box<!fir.heap<!fir.array<?xi32>>>
! FIRDialect:           fir.store %[[VAL_6]] to %[[VAL_1]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>
! FIRDialect:           %[[VAL_7:[-0-9A-Za-z._]+]] = fir.load %[[VAL_0]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>
! FIRDialect:           %[[VAL_8:[-0-9A-Za-z._]+]] = fir.box_addr %[[VAL_7]] : (!fir.box<!fir.heap<!fir.array<?xi32>>>) -> !fir.heap<!fir.array<?xi32>>
! FIRDialect:           %[[VAL_9:[-0-9A-Za-z._]+]] = fir.convert %[[VAL_8]] : (!fir.heap<!fir.array<?xi32>>) -> i64
! FIRDialect:           %[[VAL_10:[-0-9A-Za-z._]+]] = arith.constant 0 : i64
! FIRDialect:           %[[VAL_11:[-0-9A-Za-z._]+]] = arith.cmpi ne, %[[VAL_9]], %[[VAL_10]] : i64
! FIRDialect:           fir.if %[[VAL_11]] {
! FIRDialect:             %[[VAL_12:[-0-9A-Za-z._]+]] = fir.load %[[VAL_0]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>
! FIRDialect:             %[[VAL_13:[-0-9A-Za-z._]+]] = arith.constant 0 : index
! FIRDialect:             %[[VAL_14:[-0-9A-Za-z._]+]]:3 = fir.box_dims %[[VAL_12]], %[[VAL_13]] : (!fir.box<!fir.heap<!fir.array<?xi32>>>, index) -> (index, index, index)
! FIRDialect:             %[[VAL_15:[-0-9A-Za-z._]+]] = fir.box_addr %[[VAL_12]] : (!fir.box<!fir.heap<!fir.array<?xi32>>>) -> !fir.heap<!fir.array<?xi32>>
! FIRDialect:             %[[VAL_16:[-0-9A-Za-z._]+]] = arith.constant 1 : index
! FIRDialect:             %[[VAL_17:[-0-9A-Za-z._]+]] = fir.shape_shift %[[VAL_14]]#0, %[[VAL_14]]#1 : (index, index) -> !fir.shapeshift<1>
! FIRDialect:             %[[VAL_18:[-0-9A-Za-z._]+]] = fir.array_load %[[VAL_15]](%[[VAL_17]]) : (!fir.heap<!fir.array<?xi32>>, !fir.shapeshift<1>) -> !fir.array<?xi32>
! FIRDialect:             %[[VAL_19:[-0-9A-Za-z._]+]] = fir.load %[[VAL_1]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>
! FIRDialect:             %[[VAL_20:[-0-9A-Za-z._]+]] = fir.box_addr %[[VAL_19]] : (!fir.box<!fir.heap<!fir.array<?xi32>>>) -> !fir.heap<!fir.array<?xi32>>
! FIRDialect:             %[[VAL_21:[-0-9A-Za-z._]+]] = fir.convert %[[VAL_20]] : (!fir.heap<!fir.array<?xi32>>) -> i64
! FIRDialect:             %[[VAL_22:[-0-9A-Za-z._]+]] = arith.constant 0 : i64
! FIRDialect:             %[[VAL_23:[-0-9A-Za-z._]+]] = arith.cmpi ne, %[[VAL_21]], %[[VAL_22]] : i64
! FIRDialect:             %[[VAL_24:[-0-9A-Za-z._]+]]:2 = fir.if %[[VAL_23]] -> (i1, !fir.heap<!fir.array<?xi32>>) {
! FIRDialect:               %[[VAL_25:[-0-9A-Za-z._]+]] = arith.constant false
! FIRDialect:               %[[VAL_26:[-0-9A-Za-z._]+]] = arith.constant 0 : index
! FIRDialect:               %[[VAL_27:[-0-9A-Za-z._]+]]:3 = fir.box_dims %[[VAL_19]], %[[VAL_26]] : (!fir.box<!fir.heap<!fir.array<?xi32>>>, index) -> (index, index, index)
! FIRDialect:               %[[VAL_28:[-0-9A-Za-z._]+]] = arith.cmpi ne, %[[VAL_27]]#1, %[[VAL_14]]#1 : index
! FIRDialect:               %[[VAL_29:[-0-9A-Za-z._]+]] = arith.select %[[VAL_28]], %[[VAL_28]], %[[VAL_25]] : i1
! FIRDialect:               %[[VAL_30:[-0-9A-Za-z._]+]] = fir.if %[[VAL_29]] -> (!fir.heap<!fir.array<?xi32>>) {
! FIRDialect:                 %[[VAL_31:[-0-9A-Za-z._]+]] = fir.allocmem !fir.array<?xi32>, %[[VAL_14]]#1 {uniq_name = ".auto.alloc"}
! FIRDialect:                 fir.result %[[VAL_31]] : !fir.heap<!fir.array<?xi32>>
! FIRDialect:               } else {
! FIRDialect:                 fir.result %[[VAL_20]] : !fir.heap<!fir.array<?xi32>>
! FIRDialect:               }
! FIRDialect:               fir.result %[[VAL_29]], %[[VAL_30]] : i1, !fir.heap<!fir.array<?xi32>>
! FIRDialect:             } else {
! FIRDialect:               %[[VAL_32:[-0-9A-Za-z._]+]] = arith.constant true
! FIRDialect:               %[[VAL_33:[-0-9A-Za-z._]+]] = fir.allocmem !fir.array<?xi32>, %[[VAL_14]]#1 {uniq_name = ".auto.alloc"}
! FIRDialect:               fir.result %[[VAL_32]], %[[VAL_33]] : i1, !fir.heap<!fir.array<?xi32>>
! FIRDialect:             }
! FIRDialect:             fir.if %[[VAL_34:[-0-9A-Za-z._]+]]#0 {
! FIRDialect:               %[[VAL_35:[-0-9A-Za-z._]+]] = fir.load %[[VAL_1]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>
! FIRDialect:               fir.if %[[VAL_23]] {
! FIRDialect:                 fir.freemem %[[VAL_20]] : !fir.heap<!fir.array<?xi32>>
! FIRDialect:               }
! FIRDialect:               %[[VAL_36:[-0-9A-Za-z._]+]] = fir.shape_shift %[[VAL_14]]#0, %[[VAL_14]]#1 : (index, index) -> !fir.shapeshift<1>
! FIRDialect:               %[[VAL_37:[-0-9A-Za-z._]+]] = fir.embox %[[VAL_34]]#1(%[[VAL_36]]) : (!fir.heap<!fir.array<?xi32>>, !fir.shapeshift<1>) -> !fir.box<!fir.heap<!fir.array<?xi32>>>
! FIRDialect:               fir.store %[[VAL_37]] to %[[VAL_1]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>
! FIRDialect:             }
! FIRDialect:           }
! FIRDialect:           %[[VAL_38:[-0-9A-Za-z._]+]] = arith.constant 1 : i32
! FIRDialect:           return %[[VAL_38]] : i32
! FIRDialect:         }

! FIRDialect-LABEL:   func.func @compute.deinit0(
! FIRDialect-SAME:                               %[[VAL_0:[-0-9A-Za-z._]+]]: !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>,
! FIRDialect-SAME:                               %[[VAL_1:[-0-9A-Za-z._]+]]: i64) -> i32 {
! FIRDialect:           %[[VAL_2:[-0-9A-Za-z._]+]] = fir.load %[[VAL_0]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>
! FIRDialect:           %[[VAL_3:[-0-9A-Za-z._]+]] = fir.box_addr %[[VAL_2]] : (!fir.box<!fir.heap<!fir.array<?xi32>>>) -> !fir.heap<!fir.array<?xi32>>
! FIRDialect:           %[[VAL_4:[-0-9A-Za-z._]+]] = fir.convert %[[VAL_3]] : (!fir.heap<!fir.array<?xi32>>) -> i64
! FIRDialect:           %[[VAL_5:[-0-9A-Za-z._]+]] = arith.constant 0 : i64
! FIRDialect:           %[[VAL_6:[-0-9A-Za-z._]+]] = arith.cmpi ne, %[[VAL_4]], %[[VAL_5]] : i64
! FIRDialect:           fir.if %[[VAL_6]] {
! FIRDialect:             %[[VAL_7:[-0-9A-Za-z._]+]] = arith.constant false
! FIRDialect:             %[[VAL_8:[-0-9A-Za-z._]+]] = fir.absent !fir.box<none>
! FIRDialect:             %[[VAL_9:[-0-9A-Za-z._]+]] = fir.zero_bits !fir.ref<none>
! FIRDialect:             %[[VAL_10:[-0-9A-Za-z._]+]] = arith.constant 0 : i32
! FIRDialect:             %[[VAL_11:[-0-9A-Za-z._]+]] = fir.load %[[VAL_0]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>
! FIRDialect:             %[[VAL_12:[-0-9A-Za-z._]+]] = fir.box_addr %[[VAL_11]] : (!fir.box<!fir.heap<!fir.array<?xi32>>>) -> !fir.heap<!fir.array<?xi32>>
! FIRDialect:             fir.freemem %[[VAL_12]] : !fir.heap<!fir.array<?xi32>>
! FIRDialect:             %[[VAL_13:[-0-9A-Za-z._]+]] = fir.zero_bits !fir.heap<!fir.array<?xi32>>
! FIRDialect:             %[[VAL_14:[-0-9A-Za-z._]+]] = arith.constant 0 : index
! FIRDialect:             %[[VAL_15:[-0-9A-Za-z._]+]] = fir.shape %[[VAL_14]] : (index) -> !fir.shape<1>
! FIRDialect:             %[[VAL_16:[-0-9A-Za-z._]+]] = fir.embox %[[VAL_13]](%[[VAL_15]]) : (!fir.heap<!fir.array<?xi32>>, !fir.shape<1>) -> !fir.box<!fir.heap<!fir.array<?xi32>>>
! FIRDialect:             fir.store %[[VAL_16]] to %[[VAL_0]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>
! FIRDialect:           }
! FIRDialect:           %[[VAL_17:[-0-9A-Za-z._]+]] = arith.constant 1 : i32
! FIRDialect:           return %[[VAL_17]] : i32
! FIRDialect:         }

! FIRDialect-LABEL:   func.func @compute.init0(
! FIRDialect-SAME:                             %[[VAL_0:[-0-9A-Za-z._]+]]: !fir.ref<!fir.box<!fir.ptr<!fir.array<?xi32>>>>,
! FIRDialect-SAME:                             %[[VAL_1:[-0-9A-Za-z._]+]]: i64) -> i32 {
! FIRDialect:           %[[VAL_2:[-0-9A-Za-z._]+]] = fir.zero_bits !fir.ptr<!fir.array<?xi32>>
! FIRDialect:           %[[VAL_3:[-0-9A-Za-z._]+]] = arith.constant 0 : index
! FIRDialect:           %[[VAL_4:[-0-9A-Za-z._]+]] = fir.shape %[[VAL_3]] : (index) -> !fir.shape<1>
! FIRDialect:           %[[VAL_5:[-0-9A-Za-z._]+]] = fir.embox %[[VAL_2]](%[[VAL_4]]) : (!fir.ptr<!fir.array<?xi32>>, !fir.shape<1>) -> !fir.box<!fir.ptr<!fir.array<?xi32>>>
! FIRDialect:           fir.store %[[VAL_5]] to %[[VAL_0]] : !fir.ref<!fir.box<!fir.ptr<!fir.array<?xi32>>>>
! FIRDialect:           %[[VAL_6:[-0-9A-Za-z._]+]] = arith.constant 1 : i32
! FIRDialect:           return %[[VAL_6]] : i32
! FIRDialect:         }

! FIRDialect-LABEL:   func.func @compute.deinit1(
! FIRDialect-SAME:                               %[[VAL_0:[-0-9A-Za-z._]+]]: !fir.ref<!fir.box<!fir.ptr<!fir.array<?xi32>>>>,
! FIRDialect-SAME:                               %[[VAL_1:[-0-9A-Za-z._]+]]: i64) -> i32 {
! FIRDialect:           %[[VAL_2:[-0-9A-Za-z._]+]] = fir.zero_bits !fir.ptr<!fir.array<?xi32>>
! FIRDialect:           %[[VAL_3:[-0-9A-Za-z._]+]] = arith.constant 0 : index
! FIRDialect:           %[[VAL_4:[-0-9A-Za-z._]+]] = fir.shape %[[VAL_3]] : (index) -> !fir.shape<1>
! FIRDialect:           %[[VAL_5:[-0-9A-Za-z._]+]] = fir.embox %[[VAL_2]](%[[VAL_4]]) : (!fir.ptr<!fir.array<?xi32>>, !fir.shape<1>) -> !fir.box<!fir.ptr<!fir.array<?xi32>>>
! FIRDialect:           fir.store %[[VAL_5]] to %[[VAL_0]] : !fir.ref<!fir.box<!fir.ptr<!fir.array<?xi32>>>>
! FIRDialect:           %[[VAL_6:[-0-9A-Za-z._]+]] = arith.constant 1 : i32
! FIRDialect:           return %[[VAL_6]] : i32
! FIRDialect:         }

! FIRDialect-LABEL:   func.func @compute.copy1(
! FIRDialect-SAME:                             %[[VAL_0:[-0-9A-Za-z._]+]]: !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>,
! FIRDialect-SAME:                             %[[VAL_1:[-0-9A-Za-z._]+]]: !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>,
! FIRDialect-SAME:                             %[[VAL_2:[-0-9A-Za-z._]+]]: i64) -> i32 {
! FIRDialect:           %[[VAL_3:[-0-9A-Za-z._]+]] = fir.zero_bits !fir.heap<!fir.array<?xi32>>
! FIRDialect:           %[[VAL_4:[-0-9A-Za-z._]+]] = arith.constant 0 : index
! FIRDialect:           %[[VAL_5:[-0-9A-Za-z._]+]] = fir.shape %[[VAL_4]] : (index) -> !fir.shape<1>
! FIRDialect:           %[[VAL_6:[-0-9A-Za-z._]+]] = fir.embox %[[VAL_3]](%[[VAL_5]]) : (!fir.heap<!fir.array<?xi32>>, !fir.shape<1>) -> !fir.box<!fir.heap<!fir.array<?xi32>>>
! FIRDialect:           fir.store %[[VAL_6]] to %[[VAL_1]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>
! FIRDialect:           %[[VAL_7:[-0-9A-Za-z._]+]] = fir.load %[[VAL_0]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>
! FIRDialect:           %[[VAL_8:[-0-9A-Za-z._]+]] = fir.box_addr %[[VAL_7]] : (!fir.box<!fir.heap<!fir.array<?xi32>>>) -> !fir.heap<!fir.array<?xi32>>
! FIRDialect:           %[[VAL_9:[-0-9A-Za-z._]+]] = fir.convert %[[VAL_8]] : (!fir.heap<!fir.array<?xi32>>) -> i64
! FIRDialect:           %[[VAL_10:[-0-9A-Za-z._]+]] = arith.constant 0 : i64
! FIRDialect:           %[[VAL_11:[-0-9A-Za-z._]+]] = arith.cmpi ne, %[[VAL_9]], %[[VAL_10]] : i64
! FIRDialect:           fir.if %[[VAL_11]] {
! FIRDialect:             %[[VAL_12:[-0-9A-Za-z._]+]] = fir.load %[[VAL_0]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>
! FIRDialect:             %[[VAL_13:[-0-9A-Za-z._]+]] = arith.constant 0 : index
! FIRDialect:             %[[VAL_14:[-0-9A-Za-z._]+]]:3 = fir.box_dims %[[VAL_12]], %[[VAL_13]] : (!fir.box<!fir.heap<!fir.array<?xi32>>>, index) -> (index, index, index)
! FIRDialect:             %[[VAL_15:[-0-9A-Za-z._]+]] = fir.box_addr %[[VAL_12]] : (!fir.box<!fir.heap<!fir.array<?xi32>>>) -> !fir.heap<!fir.array<?xi32>>
! FIRDialect:             %[[VAL_16:[-0-9A-Za-z._]+]] = arith.constant 1 : index
! FIRDialect:             %[[VAL_17:[-0-9A-Za-z._]+]] = fir.shape_shift %[[VAL_14]]#0, %[[VAL_14]]#1 : (index, index) -> !fir.shapeshift<1>
! FIRDialect:             %[[VAL_18:[-0-9A-Za-z._]+]] = fir.array_load %[[VAL_15]](%[[VAL_17]]) : (!fir.heap<!fir.array<?xi32>>, !fir.shapeshift<1>) -> !fir.array<?xi32>
! FIRDialect:             %[[VAL_19:[-0-9A-Za-z._]+]] = fir.load %[[VAL_1]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>
! FIRDialect:             %[[VAL_20:[-0-9A-Za-z._]+]] = fir.box_addr %[[VAL_19]] : (!fir.box<!fir.heap<!fir.array<?xi32>>>) -> !fir.heap<!fir.array<?xi32>>
! FIRDialect:             %[[VAL_21:[-0-9A-Za-z._]+]] = fir.convert %[[VAL_20]] : (!fir.heap<!fir.array<?xi32>>) -> i64
! FIRDialect:             %[[VAL_22:[-0-9A-Za-z._]+]] = arith.constant 0 : i64
! FIRDialect:             %[[VAL_23:[-0-9A-Za-z._]+]] = arith.cmpi ne, %[[VAL_21]], %[[VAL_22]] : i64
! FIRDialect:             %[[VAL_24:[-0-9A-Za-z._]+]]:2 = fir.if %[[VAL_23]] -> (i1, !fir.heap<!fir.array<?xi32>>) {
! FIRDialect:               %[[VAL_25:[-0-9A-Za-z._]+]] = arith.constant false
! FIRDialect:               %[[VAL_26:[-0-9A-Za-z._]+]] = arith.constant 0 : index
! FIRDialect:               %[[VAL_27:[-0-9A-Za-z._]+]]:3 = fir.box_dims %[[VAL_19]], %[[VAL_26]] : (!fir.box<!fir.heap<!fir.array<?xi32>>>, index) -> (index, index, index)
! FIRDialect:               %[[VAL_28:[-0-9A-Za-z._]+]] = arith.cmpi ne, %[[VAL_27]]#1, %[[VAL_14]]#1 : index
! FIRDialect:               %[[VAL_29:[-0-9A-Za-z._]+]] = arith.select %[[VAL_28]], %[[VAL_28]], %[[VAL_25]] : i1
! FIRDialect:               %[[VAL_30:[-0-9A-Za-z._]+]] = fir.if %[[VAL_29]] -> (!fir.heap<!fir.array<?xi32>>) {
! FIRDialect:                 %[[VAL_31:[-0-9A-Za-z._]+]] = fir.allocmem !fir.array<?xi32>, %[[VAL_14]]#1 {uniq_name = ".auto.alloc"}
! FIRDialect:                 %[[VAL_32:[-0-9A-Za-z._]+]] = fir.shape %[[VAL_14]]#1 : (index) -> !fir.shape<1>
! FIRDialect:                 %[[VAL_33:[-0-9A-Za-z._]+]] = fir.array_load %[[VAL_31]](%[[VAL_32]]) : (!fir.heap<!fir.array<?xi32>>, !fir.shape<1>) -> !fir.array<?xi32>
! FIRDialect:                 %[[VAL_34:[-0-9A-Za-z._]+]] = arith.constant 1 : index
! FIRDialect:                 %[[VAL_35:[-0-9A-Za-z._]+]] = arith.constant 0 : index
! FIRDialect:                 %[[VAL_36:[-0-9A-Za-z._]+]] = arith.subi %[[VAL_14]]#1, %[[VAL_34]] : index
! FIRDialect:                 %[[VAL_37:[-0-9A-Za-z._]+]] = fir.do_loop %[[VAL_38:[-0-9A-Za-z._]+]] = %[[VAL_35]] to %[[VAL_36]] step %[[VAL_34]] unordered iter_args(%[[VAL_39:[-0-9A-Za-z._]+]] = %[[VAL_33]]) -> (!fir.array<?xi32>) {
! FIRDialect:                   %[[VAL_40:[-0-9A-Za-z._]+]] = fir.array_fetch %[[VAL_18]], %[[VAL_38]] : (!fir.array<?xi32>, index) -> i32
! FIRDialect:                   %[[VAL_41:[-0-9A-Za-z._]+]] = fir.array_update %[[VAL_39]], %[[VAL_40]], %[[VAL_38]] : (!fir.array<?xi32>, i32, index) -> !fir.array<?xi32>
! FIRDialect:                   %[[VAL_42:[-0-9A-Za-z._]+]] = fir.undefined index
! FIRDialect:                   fir.result %[[VAL_41]] : !fir.array<?xi32>
! FIRDialect:                 }
! FIRDialect:                 %[[VAL_43:[-0-9A-Za-z._]+]] = fir.undefined index
! FIRDialect:                 fir.array_merge_store %[[VAL_33]], %[[VAL_37]] to %[[VAL_31]] : !fir.array<?xi32>, !fir.array<?xi32>, !fir.heap<!fir.array<?xi32>>
! FIRDialect:                 fir.result %[[VAL_31]] : !fir.heap<!fir.array<?xi32>>
! FIRDialect:               } else {
! FIRDialect:                 %[[VAL_44:[-0-9A-Za-z._]+]] = fir.shape %[[VAL_14]]#1 : (index) -> !fir.shape<1>
! FIRDialect:                 %[[VAL_45:[-0-9A-Za-z._]+]] = fir.array_load %[[VAL_20]](%[[VAL_44]]) : (!fir.heap<!fir.array<?xi32>>, !fir.shape<1>) -> !fir.array<?xi32>
! FIRDialect:                 %[[VAL_46:[-0-9A-Za-z._]+]] = arith.constant 1 : index
! FIRDialect:                 %[[VAL_47:[-0-9A-Za-z._]+]] = arith.constant 0 : index
! FIRDialect:                 %[[VAL_48:[-0-9A-Za-z._]+]] = arith.subi %[[VAL_14]]#1, %[[VAL_46]] : index
! FIRDialect:                 %[[VAL_49:[-0-9A-Za-z._]+]] = fir.do_loop %[[VAL_50:[-0-9A-Za-z._]+]] = %[[VAL_47]] to %[[VAL_48]] step %[[VAL_46]] unordered iter_args(%[[VAL_51:[-0-9A-Za-z._]+]] = %[[VAL_45]]) -> (!fir.array<?xi32>) {
! FIRDialect:                   %[[VAL_52:[-0-9A-Za-z._]+]] = fir.array_fetch %[[VAL_18]], %[[VAL_50]] : (!fir.array<?xi32>, index) -> i32
! FIRDialect:                   %[[VAL_53:[-0-9A-Za-z._]+]] = fir.array_update %[[VAL_51]], %[[VAL_52]], %[[VAL_50]] : (!fir.array<?xi32>, i32, index) -> !fir.array<?xi32>
! FIRDialect:                   %[[VAL_54:[-0-9A-Za-z._]+]] = fir.undefined index
! FIRDialect:                   fir.result %[[VAL_53]] : !fir.array<?xi32>
! FIRDialect:                 }
! FIRDialect:                 %[[VAL_55:[-0-9A-Za-z._]+]] = fir.undefined index
! FIRDialect:                 fir.array_merge_store %[[VAL_45]], %[[VAL_49]] to %[[VAL_20]] : !fir.array<?xi32>, !fir.array<?xi32>, !fir.heap<!fir.array<?xi32>>
! FIRDialect:                 fir.result %[[VAL_20]] : !fir.heap<!fir.array<?xi32>>
! FIRDialect:               }
! FIRDialect:               fir.result %[[VAL_29]], %[[VAL_30]] : i1, !fir.heap<!fir.array<?xi32>>
! FIRDialect:             } else {
! FIRDialect:               %[[VAL_56:[-0-9A-Za-z._]+]] = arith.constant true
! FIRDialect:               %[[VAL_57:[-0-9A-Za-z._]+]] = fir.allocmem !fir.array<?xi32>, %[[VAL_14]]#1 {uniq_name = ".auto.alloc"}
! FIRDialect:               %[[VAL_58:[-0-9A-Za-z._]+]] = fir.shape %[[VAL_14]]#1 : (index) -> !fir.shape<1>
! FIRDialect:               %[[VAL_59:[-0-9A-Za-z._]+]] = fir.array_load %[[VAL_57]](%[[VAL_58]]) : (!fir.heap<!fir.array<?xi32>>, !fir.shape<1>) -> !fir.array<?xi32>
! FIRDialect:               %[[VAL_60:[-0-9A-Za-z._]+]] = arith.constant 1 : index
! FIRDialect:               %[[VAL_61:[-0-9A-Za-z._]+]] = arith.constant 0 : index
! FIRDialect:               %[[VAL_62:[-0-9A-Za-z._]+]] = arith.subi %[[VAL_14]]#1, %[[VAL_60]] : index
! FIRDialect:               %[[VAL_63:[-0-9A-Za-z._]+]] = fir.do_loop %[[VAL_64:[-0-9A-Za-z._]+]] = %[[VAL_61]] to %[[VAL_62]] step %[[VAL_60]] unordered iter_args(%[[VAL_65:[-0-9A-Za-z._]+]] = %[[VAL_59]]) -> (!fir.array<?xi32>) {
! FIRDialect:                 %[[VAL_66:[-0-9A-Za-z._]+]] = fir.array_fetch %[[VAL_18]], %[[VAL_64]] : (!fir.array<?xi32>, index) -> i32
! FIRDialect:                 %[[VAL_67:[-0-9A-Za-z._]+]] = fir.array_update %[[VAL_65]], %[[VAL_66]], %[[VAL_64]] : (!fir.array<?xi32>, i32, index) -> !fir.array<?xi32>
! FIRDialect:                 %[[VAL_68:[-0-9A-Za-z._]+]] = fir.undefined index
! FIRDialect:                 fir.result %[[VAL_67]] : !fir.array<?xi32>
! FIRDialect:               }
! FIRDialect:               %[[VAL_69:[-0-9A-Za-z._]+]] = fir.undefined index
! FIRDialect:               fir.array_merge_store %[[VAL_59]], %[[VAL_63]] to %[[VAL_57]] : !fir.array<?xi32>, !fir.array<?xi32>, !fir.heap<!fir.array<?xi32>>
! FIRDialect:               fir.result %[[VAL_56]], %[[VAL_57]] : i1, !fir.heap<!fir.array<?xi32>>
! FIRDialect:             }
! FIRDialect:             fir.if %[[VAL_70:[-0-9A-Za-z._]+]]#0 {
! FIRDialect:               %[[VAL_71:[-0-9A-Za-z._]+]] = fir.load %[[VAL_1]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>
! FIRDialect:               fir.if %[[VAL_23]] {
! FIRDialect:                 fir.freemem %[[VAL_20]] : !fir.heap<!fir.array<?xi32>>
! FIRDialect:               }
! FIRDialect:               %[[VAL_72:[-0-9A-Za-z._]+]] = fir.shape_shift %[[VAL_14]]#0, %[[VAL_14]]#1 : (index, index) -> !fir.shapeshift<1>
! FIRDialect:               %[[VAL_73:[-0-9A-Za-z._]+]] = fir.embox %[[VAL_70]]#1(%[[VAL_72]]) : (!fir.heap<!fir.array<?xi32>>, !fir.shapeshift<1>) -> !fir.box<!fir.heap<!fir.array<?xi32>>>
! FIRDialect:               fir.store %[[VAL_73]] to %[[VAL_1]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>
! FIRDialect:             }
! FIRDialect:           }
! FIRDialect:           %[[VAL_74:[-0-9A-Za-z._]+]] = arith.constant 1 : i32
! FIRDialect:           return %[[VAL_74]] : i32
! FIRDialect:         }

! FIRDialect-LABEL:   func.func @compute.deinit2(
! FIRDialect-SAME:                               %[[VAL_0:[-0-9A-Za-z._]+]]: !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>,
! FIRDialect-SAME:                               %[[VAL_1:[-0-9A-Za-z._]+]]: i64) -> i32 {
! FIRDialect:           %[[VAL_2:[-0-9A-Za-z._]+]] = fir.load %[[VAL_0]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>
! FIRDialect:           %[[VAL_3:[-0-9A-Za-z._]+]] = fir.box_addr %[[VAL_2]] : (!fir.box<!fir.heap<!fir.array<?xi32>>>) -> !fir.heap<!fir.array<?xi32>>
! FIRDialect:           %[[VAL_4:[-0-9A-Za-z._]+]] = fir.convert %[[VAL_3]] : (!fir.heap<!fir.array<?xi32>>) -> i64
! FIRDialect:           %[[VAL_5:[-0-9A-Za-z._]+]] = arith.constant 0 : i64
! FIRDialect:           %[[VAL_6:[-0-9A-Za-z._]+]] = arith.cmpi ne, %[[VAL_4]], %[[VAL_5]] : i64
! FIRDialect:           fir.if %[[VAL_6]] {
! FIRDialect:             %[[VAL_7:[-0-9A-Za-z._]+]] = arith.constant false
! FIRDialect:             %[[VAL_8:[-0-9A-Za-z._]+]] = fir.absent !fir.box<none>
! FIRDialect:             %[[VAL_9:[-0-9A-Za-z._]+]] = fir.zero_bits !fir.ref<none>
! FIRDialect:             %[[VAL_10:[-0-9A-Za-z._]+]] = arith.constant 0 : i32
! FIRDialect:             %[[VAL_11:[-0-9A-Za-z._]+]] = fir.load %[[VAL_0]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>
! FIRDialect:             %[[VAL_12:[-0-9A-Za-z._]+]] = fir.box_addr %[[VAL_11]] : (!fir.box<!fir.heap<!fir.array<?xi32>>>) -> !fir.heap<!fir.array<?xi32>>
! FIRDialect:             fir.freemem %[[VAL_12]] : !fir.heap<!fir.array<?xi32>>
! FIRDialect:             %[[VAL_13:[-0-9A-Za-z._]+]] = fir.zero_bits !fir.heap<!fir.array<?xi32>>
! FIRDialect:             %[[VAL_14:[-0-9A-Za-z._]+]] = arith.constant 0 : index
! FIRDialect:             %[[VAL_15:[-0-9A-Za-z._]+]] = fir.shape %[[VAL_14]] : (index) -> !fir.shape<1>
! FIRDialect:             %[[VAL_16:[-0-9A-Za-z._]+]] = fir.embox %[[VAL_13]](%[[VAL_15]]) : (!fir.heap<!fir.array<?xi32>>, !fir.shape<1>) -> !fir.box<!fir.heap<!fir.array<?xi32>>>
! FIRDialect:             fir.store %[[VAL_16]] to %[[VAL_0]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>
! FIRDialect:           }
! FIRDialect:           %[[VAL_17:[-0-9A-Za-z._]+]] = arith.constant 1 : i32
! FIRDialect:           return %[[VAL_17]] : i32
! FIRDialect:         }

! FIRDialect-LABEL:   func.func @compute.copy2(
! FIRDialect-SAME:                             %[[VAL_0:[-0-9A-Za-z._]+]]: !fir.ref<!fir.box<!fir.ptr<!fir.array<?xi32>>>>,
! FIRDialect-SAME:                             %[[VAL_1:[-0-9A-Za-z._]+]]: !fir.ref<!fir.box<!fir.ptr<!fir.array<?xi32>>>>,
! FIRDialect-SAME:                             %[[VAL_2:[-0-9A-Za-z._]+]]: i64) -> i32 {
! FIRDialect:           %[[VAL_3:[-0-9A-Za-z._]+]] = fir.load %[[VAL_0]] : !fir.ref<!fir.box<!fir.ptr<!fir.array<?xi32>>>>
! FIRDialect:           %[[VAL_4:[-0-9A-Za-z._]+]] = arith.constant 0 : index
! FIRDialect:           %[[VAL_5:[-0-9A-Za-z._]+]]:3 = fir.box_dims %[[VAL_3]], %[[VAL_4]] : (!fir.box<!fir.ptr<!fir.array<?xi32>>>, index) -> (index, index, index)
! FIRDialect:           %[[VAL_6:[-0-9A-Za-z._]+]] = fir.shift %[[VAL_5]]#0 : (index) -> !fir.shift<1>
! FIRDialect:           %[[VAL_7:[-0-9A-Za-z._]+]] = fir.rebox %[[VAL_3]](%[[VAL_6]]) : (!fir.box<!fir.ptr<!fir.array<?xi32>>>, !fir.shift<1>) -> !fir.box<!fir.ptr<!fir.array<?xi32>>>
! FIRDialect:           fir.store %[[VAL_7]] to %[[VAL_1]] : !fir.ref<!fir.box<!fir.ptr<!fir.array<?xi32>>>>
! FIRDialect:           %[[VAL_8:[-0-9A-Za-z._]+]] = arith.constant 1 : i32
! FIRDialect:           return %[[VAL_8]] : i32
! FIRDialect:         }

! FIRDialect-LABEL:   func.func @compute.deinit3(
! FIRDialect-SAME:                               %[[VAL_0:[-0-9A-Za-z._]+]]: !fir.ref<!fir.box<!fir.ptr<!fir.array<?xi32>>>>,
! FIRDialect-SAME:                               %[[VAL_1:[-0-9A-Za-z._]+]]: i64) -> i32 {
! FIRDialect:           %[[VAL_2:[-0-9A-Za-z._]+]] = fir.zero_bits !fir.ptr<!fir.array<?xi32>>
! FIRDialect:           %[[VAL_3:[-0-9A-Za-z._]+]] = arith.constant 0 : index
! FIRDialect:           %[[VAL_4:[-0-9A-Za-z._]+]] = fir.shape %[[VAL_3]] : (index) -> !fir.shape<1>
! FIRDialect:           %[[VAL_5:[-0-9A-Za-z._]+]] = fir.embox %[[VAL_2]](%[[VAL_4]]) : (!fir.ptr<!fir.array<?xi32>>, !fir.shape<1>) -> !fir.box<!fir.ptr<!fir.array<?xi32>>>
! FIRDialect:           fir.store %[[VAL_5]] to %[[VAL_0]] : !fir.ref<!fir.box<!fir.ptr<!fir.array<?xi32>>>>
! FIRDialect:           %[[VAL_6:[-0-9A-Za-z._]+]] = arith.constant 1 : i32
! FIRDialect:           return %[[VAL_6]] : i32
! FIRDialect:         }

! FIRDialect-LABEL:   func.func @compute.copy3(
! FIRDialect-SAME:                             %[[VAL_0:[-0-9A-Za-z._]+]]: !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>,
! FIRDialect-SAME:                             %[[VAL_1:[-0-9A-Za-z._]+]]: !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>,
! FIRDialect-SAME:                             %[[VAL_2:[-0-9A-Za-z._]+]]: i64) -> i32 {
! FIRDialect:           %[[VAL_3:[-0-9A-Za-z._]+]] = fir.zero_bits !fir.heap<!fir.array<?xi32>>
! FIRDialect:           %[[VAL_4:[-0-9A-Za-z._]+]] = arith.constant 0 : index
! FIRDialect:           %[[VAL_5:[-0-9A-Za-z._]+]] = fir.shape %[[VAL_4]] : (index) -> !fir.shape<1>
! FIRDialect:           %[[VAL_6:[-0-9A-Za-z._]+]] = fir.embox %[[VAL_3]](%[[VAL_5]]) : (!fir.heap<!fir.array<?xi32>>, !fir.shape<1>) -> !fir.box<!fir.heap<!fir.array<?xi32>>>
! FIRDialect:           fir.store %[[VAL_6]] to %[[VAL_1]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>
! FIRDialect:           %[[VAL_7:[-0-9A-Za-z._]+]] = fir.load %[[VAL_0]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>
! FIRDialect:           %[[VAL_8:[-0-9A-Za-z._]+]] = fir.box_addr %[[VAL_7]] : (!fir.box<!fir.heap<!fir.array<?xi32>>>) -> !fir.heap<!fir.array<?xi32>>
! FIRDialect:           %[[VAL_9:[-0-9A-Za-z._]+]] = fir.convert %[[VAL_8]] : (!fir.heap<!fir.array<?xi32>>) -> i64
! FIRDialect:           %[[VAL_10:[-0-9A-Za-z._]+]] = arith.constant 0 : i64
! FIRDialect:           %[[VAL_11:[-0-9A-Za-z._]+]] = arith.cmpi ne, %[[VAL_9]], %[[VAL_10]] : i64
! FIRDialect:           fir.if %[[VAL_11]] {
! FIRDialect:             %[[VAL_12:[-0-9A-Za-z._]+]] = fir.load %[[VAL_0]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>
! FIRDialect:             %[[VAL_13:[-0-9A-Za-z._]+]] = arith.constant 0 : index
! FIRDialect:             %[[VAL_14:[-0-9A-Za-z._]+]]:3 = fir.box_dims %[[VAL_12]], %[[VAL_13]] : (!fir.box<!fir.heap<!fir.array<?xi32>>>, index) -> (index, index, index)
! FIRDialect:             %[[VAL_15:[-0-9A-Za-z._]+]] = fir.box_addr %[[VAL_12]] : (!fir.box<!fir.heap<!fir.array<?xi32>>>) -> !fir.heap<!fir.array<?xi32>>
! FIRDialect:             %[[VAL_16:[-0-9A-Za-z._]+]] = arith.constant 1 : index
! FIRDialect:             %[[VAL_17:[-0-9A-Za-z._]+]] = fir.shape_shift %[[VAL_14]]#0, %[[VAL_14]]#1 : (index, index) -> !fir.shapeshift<1>
! FIRDialect:             %[[VAL_18:[-0-9A-Za-z._]+]] = fir.array_load %[[VAL_15]](%[[VAL_17]]) : (!fir.heap<!fir.array<?xi32>>, !fir.shapeshift<1>) -> !fir.array<?xi32>
! FIRDialect:             %[[VAL_19:[-0-9A-Za-z._]+]] = fir.load %[[VAL_1]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>
! FIRDialect:             %[[VAL_20:[-0-9A-Za-z._]+]] = fir.box_addr %[[VAL_19]] : (!fir.box<!fir.heap<!fir.array<?xi32>>>) -> !fir.heap<!fir.array<?xi32>>
! FIRDialect:             %[[VAL_21:[-0-9A-Za-z._]+]] = fir.convert %[[VAL_20]] : (!fir.heap<!fir.array<?xi32>>) -> i64
! FIRDialect:             %[[VAL_22:[-0-9A-Za-z._]+]] = arith.constant 0 : i64
! FIRDialect:             %[[VAL_23:[-0-9A-Za-z._]+]] = arith.cmpi ne, %[[VAL_21]], %[[VAL_22]] : i64
! FIRDialect:             %[[VAL_24:[-0-9A-Za-z._]+]]:2 = fir.if %[[VAL_23]] -> (i1, !fir.heap<!fir.array<?xi32>>) {
! FIRDialect:               %[[VAL_25:[-0-9A-Za-z._]+]] = arith.constant false
! FIRDialect:               %[[VAL_26:[-0-9A-Za-z._]+]] = arith.constant 0 : index
! FIRDialect:               %[[VAL_27:[-0-9A-Za-z._]+]]:3 = fir.box_dims %[[VAL_19]], %[[VAL_26]] : (!fir.box<!fir.heap<!fir.array<?xi32>>>, index) -> (index, index, index)
! FIRDialect:               %[[VAL_28:[-0-9A-Za-z._]+]] = arith.cmpi ne, %[[VAL_27]]#1, %[[VAL_14]]#1 : index
! FIRDialect:               %[[VAL_29:[-0-9A-Za-z._]+]] = arith.select %[[VAL_28]], %[[VAL_28]], %[[VAL_25]] : i1
! FIRDialect:               %[[VAL_30:[-0-9A-Za-z._]+]] = fir.if %[[VAL_29]] -> (!fir.heap<!fir.array<?xi32>>) {
! FIRDialect:                 %[[VAL_31:[-0-9A-Za-z._]+]] = fir.allocmem !fir.array<?xi32>, %[[VAL_14]]#1 {uniq_name = ".auto.alloc"}
! FIRDialect:                 fir.result %[[VAL_31]] : !fir.heap<!fir.array<?xi32>>
! FIRDialect:               } else {
! FIRDialect:                 fir.result %[[VAL_20]] : !fir.heap<!fir.array<?xi32>>
! FIRDialect:               }
! FIRDialect:               fir.result %[[VAL_29]], %[[VAL_30]] : i1, !fir.heap<!fir.array<?xi32>>
! FIRDialect:             } else {
! FIRDialect:               %[[VAL_32:[-0-9A-Za-z._]+]] = arith.constant true
! FIRDialect:               %[[VAL_33:[-0-9A-Za-z._]+]] = fir.allocmem !fir.array<?xi32>, %[[VAL_14]]#1 {uniq_name = ".auto.alloc"}
! FIRDialect:               fir.result %[[VAL_32]], %[[VAL_33]] : i1, !fir.heap<!fir.array<?xi32>>
! FIRDialect:             }
! FIRDialect:             fir.if %[[VAL_34:[-0-9A-Za-z._]+]]#0 {
! FIRDialect:               %[[VAL_35:[-0-9A-Za-z._]+]] = fir.load %[[VAL_1]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>
! FIRDialect:               fir.if %[[VAL_23]] {
! FIRDialect:                 fir.freemem %[[VAL_20]] : !fir.heap<!fir.array<?xi32>>
! FIRDialect:               }
! FIRDialect:               %[[VAL_36:[-0-9A-Za-z._]+]] = fir.shape_shift %[[VAL_14]]#0, %[[VAL_14]]#1 : (index, index) -> !fir.shapeshift<1>
! FIRDialect:               %[[VAL_37:[-0-9A-Za-z._]+]] = fir.embox %[[VAL_34]]#1(%[[VAL_36]]) : (!fir.heap<!fir.array<?xi32>>, !fir.shapeshift<1>) -> !fir.box<!fir.heap<!fir.array<?xi32>>>
! FIRDialect:               fir.store %[[VAL_37]] to %[[VAL_1]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>
! FIRDialect:             }
! FIRDialect:           }
! FIRDialect:           %[[VAL_38:[-0-9A-Za-z._]+]] = arith.constant 1 : i32
! FIRDialect:           return %[[VAL_38]] : i32
! FIRDialect:         }

! FIRDialect-LABEL:   func.func @compute.deinit4(
! FIRDialect-SAME:                               %[[VAL_0:[-0-9A-Za-z._]+]]: !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>,
! FIRDialect-SAME:                               %[[VAL_1:[-0-9A-Za-z._]+]]: i64) -> i32 {
! FIRDialect:           %[[VAL_2:[-0-9A-Za-z._]+]] = fir.load %[[VAL_0]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>
! FIRDialect:           %[[VAL_3:[-0-9A-Za-z._]+]] = fir.box_addr %[[VAL_2]] : (!fir.box<!fir.heap<!fir.array<?xi32>>>) -> !fir.heap<!fir.array<?xi32>>
! FIRDialect:           %[[VAL_4:[-0-9A-Za-z._]+]] = fir.convert %[[VAL_3]] : (!fir.heap<!fir.array<?xi32>>) -> i64
! FIRDialect:           %[[VAL_5:[-0-9A-Za-z._]+]] = arith.constant 0 : i64
! FIRDialect:           %[[VAL_6:[-0-9A-Za-z._]+]] = arith.cmpi ne, %[[VAL_4]], %[[VAL_5]] : i64
! FIRDialect:           fir.if %[[VAL_6]] {
! FIRDialect:             %[[VAL_7:[-0-9A-Za-z._]+]] = arith.constant false
! FIRDialect:             %[[VAL_8:[-0-9A-Za-z._]+]] = fir.absent !fir.box<none>
! FIRDialect:             %[[VAL_9:[-0-9A-Za-z._]+]] = fir.zero_bits !fir.ref<none>
! FIRDialect:             %[[VAL_10:[-0-9A-Za-z._]+]] = arith.constant 0 : i32
! FIRDialect:             %[[VAL_11:[-0-9A-Za-z._]+]] = fir.load %[[VAL_0]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>
! FIRDialect:             %[[VAL_12:[-0-9A-Za-z._]+]] = fir.box_addr %[[VAL_11]] : (!fir.box<!fir.heap<!fir.array<?xi32>>>) -> !fir.heap<!fir.array<?xi32>>
! FIRDialect:             fir.freemem %[[VAL_12]] : !fir.heap<!fir.array<?xi32>>
! FIRDialect:             %[[VAL_13:[-0-9A-Za-z._]+]] = fir.zero_bits !fir.heap<!fir.array<?xi32>>
! FIRDialect:             %[[VAL_14:[-0-9A-Za-z._]+]] = arith.constant 0 : index
! FIRDialect:             %[[VAL_15:[-0-9A-Za-z._]+]] = fir.shape %[[VAL_14]] : (index) -> !fir.shape<1>
! FIRDialect:             %[[VAL_16:[-0-9A-Za-z._]+]] = fir.embox %[[VAL_13]](%[[VAL_15]]) : (!fir.heap<!fir.array<?xi32>>, !fir.shape<1>) -> !fir.box<!fir.heap<!fir.array<?xi32>>>
! FIRDialect:             fir.store %[[VAL_16]] to %[[VAL_0]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>
! FIRDialect:           }
! FIRDialect:           %[[VAL_17:[-0-9A-Za-z._]+]] = arith.constant 1 : i32
! FIRDialect:           return %[[VAL_17]] : i32
! FIRDialect:         }

! FIRDialect-LABEL:   func.func @compute.init1(
! FIRDialect-SAME:                             %[[VAL_0:[-0-9A-Za-z._]+]]: !fir.ref<!fir.box<!fir.ptr<!fir.array<?xi32>>>>,
! FIRDialect-SAME:                             %[[VAL_1:[-0-9A-Za-z._]+]]: i64) -> i32 {
! FIRDialect:           %[[VAL_2:[-0-9A-Za-z._]+]] = fir.zero_bits !fir.ptr<!fir.array<?xi32>>
! FIRDialect:           %[[VAL_3:[-0-9A-Za-z._]+]] = arith.constant 0 : index
! FIRDialect:           %[[VAL_4:[-0-9A-Za-z._]+]] = fir.shape %[[VAL_3]] : (index) -> !fir.shape<1>
! FIRDialect:           %[[VAL_5:[-0-9A-Za-z._]+]] = fir.embox %[[VAL_2]](%[[VAL_4]]) : (!fir.ptr<!fir.array<?xi32>>, !fir.shape<1>) -> !fir.box<!fir.ptr<!fir.array<?xi32>>>
! FIRDialect:           fir.store %[[VAL_5]] to %[[VAL_0]] : !fir.ref<!fir.box<!fir.ptr<!fir.array<?xi32>>>>
! FIRDialect:           %[[VAL_6:[-0-9A-Za-z._]+]] = arith.constant 1 : i32
! FIRDialect:           return %[[VAL_6]] : i32
! FIRDialect:         }

! FIRDialect-LABEL:   func.func @compute.deinit5(
! FIRDialect-SAME:                               %[[VAL_0:[-0-9A-Za-z._]+]]: !fir.ref<!fir.box<!fir.ptr<!fir.array<?xi32>>>>,
! FIRDialect-SAME:                               %[[VAL_1:[-0-9A-Za-z._]+]]: i64) -> i32 {
! FIRDialect:           %[[VAL_2:[-0-9A-Za-z._]+]] = fir.zero_bits !fir.ptr<!fir.array<?xi32>>
! FIRDialect:           %[[VAL_3:[-0-9A-Za-z._]+]] = arith.constant 0 : index
! FIRDialect:           %[[VAL_4:[-0-9A-Za-z._]+]] = fir.shape %[[VAL_3]] : (index) -> !fir.shape<1>
! FIRDialect:           %[[VAL_5:[-0-9A-Za-z._]+]] = fir.embox %[[VAL_2]](%[[VAL_4]]) : (!fir.ptr<!fir.array<?xi32>>, !fir.shape<1>) -> !fir.box<!fir.ptr<!fir.array<?xi32>>>
! FIRDialect:           fir.store %[[VAL_5]] to %[[VAL_0]] : !fir.ref<!fir.box<!fir.ptr<!fir.array<?xi32>>>>
! FIRDialect:           %[[VAL_6:[-0-9A-Za-z._]+]] = arith.constant 1 : i32
! FIRDialect:           return %[[VAL_6]] : i32
! FIRDialect:         }

! FIRDialect-LABEL:   func.func @compute.copy4(
! FIRDialect-SAME:                             %[[VAL_0:[-0-9A-Za-z._]+]]: !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>,
! FIRDialect-SAME:                             %[[VAL_1:[-0-9A-Za-z._]+]]: !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>,
! FIRDialect-SAME:                             %[[VAL_2:[-0-9A-Za-z._]+]]: i64) -> i32 {
! FIRDialect:           %[[VAL_3:[-0-9A-Za-z._]+]] = fir.zero_bits !fir.heap<!fir.array<?xi32>>
! FIRDialect:           %[[VAL_4:[-0-9A-Za-z._]+]] = arith.constant 0 : index
! FIRDialect:           %[[VAL_5:[-0-9A-Za-z._]+]] = fir.shape %[[VAL_4]] : (index) -> !fir.shape<1>
! FIRDialect:           %[[VAL_6:[-0-9A-Za-z._]+]] = fir.embox %[[VAL_3]](%[[VAL_5]]) : (!fir.heap<!fir.array<?xi32>>, !fir.shape<1>) -> !fir.box<!fir.heap<!fir.array<?xi32>>>
! FIRDialect:           fir.store %[[VAL_6]] to %[[VAL_1]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>
! FIRDialect:           %[[VAL_7:[-0-9A-Za-z._]+]] = fir.load %[[VAL_0]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>
! FIRDialect:           %[[VAL_8:[-0-9A-Za-z._]+]] = fir.box_addr %[[VAL_7]] : (!fir.box<!fir.heap<!fir.array<?xi32>>>) -> !fir.heap<!fir.array<?xi32>>
! FIRDialect:           %[[VAL_9:[-0-9A-Za-z._]+]] = fir.convert %[[VAL_8]] : (!fir.heap<!fir.array<?xi32>>) -> i64
! FIRDialect:           %[[VAL_10:[-0-9A-Za-z._]+]] = arith.constant 0 : i64
! FIRDialect:           %[[VAL_11:[-0-9A-Za-z._]+]] = arith.cmpi ne, %[[VAL_9]], %[[VAL_10]] : i64
! FIRDialect:           fir.if %[[VAL_11]] {
! FIRDialect:             %[[VAL_12:[-0-9A-Za-z._]+]] = fir.load %[[VAL_0]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>
! FIRDialect:             %[[VAL_13:[-0-9A-Za-z._]+]] = arith.constant 0 : index
! FIRDialect:             %[[VAL_14:[-0-9A-Za-z._]+]]:3 = fir.box_dims %[[VAL_12]], %[[VAL_13]] : (!fir.box<!fir.heap<!fir.array<?xi32>>>, index) -> (index, index, index)
! FIRDialect:             %[[VAL_15:[-0-9A-Za-z._]+]] = fir.box_addr %[[VAL_12]] : (!fir.box<!fir.heap<!fir.array<?xi32>>>) -> !fir.heap<!fir.array<?xi32>>
! FIRDialect:             %[[VAL_16:[-0-9A-Za-z._]+]] = arith.constant 1 : index
! FIRDialect:             %[[VAL_17:[-0-9A-Za-z._]+]] = fir.shape_shift %[[VAL_14]]#0, %[[VAL_14]]#1 : (index, index) -> !fir.shapeshift<1>
! FIRDialect:             %[[VAL_18:[-0-9A-Za-z._]+]] = fir.array_load %[[VAL_15]](%[[VAL_17]]) : (!fir.heap<!fir.array<?xi32>>, !fir.shapeshift<1>) -> !fir.array<?xi32>
! FIRDialect:             %[[VAL_19:[-0-9A-Za-z._]+]] = fir.load %[[VAL_1]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>
! FIRDialect:             %[[VAL_20:[-0-9A-Za-z._]+]] = fir.box_addr %[[VAL_19]] : (!fir.box<!fir.heap<!fir.array<?xi32>>>) -> !fir.heap<!fir.array<?xi32>>
! FIRDialect:             %[[VAL_21:[-0-9A-Za-z._]+]] = fir.convert %[[VAL_20]] : (!fir.heap<!fir.array<?xi32>>) -> i64
! FIRDialect:             %[[VAL_22:[-0-9A-Za-z._]+]] = arith.constant 0 : i64
! FIRDialect:             %[[VAL_23:[-0-9A-Za-z._]+]] = arith.cmpi ne, %[[VAL_21]], %[[VAL_22]] : i64
! FIRDialect:             %[[VAL_24:[-0-9A-Za-z._]+]]:2 = fir.if %[[VAL_23]] -> (i1, !fir.heap<!fir.array<?xi32>>) {
! FIRDialect:               %[[VAL_25:[-0-9A-Za-z._]+]] = arith.constant false
! FIRDialect:               %[[VAL_26:[-0-9A-Za-z._]+]] = arith.constant 0 : index
! FIRDialect:               %[[VAL_27:[-0-9A-Za-z._]+]]:3 = fir.box_dims %[[VAL_19]], %[[VAL_26]] : (!fir.box<!fir.heap<!fir.array<?xi32>>>, index) -> (index, index, index)
! FIRDialect:               %[[VAL_28:[-0-9A-Za-z._]+]] = arith.cmpi ne, %[[VAL_27]]#1, %[[VAL_14]]#1 : index
! FIRDialect:               %[[VAL_29:[-0-9A-Za-z._]+]] = arith.select %[[VAL_28]], %[[VAL_28]], %[[VAL_25]] : i1
! FIRDialect:               %[[VAL_30:[-0-9A-Za-z._]+]] = fir.if %[[VAL_29]] -> (!fir.heap<!fir.array<?xi32>>) {
! FIRDialect:                 %[[VAL_31:[-0-9A-Za-z._]+]] = fir.allocmem !fir.array<?xi32>, %[[VAL_14]]#1 {uniq_name = ".auto.alloc"}
! FIRDialect:                 %[[VAL_32:[-0-9A-Za-z._]+]] = fir.shape %[[VAL_14]]#1 : (index) -> !fir.shape<1>
! FIRDialect:                 %[[VAL_33:[-0-9A-Za-z._]+]] = fir.array_load %[[VAL_31]](%[[VAL_32]]) : (!fir.heap<!fir.array<?xi32>>, !fir.shape<1>) -> !fir.array<?xi32>
! FIRDialect:                 %[[VAL_34:[-0-9A-Za-z._]+]] = arith.constant 1 : index
! FIRDialect:                 %[[VAL_35:[-0-9A-Za-z._]+]] = arith.constant 0 : index
! FIRDialect:                 %[[VAL_36:[-0-9A-Za-z._]+]] = arith.subi %[[VAL_14]]#1, %[[VAL_34]] : index
! FIRDialect:                 %[[VAL_37:[-0-9A-Za-z._]+]] = fir.do_loop %[[VAL_38:[-0-9A-Za-z._]+]] = %[[VAL_35]] to %[[VAL_36]] step %[[VAL_34]] unordered iter_args(%[[VAL_39:[-0-9A-Za-z._]+]] = %[[VAL_33]]) -> (!fir.array<?xi32>) {
! FIRDialect:                   %[[VAL_40:[-0-9A-Za-z._]+]] = fir.array_fetch %[[VAL_18]], %[[VAL_38]] : (!fir.array<?xi32>, index) -> i32
! FIRDialect:                   %[[VAL_41:[-0-9A-Za-z._]+]] = fir.array_update %[[VAL_39]], %[[VAL_40]], %[[VAL_38]] : (!fir.array<?xi32>, i32, index) -> !fir.array<?xi32>
! FIRDialect:                   %[[VAL_42:[-0-9A-Za-z._]+]] = fir.undefined index
! FIRDialect:                   fir.result %[[VAL_41]] : !fir.array<?xi32>
! FIRDialect:                 }
! FIRDialect:                 %[[VAL_43:[-0-9A-Za-z._]+]] = fir.undefined index
! FIRDialect:                 fir.array_merge_store %[[VAL_33]], %[[VAL_37]] to %[[VAL_31]] : !fir.array<?xi32>, !fir.array<?xi32>, !fir.heap<!fir.array<?xi32>>
! FIRDialect:                 fir.result %[[VAL_31]] : !fir.heap<!fir.array<?xi32>>
! FIRDialect:               } else {
! FIRDialect:                 %[[VAL_44:[-0-9A-Za-z._]+]] = fir.shape %[[VAL_14]]#1 : (index) -> !fir.shape<1>
! FIRDialect:                 %[[VAL_45:[-0-9A-Za-z._]+]] = fir.array_load %[[VAL_20]](%[[VAL_44]]) : (!fir.heap<!fir.array<?xi32>>, !fir.shape<1>) -> !fir.array<?xi32>
! FIRDialect:                 %[[VAL_46:[-0-9A-Za-z._]+]] = arith.constant 1 : index
! FIRDialect:                 %[[VAL_47:[-0-9A-Za-z._]+]] = arith.constant 0 : index
! FIRDialect:                 %[[VAL_48:[-0-9A-Za-z._]+]] = arith.subi %[[VAL_14]]#1, %[[VAL_46]] : index
! FIRDialect:                 %[[VAL_49:[-0-9A-Za-z._]+]] = fir.do_loop %[[VAL_50:[-0-9A-Za-z._]+]] = %[[VAL_47]] to %[[VAL_48]] step %[[VAL_46]] unordered iter_args(%[[VAL_51:[-0-9A-Za-z._]+]] = %[[VAL_45]]) -> (!fir.array<?xi32>) {
! FIRDialect:                   %[[VAL_52:[-0-9A-Za-z._]+]] = fir.array_fetch %[[VAL_18]], %[[VAL_50]] : (!fir.array<?xi32>, index) -> i32
! FIRDialect:                   %[[VAL_53:[-0-9A-Za-z._]+]] = fir.array_update %[[VAL_51]], %[[VAL_52]], %[[VAL_50]] : (!fir.array<?xi32>, i32, index) -> !fir.array<?xi32>
! FIRDialect:                   %[[VAL_54:[-0-9A-Za-z._]+]] = fir.undefined index
! FIRDialect:                   fir.result %[[VAL_53]] : !fir.array<?xi32>
! FIRDialect:                 }
! FIRDialect:                 %[[VAL_55:[-0-9A-Za-z._]+]] = fir.undefined index
! FIRDialect:                 fir.array_merge_store %[[VAL_45]], %[[VAL_49]] to %[[VAL_20]] : !fir.array<?xi32>, !fir.array<?xi32>, !fir.heap<!fir.array<?xi32>>
! FIRDialect:                 fir.result %[[VAL_20]] : !fir.heap<!fir.array<?xi32>>
! FIRDialect:               }
! FIRDialect:               fir.result %[[VAL_29]], %[[VAL_30]] : i1, !fir.heap<!fir.array<?xi32>>
! FIRDialect:             } else {
! FIRDialect:               %[[VAL_56:[-0-9A-Za-z._]+]] = arith.constant true
! FIRDialect:               %[[VAL_57:[-0-9A-Za-z._]+]] = fir.allocmem !fir.array<?xi32>, %[[VAL_14]]#1 {uniq_name = ".auto.alloc"}
! FIRDialect:               %[[VAL_58:[-0-9A-Za-z._]+]] = fir.shape %[[VAL_14]]#1 : (index) -> !fir.shape<1>
! FIRDialect:               %[[VAL_59:[-0-9A-Za-z._]+]] = fir.array_load %[[VAL_57]](%[[VAL_58]]) : (!fir.heap<!fir.array<?xi32>>, !fir.shape<1>) -> !fir.array<?xi32>
! FIRDialect:               %[[VAL_60:[-0-9A-Za-z._]+]] = arith.constant 1 : index
! FIRDialect:               %[[VAL_61:[-0-9A-Za-z._]+]] = arith.constant 0 : index
! FIRDialect:               %[[VAL_62:[-0-9A-Za-z._]+]] = arith.subi %[[VAL_14]]#1, %[[VAL_60]] : index
! FIRDialect:               %[[VAL_63:[-0-9A-Za-z._]+]] = fir.do_loop %[[VAL_64:[-0-9A-Za-z._]+]] = %[[VAL_61]] to %[[VAL_62]] step %[[VAL_60]] unordered iter_args(%[[VAL_65:[-0-9A-Za-z._]+]] = %[[VAL_59]]) -> (!fir.array<?xi32>) {
! FIRDialect:                 %[[VAL_66:[-0-9A-Za-z._]+]] = fir.array_fetch %[[VAL_18]], %[[VAL_64]] : (!fir.array<?xi32>, index) -> i32
! FIRDialect:                 %[[VAL_67:[-0-9A-Za-z._]+]] = fir.array_update %[[VAL_65]], %[[VAL_66]], %[[VAL_64]] : (!fir.array<?xi32>, i32, index) -> !fir.array<?xi32>
! FIRDialect:                 %[[VAL_68:[-0-9A-Za-z._]+]] = fir.undefined index
! FIRDialect:                 fir.result %[[VAL_67]] : !fir.array<?xi32>
! FIRDialect:               }
! FIRDialect:               %[[VAL_69:[-0-9A-Za-z._]+]] = fir.undefined index
! FIRDialect:               fir.array_merge_store %[[VAL_59]], %[[VAL_63]] to %[[VAL_57]] : !fir.array<?xi32>, !fir.array<?xi32>, !fir.heap<!fir.array<?xi32>>
! FIRDialect:               fir.result %[[VAL_56]], %[[VAL_57]] : i1, !fir.heap<!fir.array<?xi32>>
! FIRDialect:             }
! FIRDialect:             fir.if %[[VAL_70:[-0-9A-Za-z._]+]]#0 {
! FIRDialect:               %[[VAL_71:[-0-9A-Za-z._]+]] = fir.load %[[VAL_1]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>
! FIRDialect:               fir.if %[[VAL_23]] {
! FIRDialect:                 fir.freemem %[[VAL_20]] : !fir.heap<!fir.array<?xi32>>
! FIRDialect:               }
! FIRDialect:               %[[VAL_72:[-0-9A-Za-z._]+]] = fir.shape_shift %[[VAL_14]]#0, %[[VAL_14]]#1 : (index, index) -> !fir.shapeshift<1>
! FIRDialect:               %[[VAL_73:[-0-9A-Za-z._]+]] = fir.embox %[[VAL_70]]#1(%[[VAL_72]]) : (!fir.heap<!fir.array<?xi32>>, !fir.shapeshift<1>) -> !fir.box<!fir.heap<!fir.array<?xi32>>>
! FIRDialect:               fir.store %[[VAL_73]] to %[[VAL_1]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>
! FIRDialect:             }
! FIRDialect:           }
! FIRDialect:           %[[VAL_74:[-0-9A-Za-z._]+]] = arith.constant 1 : i32
! FIRDialect:           return %[[VAL_74]] : i32
! FIRDialect:         }

! FIRDialect-LABEL:   func.func @compute.deinit6(
! FIRDialect-SAME:                               %[[VAL_0:[-0-9A-Za-z._]+]]: !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>,
! FIRDialect-SAME:                               %[[VAL_1:[-0-9A-Za-z._]+]]: i64) -> i32 {
! FIRDialect:           %[[VAL_2:[-0-9A-Za-z._]+]] = fir.load %[[VAL_0]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>
! FIRDialect:           %[[VAL_3:[-0-9A-Za-z._]+]] = fir.box_addr %[[VAL_2]] : (!fir.box<!fir.heap<!fir.array<?xi32>>>) -> !fir.heap<!fir.array<?xi32>>
! FIRDialect:           %[[VAL_4:[-0-9A-Za-z._]+]] = fir.convert %[[VAL_3]] : (!fir.heap<!fir.array<?xi32>>) -> i64
! FIRDialect:           %[[VAL_5:[-0-9A-Za-z._]+]] = arith.constant 0 : i64
! FIRDialect:           %[[VAL_6:[-0-9A-Za-z._]+]] = arith.cmpi ne, %[[VAL_4]], %[[VAL_5]] : i64
! FIRDialect:           fir.if %[[VAL_6]] {
! FIRDialect:             %[[VAL_7:[-0-9A-Za-z._]+]] = arith.constant false
! FIRDialect:             %[[VAL_8:[-0-9A-Za-z._]+]] = fir.absent !fir.box<none>
! FIRDialect:             %[[VAL_9:[-0-9A-Za-z._]+]] = fir.zero_bits !fir.ref<none>
! FIRDialect:             %[[VAL_10:[-0-9A-Za-z._]+]] = arith.constant 0 : i32
! FIRDialect:             %[[VAL_11:[-0-9A-Za-z._]+]] = fir.load %[[VAL_0]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>
! FIRDialect:             %[[VAL_12:[-0-9A-Za-z._]+]] = fir.box_addr %[[VAL_11]] : (!fir.box<!fir.heap<!fir.array<?xi32>>>) -> !fir.heap<!fir.array<?xi32>>
! FIRDialect:             fir.freemem %[[VAL_12]] : !fir.heap<!fir.array<?xi32>>
! FIRDialect:             %[[VAL_13:[-0-9A-Za-z._]+]] = fir.zero_bits !fir.heap<!fir.array<?xi32>>
! FIRDialect:             %[[VAL_14:[-0-9A-Za-z._]+]] = arith.constant 0 : index
! FIRDialect:             %[[VAL_15:[-0-9A-Za-z._]+]] = fir.shape %[[VAL_14]] : (index) -> !fir.shape<1>
! FIRDialect:             %[[VAL_16:[-0-9A-Za-z._]+]] = fir.embox %[[VAL_13]](%[[VAL_15]]) : (!fir.heap<!fir.array<?xi32>>, !fir.shape<1>) -> !fir.box<!fir.heap<!fir.array<?xi32>>>
! FIRDialect:             fir.store %[[VAL_16]] to %[[VAL_0]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>
! FIRDialect:           }
! FIRDialect:           %[[VAL_17:[-0-9A-Za-z._]+]] = arith.constant 1 : i32
! FIRDialect:           return %[[VAL_17]] : i32
! FIRDialect:         }

! FIRDialect-LABEL:   func.func @compute.copy5(
! FIRDialect-SAME:                             %[[VAL_0:[-0-9A-Za-z._]+]]: !fir.ref<!fir.box<!fir.ptr<!fir.array<?xi32>>>>,
! FIRDialect-SAME:                             %[[VAL_1:[-0-9A-Za-z._]+]]: !fir.ref<!fir.box<!fir.ptr<!fir.array<?xi32>>>>,
! FIRDialect-SAME:                             %[[VAL_2:[-0-9A-Za-z._]+]]: i64) -> i32 {
! FIRDialect:           %[[VAL_3:[-0-9A-Za-z._]+]] = fir.load %[[VAL_0]] : !fir.ref<!fir.box<!fir.ptr<!fir.array<?xi32>>>>
! FIRDialect:           %[[VAL_4:[-0-9A-Za-z._]+]] = arith.constant 0 : index
! FIRDialect:           %[[VAL_5:[-0-9A-Za-z._]+]]:3 = fir.box_dims %[[VAL_3]], %[[VAL_4]] : (!fir.box<!fir.ptr<!fir.array<?xi32>>>, index) -> (index, index, index)
! FIRDialect:           %[[VAL_6:[-0-9A-Za-z._]+]] = fir.shift %[[VAL_5]]#0 : (index) -> !fir.shift<1>
! FIRDialect:           %[[VAL_7:[-0-9A-Za-z._]+]] = fir.rebox %[[VAL_3]](%[[VAL_6]]) : (!fir.box<!fir.ptr<!fir.array<?xi32>>>, !fir.shift<1>) -> !fir.box<!fir.ptr<!fir.array<?xi32>>>
! FIRDialect:           fir.store %[[VAL_7]] to %[[VAL_1]] : !fir.ref<!fir.box<!fir.ptr<!fir.array<?xi32>>>>
! FIRDialect:           %[[VAL_8:[-0-9A-Za-z._]+]] = arith.constant 1 : i32
! FIRDialect:           return %[[VAL_8]] : i32
! FIRDialect:         }

! FIRDialect-LABEL:   func.func @compute.deinit7(
! FIRDialect-SAME:                               %[[VAL_0:[-0-9A-Za-z._]+]]: !fir.ref<!fir.box<!fir.ptr<!fir.array<?xi32>>>>,
! FIRDialect-SAME:                               %[[VAL_1:[-0-9A-Za-z._]+]]: i64) -> i32 {
! FIRDialect:           %[[VAL_2:[-0-9A-Za-z._]+]] = fir.zero_bits !fir.ptr<!fir.array<?xi32>>
! FIRDialect:           %[[VAL_3:[-0-9A-Za-z._]+]] = arith.constant 0 : index
! FIRDialect:           %[[VAL_4:[-0-9A-Za-z._]+]] = fir.shape %[[VAL_3]] : (index) -> !fir.shape<1>
! FIRDialect:           %[[VAL_5:[-0-9A-Za-z._]+]] = fir.embox %[[VAL_2]](%[[VAL_4]]) : (!fir.ptr<!fir.array<?xi32>>, !fir.shape<1>) -> !fir.box<!fir.ptr<!fir.array<?xi32>>>
! FIRDialect:           fir.store %[[VAL_5]] to %[[VAL_0]] : !fir.ref<!fir.box<!fir.ptr<!fir.array<?xi32>>>>
! FIRDialect:           %[[VAL_6:[-0-9A-Za-z._]+]] = arith.constant 1 : i32
! FIRDialect:           return %[[VAL_6]] : i32
! FIRDialect:         }

! FIRDialect-LABEL:   func.func @compute.copy6(
! FIRDialect-SAME:                             %[[VAL_0:[-0-9A-Za-z._]+]]: !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>,
! FIRDialect-SAME:                             %[[VAL_1:[-0-9A-Za-z._]+]]: !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>,
! FIRDialect-SAME:                             %[[VAL_2:[-0-9A-Za-z._]+]]: i64) -> i32 {
! FIRDialect:           %[[VAL_3:[-0-9A-Za-z._]+]] = fir.zero_bits !fir.heap<!fir.array<?xi32>>
! FIRDialect:           %[[VAL_4:[-0-9A-Za-z._]+]] = arith.constant 0 : index
! FIRDialect:           %[[VAL_5:[-0-9A-Za-z._]+]] = fir.shape %[[VAL_4]] : (index) -> !fir.shape<1>
! FIRDialect:           %[[VAL_6:[-0-9A-Za-z._]+]] = fir.embox %[[VAL_3]](%[[VAL_5]]) : (!fir.heap<!fir.array<?xi32>>, !fir.shape<1>) -> !fir.box<!fir.heap<!fir.array<?xi32>>>
! FIRDialect:           fir.store %[[VAL_6]] to %[[VAL_1]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>
! FIRDialect:           %[[VAL_7:[-0-9A-Za-z._]+]] = fir.load %[[VAL_0]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>
! FIRDialect:           %[[VAL_8:[-0-9A-Za-z._]+]] = fir.box_addr %[[VAL_7]] : (!fir.box<!fir.heap<!fir.array<?xi32>>>) -> !fir.heap<!fir.array<?xi32>>
! FIRDialect:           %[[VAL_9:[-0-9A-Za-z._]+]] = fir.convert %[[VAL_8]] : (!fir.heap<!fir.array<?xi32>>) -> i64
! FIRDialect:           %[[VAL_10:[-0-9A-Za-z._]+]] = arith.constant 0 : i64
! FIRDialect:           %[[VAL_11:[-0-9A-Za-z._]+]] = arith.cmpi ne, %[[VAL_9]], %[[VAL_10]] : i64
! FIRDialect:           fir.if %[[VAL_11]] {
! FIRDialect:             %[[VAL_12:[-0-9A-Za-z._]+]] = fir.load %[[VAL_0]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>
! FIRDialect:             %[[VAL_13:[-0-9A-Za-z._]+]] = arith.constant 0 : index
! FIRDialect:             %[[VAL_14:[-0-9A-Za-z._]+]]:3 = fir.box_dims %[[VAL_12]], %[[VAL_13]] : (!fir.box<!fir.heap<!fir.array<?xi32>>>, index) -> (index, index, index)
! FIRDialect:             %[[VAL_15:[-0-9A-Za-z._]+]] = fir.box_addr %[[VAL_12]] : (!fir.box<!fir.heap<!fir.array<?xi32>>>) -> !fir.heap<!fir.array<?xi32>>
! FIRDialect:             %[[VAL_16:[-0-9A-Za-z._]+]] = arith.constant 1 : index
! FIRDialect:             %[[VAL_17:[-0-9A-Za-z._]+]] = fir.shape_shift %[[VAL_14]]#0, %[[VAL_14]]#1 : (index, index) -> !fir.shapeshift<1>
! FIRDialect:             %[[VAL_18:[-0-9A-Za-z._]+]] = fir.array_load %[[VAL_15]](%[[VAL_17]]) : (!fir.heap<!fir.array<?xi32>>, !fir.shapeshift<1>) -> !fir.array<?xi32>
! FIRDialect:             %[[VAL_19:[-0-9A-Za-z._]+]] = fir.load %[[VAL_1]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>
! FIRDialect:             %[[VAL_20:[-0-9A-Za-z._]+]] = fir.box_addr %[[VAL_19]] : (!fir.box<!fir.heap<!fir.array<?xi32>>>) -> !fir.heap<!fir.array<?xi32>>
! FIRDialect:             %[[VAL_21:[-0-9A-Za-z._]+]] = fir.convert %[[VAL_20]] : (!fir.heap<!fir.array<?xi32>>) -> i64
! FIRDialect:             %[[VAL_22:[-0-9A-Za-z._]+]] = arith.constant 0 : i64
! FIRDialect:             %[[VAL_23:[-0-9A-Za-z._]+]] = arith.cmpi ne, %[[VAL_21]], %[[VAL_22]] : i64
! FIRDialect:             %[[VAL_24:[-0-9A-Za-z._]+]]:2 = fir.if %[[VAL_23]] -> (i1, !fir.heap<!fir.array<?xi32>>) {
! FIRDialect:               %[[VAL_25:[-0-9A-Za-z._]+]] = arith.constant false
! FIRDialect:               %[[VAL_26:[-0-9A-Za-z._]+]] = arith.constant 0 : index
! FIRDialect:               %[[VAL_27:[-0-9A-Za-z._]+]]:3 = fir.box_dims %[[VAL_19]], %[[VAL_26]] : (!fir.box<!fir.heap<!fir.array<?xi32>>>, index) -> (index, index, index)
! FIRDialect:               %[[VAL_28:[-0-9A-Za-z._]+]] = arith.cmpi ne, %[[VAL_27]]#1, %[[VAL_14]]#1 : index
! FIRDialect:               %[[VAL_29:[-0-9A-Za-z._]+]] = arith.select %[[VAL_28]], %[[VAL_28]], %[[VAL_25]] : i1
! FIRDialect:               %[[VAL_30:[-0-9A-Za-z._]+]] = fir.if %[[VAL_29]] -> (!fir.heap<!fir.array<?xi32>>) {
! FIRDialect:                 %[[VAL_31:[-0-9A-Za-z._]+]] = fir.allocmem !fir.array<?xi32>, %[[VAL_14]]#1 {uniq_name = ".auto.alloc"}
! FIRDialect:                 fir.result %[[VAL_31]] : !fir.heap<!fir.array<?xi32>>
! FIRDialect:               } else {
! FIRDialect:                 fir.result %[[VAL_20]] : !fir.heap<!fir.array<?xi32>>
! FIRDialect:               }
! FIRDialect:               fir.result %[[VAL_29]], %[[VAL_30]] : i1, !fir.heap<!fir.array<?xi32>>
! FIRDialect:             } else {
! FIRDialect:               %[[VAL_32:[-0-9A-Za-z._]+]] = arith.constant true
! FIRDialect:               %[[VAL_33:[-0-9A-Za-z._]+]] = fir.allocmem !fir.array<?xi32>, %[[VAL_14]]#1 {uniq_name = ".auto.alloc"}
! FIRDialect:               fir.result %[[VAL_32]], %[[VAL_33]] : i1, !fir.heap<!fir.array<?xi32>>
! FIRDialect:             }
! FIRDialect:             fir.if %[[VAL_34:[-0-9A-Za-z._]+]]#0 {
! FIRDialect:               %[[VAL_35:[-0-9A-Za-z._]+]] = fir.load %[[VAL_1]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>
! FIRDialect:               fir.if %[[VAL_23]] {
! FIRDialect:                 fir.freemem %[[VAL_20]] : !fir.heap<!fir.array<?xi32>>
! FIRDialect:               }
! FIRDialect:               %[[VAL_36:[-0-9A-Za-z._]+]] = fir.shape_shift %[[VAL_14]]#0, %[[VAL_14]]#1 : (index, index) -> !fir.shapeshift<1>
! FIRDialect:               %[[VAL_37:[-0-9A-Za-z._]+]] = fir.embox %[[VAL_34]]#1(%[[VAL_36]]) : (!fir.heap<!fir.array<?xi32>>, !fir.shapeshift<1>) -> !fir.box<!fir.heap<!fir.array<?xi32>>>
! FIRDialect:               fir.store %[[VAL_37]] to %[[VAL_1]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>
! FIRDialect:             }
! FIRDialect:           }
! FIRDialect:           %[[VAL_38:[-0-9A-Za-z._]+]] = arith.constant 1 : i32
! FIRDialect:           return %[[VAL_38]] : i32
! FIRDialect:         }

! FIRDialect-LABEL:   func.func @compute.deinit8(
! FIRDialect-SAME:                               %[[VAL_0:[-0-9A-Za-z._]+]]: !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>,
! FIRDialect-SAME:                               %[[VAL_1:[-0-9A-Za-z._]+]]: i64) -> i32 {
! FIRDialect:           %[[VAL_2:[-0-9A-Za-z._]+]] = fir.load %[[VAL_0]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>
! FIRDialect:           %[[VAL_3:[-0-9A-Za-z._]+]] = fir.box_addr %[[VAL_2]] : (!fir.box<!fir.heap<!fir.array<?xi32>>>) -> !fir.heap<!fir.array<?xi32>>
! FIRDialect:           %[[VAL_4:[-0-9A-Za-z._]+]] = fir.convert %[[VAL_3]] : (!fir.heap<!fir.array<?xi32>>) -> i64
! FIRDialect:           %[[VAL_5:[-0-9A-Za-z._]+]] = arith.constant 0 : i64
! FIRDialect:           %[[VAL_6:[-0-9A-Za-z._]+]] = arith.cmpi ne, %[[VAL_4]], %[[VAL_5]] : i64
! FIRDialect:           fir.if %[[VAL_6]] {
! FIRDialect:             %[[VAL_7:[-0-9A-Za-z._]+]] = arith.constant false
! FIRDialect:             %[[VAL_8:[-0-9A-Za-z._]+]] = fir.absent !fir.box<none>
! FIRDialect:             %[[VAL_9:[-0-9A-Za-z._]+]] = fir.zero_bits !fir.ref<none>
! FIRDialect:             %[[VAL_10:[-0-9A-Za-z._]+]] = arith.constant 0 : i32
! FIRDialect:             %[[VAL_11:[-0-9A-Za-z._]+]] = fir.load %[[VAL_0]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>
! FIRDialect:             %[[VAL_12:[-0-9A-Za-z._]+]] = fir.box_addr %[[VAL_11]] : (!fir.box<!fir.heap<!fir.array<?xi32>>>) -> !fir.heap<!fir.array<?xi32>>
! FIRDialect:             fir.freemem %[[VAL_12]] : !fir.heap<!fir.array<?xi32>>
! FIRDialect:             %[[VAL_13:[-0-9A-Za-z._]+]] = fir.zero_bits !fir.heap<!fir.array<?xi32>>
! FIRDialect:             %[[VAL_14:[-0-9A-Za-z._]+]] = arith.constant 0 : index
! FIRDialect:             %[[VAL_15:[-0-9A-Za-z._]+]] = fir.shape %[[VAL_14]] : (index) -> !fir.shape<1>
! FIRDialect:             %[[VAL_16:[-0-9A-Za-z._]+]] = fir.embox %[[VAL_13]](%[[VAL_15]]) : (!fir.heap<!fir.array<?xi32>>, !fir.shape<1>) -> !fir.box<!fir.heap<!fir.array<?xi32>>>
! FIRDialect:             fir.store %[[VAL_16]] to %[[VAL_0]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>
! FIRDialect:           }
! FIRDialect:           %[[VAL_17:[-0-9A-Za-z._]+]] = arith.constant 1 : i32
! FIRDialect:           return %[[VAL_17]] : i32
! FIRDialect:         }

! FIRDialect-LABEL:   func.func @compute.init2(
! FIRDialect-SAME:                             %[[VAL_0:[-0-9A-Za-z._]+]]: !fir.ref<!fir.box<!fir.ptr<!fir.array<?xi32>>>>,
! FIRDialect-SAME:                             %[[VAL_1:[-0-9A-Za-z._]+]]: i64) -> i32 {
! FIRDialect:           %[[VAL_2:[-0-9A-Za-z._]+]] = fir.zero_bits !fir.ptr<!fir.array<?xi32>>
! FIRDialect:           %[[VAL_3:[-0-9A-Za-z._]+]] = arith.constant 0 : index
! FIRDialect:           %[[VAL_4:[-0-9A-Za-z._]+]] = fir.shape %[[VAL_3]] : (index) -> !fir.shape<1>
! FIRDialect:           %[[VAL_5:[-0-9A-Za-z._]+]] = fir.embox %[[VAL_2]](%[[VAL_4]]) : (!fir.ptr<!fir.array<?xi32>>, !fir.shape<1>) -> !fir.box<!fir.ptr<!fir.array<?xi32>>>
! FIRDialect:           fir.store %[[VAL_5]] to %[[VAL_0]] : !fir.ref<!fir.box<!fir.ptr<!fir.array<?xi32>>>>
! FIRDialect:           %[[VAL_6:[-0-9A-Za-z._]+]] = arith.constant 1 : i32
! FIRDialect:           return %[[VAL_6]] : i32
! FIRDialect:         }

! FIRDialect-LABEL:   func.func @compute.deinit9(
! FIRDialect-SAME:                               %[[VAL_0:[-0-9A-Za-z._]+]]: !fir.ref<!fir.box<!fir.ptr<!fir.array<?xi32>>>>,
! FIRDialect-SAME:                               %[[VAL_1:[-0-9A-Za-z._]+]]: i64) -> i32 {
! FIRDialect:           %[[VAL_2:[-0-9A-Za-z._]+]] = fir.zero_bits !fir.ptr<!fir.array<?xi32>>
! FIRDialect:           %[[VAL_3:[-0-9A-Za-z._]+]] = arith.constant 0 : index
! FIRDialect:           %[[VAL_4:[-0-9A-Za-z._]+]] = fir.shape %[[VAL_3]] : (index) -> !fir.shape<1>
! FIRDialect:           %[[VAL_5:[-0-9A-Za-z._]+]] = fir.embox %[[VAL_2]](%[[VAL_4]]) : (!fir.ptr<!fir.array<?xi32>>, !fir.shape<1>) -> !fir.box<!fir.ptr<!fir.array<?xi32>>>
! FIRDialect:           fir.store %[[VAL_5]] to %[[VAL_0]] : !fir.ref<!fir.box<!fir.ptr<!fir.array<?xi32>>>>
! FIRDialect:           %[[VAL_6:[-0-9A-Za-z._]+]] = arith.constant 1 : i32
! FIRDialect:           return %[[VAL_6]] : i32
! FIRDialect:         }

! FIRDialect-LABEL:   func.func @compute.copy7(
! FIRDialect-SAME:                             %[[VAL_0:[-0-9A-Za-z._]+]]: !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>,
! FIRDialect-SAME:                             %[[VAL_1:[-0-9A-Za-z._]+]]: !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>,
! FIRDialect-SAME:                             %[[VAL_2:[-0-9A-Za-z._]+]]: i64) -> i32 {
! FIRDialect:           %[[VAL_3:[-0-9A-Za-z._]+]] = fir.zero_bits !fir.heap<!fir.array<?xi32>>
! FIRDialect:           %[[VAL_4:[-0-9A-Za-z._]+]] = arith.constant 0 : index
! FIRDialect:           %[[VAL_5:[-0-9A-Za-z._]+]] = fir.shape %[[VAL_4]] : (index) -> !fir.shape<1>
! FIRDialect:           %[[VAL_6:[-0-9A-Za-z._]+]] = fir.embox %[[VAL_3]](%[[VAL_5]]) : (!fir.heap<!fir.array<?xi32>>, !fir.shape<1>) -> !fir.box<!fir.heap<!fir.array<?xi32>>>
! FIRDialect:           fir.store %[[VAL_6]] to %[[VAL_1]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>
! FIRDialect:           %[[VAL_7:[-0-9A-Za-z._]+]] = fir.load %[[VAL_0]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>
! FIRDialect:           %[[VAL_8:[-0-9A-Za-z._]+]] = fir.box_addr %[[VAL_7]] : (!fir.box<!fir.heap<!fir.array<?xi32>>>) -> !fir.heap<!fir.array<?xi32>>
! FIRDialect:           %[[VAL_9:[-0-9A-Za-z._]+]] = fir.convert %[[VAL_8]] : (!fir.heap<!fir.array<?xi32>>) -> i64
! FIRDialect:           %[[VAL_10:[-0-9A-Za-z._]+]] = arith.constant 0 : i64
! FIRDialect:           %[[VAL_11:[-0-9A-Za-z._]+]] = arith.cmpi ne, %[[VAL_9]], %[[VAL_10]] : i64
! FIRDialect:           fir.if %[[VAL_11]] {
! FIRDialect:             %[[VAL_12:[-0-9A-Za-z._]+]] = fir.load %[[VAL_0]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>
! FIRDialect:             %[[VAL_13:[-0-9A-Za-z._]+]] = arith.constant 0 : index
! FIRDialect:             %[[VAL_14:[-0-9A-Za-z._]+]]:3 = fir.box_dims %[[VAL_12]], %[[VAL_13]] : (!fir.box<!fir.heap<!fir.array<?xi32>>>, index) -> (index, index, index)
! FIRDialect:             %[[VAL_15:[-0-9A-Za-z._]+]] = fir.box_addr %[[VAL_12]] : (!fir.box<!fir.heap<!fir.array<?xi32>>>) -> !fir.heap<!fir.array<?xi32>>
! FIRDialect:             %[[VAL_16:[-0-9A-Za-z._]+]] = arith.constant 1 : index
! FIRDialect:             %[[VAL_17:[-0-9A-Za-z._]+]] = fir.shape_shift %[[VAL_14]]#0, %[[VAL_14]]#1 : (index, index) -> !fir.shapeshift<1>
! FIRDialect:             %[[VAL_18:[-0-9A-Za-z._]+]] = fir.array_load %[[VAL_15]](%[[VAL_17]]) : (!fir.heap<!fir.array<?xi32>>, !fir.shapeshift<1>) -> !fir.array<?xi32>
! FIRDialect:             %[[VAL_19:[-0-9A-Za-z._]+]] = fir.load %[[VAL_1]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>
! FIRDialect:             %[[VAL_20:[-0-9A-Za-z._]+]] = fir.box_addr %[[VAL_19]] : (!fir.box<!fir.heap<!fir.array<?xi32>>>) -> !fir.heap<!fir.array<?xi32>>
! FIRDialect:             %[[VAL_21:[-0-9A-Za-z._]+]] = fir.convert %[[VAL_20]] : (!fir.heap<!fir.array<?xi32>>) -> i64
! FIRDialect:             %[[VAL_22:[-0-9A-Za-z._]+]] = arith.constant 0 : i64
! FIRDialect:             %[[VAL_23:[-0-9A-Za-z._]+]] = arith.cmpi ne, %[[VAL_21]], %[[VAL_22]] : i64
! FIRDialect:             %[[VAL_24:[-0-9A-Za-z._]+]]:2 = fir.if %[[VAL_23]] -> (i1, !fir.heap<!fir.array<?xi32>>) {
! FIRDialect:               %[[VAL_25:[-0-9A-Za-z._]+]] = arith.constant false
! FIRDialect:               %[[VAL_26:[-0-9A-Za-z._]+]] = arith.constant 0 : index
! FIRDialect:               %[[VAL_27:[-0-9A-Za-z._]+]]:3 = fir.box_dims %[[VAL_19]], %[[VAL_26]] : (!fir.box<!fir.heap<!fir.array<?xi32>>>, index) -> (index, index, index)
! FIRDialect:               %[[VAL_28:[-0-9A-Za-z._]+]] = arith.cmpi ne, %[[VAL_27]]#1, %[[VAL_14]]#1 : index
! FIRDialect:               %[[VAL_29:[-0-9A-Za-z._]+]] = arith.select %[[VAL_28]], %[[VAL_28]], %[[VAL_25]] : i1
! FIRDialect:               %[[VAL_30:[-0-9A-Za-z._]+]] = fir.if %[[VAL_29]] -> (!fir.heap<!fir.array<?xi32>>) {
! FIRDialect:                 %[[VAL_31:[-0-9A-Za-z._]+]] = fir.allocmem !fir.array<?xi32>, %[[VAL_14]]#1 {uniq_name = ".auto.alloc"}
! FIRDialect:                 %[[VAL_32:[-0-9A-Za-z._]+]] = fir.shape %[[VAL_14]]#1 : (index) -> !fir.shape<1>
! FIRDialect:                 %[[VAL_33:[-0-9A-Za-z._]+]] = fir.array_load %[[VAL_31]](%[[VAL_32]]) : (!fir.heap<!fir.array<?xi32>>, !fir.shape<1>) -> !fir.array<?xi32>
! FIRDialect:                 %[[VAL_34:[-0-9A-Za-z._]+]] = arith.constant 1 : index
! FIRDialect:                 %[[VAL_35:[-0-9A-Za-z._]+]] = arith.constant 0 : index
! FIRDialect:                 %[[VAL_36:[-0-9A-Za-z._]+]] = arith.subi %[[VAL_14]]#1, %[[VAL_34]] : index
! FIRDialect:                 %[[VAL_37:[-0-9A-Za-z._]+]] = fir.do_loop %[[VAL_38:[-0-9A-Za-z._]+]] = %[[VAL_35]] to %[[VAL_36]] step %[[VAL_34]] unordered iter_args(%[[VAL_39:[-0-9A-Za-z._]+]] = %[[VAL_33]]) -> (!fir.array<?xi32>) {
! FIRDialect:                   %[[VAL_40:[-0-9A-Za-z._]+]] = fir.array_fetch %[[VAL_18]], %[[VAL_38]] : (!fir.array<?xi32>, index) -> i32
! FIRDialect:                   %[[VAL_41:[-0-9A-Za-z._]+]] = fir.array_update %[[VAL_39]], %[[VAL_40]], %[[VAL_38]] : (!fir.array<?xi32>, i32, index) -> !fir.array<?xi32>
! FIRDialect:                   %[[VAL_42:[-0-9A-Za-z._]+]] = fir.undefined index
! FIRDialect:                   fir.result %[[VAL_41]] : !fir.array<?xi32>
! FIRDialect:                 }
! FIRDialect:                 %[[VAL_43:[-0-9A-Za-z._]+]] = fir.undefined index
! FIRDialect:                 fir.array_merge_store %[[VAL_33]], %[[VAL_37]] to %[[VAL_31]] : !fir.array<?xi32>, !fir.array<?xi32>, !fir.heap<!fir.array<?xi32>>
! FIRDialect:                 fir.result %[[VAL_31]] : !fir.heap<!fir.array<?xi32>>
! FIRDialect:               } else {
! FIRDialect:                 %[[VAL_44:[-0-9A-Za-z._]+]] = fir.shape %[[VAL_14]]#1 : (index) -> !fir.shape<1>
! FIRDialect:                 %[[VAL_45:[-0-9A-Za-z._]+]] = fir.array_load %[[VAL_20]](%[[VAL_44]]) : (!fir.heap<!fir.array<?xi32>>, !fir.shape<1>) -> !fir.array<?xi32>
! FIRDialect:                 %[[VAL_46:[-0-9A-Za-z._]+]] = arith.constant 1 : index
! FIRDialect:                 %[[VAL_47:[-0-9A-Za-z._]+]] = arith.constant 0 : index
! FIRDialect:                 %[[VAL_48:[-0-9A-Za-z._]+]] = arith.subi %[[VAL_14]]#1, %[[VAL_46]] : index
! FIRDialect:                 %[[VAL_49:[-0-9A-Za-z._]+]] = fir.do_loop %[[VAL_50:[-0-9A-Za-z._]+]] = %[[VAL_47]] to %[[VAL_48]] step %[[VAL_46]] unordered iter_args(%[[VAL_51:[-0-9A-Za-z._]+]] = %[[VAL_45]]) -> (!fir.array<?xi32>) {
! FIRDialect:                   %[[VAL_52:[-0-9A-Za-z._]+]] = fir.array_fetch %[[VAL_18]], %[[VAL_50]] : (!fir.array<?xi32>, index) -> i32
! FIRDialect:                   %[[VAL_53:[-0-9A-Za-z._]+]] = fir.array_update %[[VAL_51]], %[[VAL_52]], %[[VAL_50]] : (!fir.array<?xi32>, i32, index) -> !fir.array<?xi32>
! FIRDialect:                   %[[VAL_54:[-0-9A-Za-z._]+]] = fir.undefined index
! FIRDialect:                   fir.result %[[VAL_53]] : !fir.array<?xi32>
! FIRDialect:                 }
! FIRDialect:                 %[[VAL_55:[-0-9A-Za-z._]+]] = fir.undefined index
! FIRDialect:                 fir.array_merge_store %[[VAL_45]], %[[VAL_49]] to %[[VAL_20]] : !fir.array<?xi32>, !fir.array<?xi32>, !fir.heap<!fir.array<?xi32>>
! FIRDialect:                 fir.result %[[VAL_20]] : !fir.heap<!fir.array<?xi32>>
! FIRDialect:               }
! FIRDialect:               fir.result %[[VAL_29]], %[[VAL_30]] : i1, !fir.heap<!fir.array<?xi32>>
! FIRDialect:             } else {
! FIRDialect:               %[[VAL_56:[-0-9A-Za-z._]+]] = arith.constant true
! FIRDialect:               %[[VAL_57:[-0-9A-Za-z._]+]] = fir.allocmem !fir.array<?xi32>, %[[VAL_14]]#1 {uniq_name = ".auto.alloc"}
! FIRDialect:               %[[VAL_58:[-0-9A-Za-z._]+]] = fir.shape %[[VAL_14]]#1 : (index) -> !fir.shape<1>
! FIRDialect:               %[[VAL_59:[-0-9A-Za-z._]+]] = fir.array_load %[[VAL_57]](%[[VAL_58]]) : (!fir.heap<!fir.array<?xi32>>, !fir.shape<1>) -> !fir.array<?xi32>
! FIRDialect:               %[[VAL_60:[-0-9A-Za-z._]+]] = arith.constant 1 : index
! FIRDialect:               %[[VAL_61:[-0-9A-Za-z._]+]] = arith.constant 0 : index
! FIRDialect:               %[[VAL_62:[-0-9A-Za-z._]+]] = arith.subi %[[VAL_14]]#1, %[[VAL_60]] : index
! FIRDialect:               %[[VAL_63:[-0-9A-Za-z._]+]] = fir.do_loop %[[VAL_64:[-0-9A-Za-z._]+]] = %[[VAL_61]] to %[[VAL_62]] step %[[VAL_60]] unordered iter_args(%[[VAL_65:[-0-9A-Za-z._]+]] = %[[VAL_59]]) -> (!fir.array<?xi32>) {
! FIRDialect:                 %[[VAL_66:[-0-9A-Za-z._]+]] = fir.array_fetch %[[VAL_18]], %[[VAL_64]] : (!fir.array<?xi32>, index) -> i32
! FIRDialect:                 %[[VAL_67:[-0-9A-Za-z._]+]] = fir.array_update %[[VAL_65]], %[[VAL_66]], %[[VAL_64]] : (!fir.array<?xi32>, i32, index) -> !fir.array<?xi32>
! FIRDialect:                 %[[VAL_68:[-0-9A-Za-z._]+]] = fir.undefined index
! FIRDialect:                 fir.result %[[VAL_67]] : !fir.array<?xi32>
! FIRDialect:               }
! FIRDialect:               %[[VAL_69:[-0-9A-Za-z._]+]] = fir.undefined index
! FIRDialect:               fir.array_merge_store %[[VAL_59]], %[[VAL_63]] to %[[VAL_57]] : !fir.array<?xi32>, !fir.array<?xi32>, !fir.heap<!fir.array<?xi32>>
! FIRDialect:               fir.result %[[VAL_56]], %[[VAL_57]] : i1, !fir.heap<!fir.array<?xi32>>
! FIRDialect:             }
! FIRDialect:             fir.if %[[VAL_70:[-0-9A-Za-z._]+]]#0 {
! FIRDialect:               %[[VAL_71:[-0-9A-Za-z._]+]] = fir.load %[[VAL_1]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>
! FIRDialect:               fir.if %[[VAL_23]] {
! FIRDialect:                 fir.freemem %[[VAL_20]] : !fir.heap<!fir.array<?xi32>>
! FIRDialect:               }
! FIRDialect:               %[[VAL_72:[-0-9A-Za-z._]+]] = fir.shape_shift %[[VAL_14]]#0, %[[VAL_14]]#1 : (index, index) -> !fir.shapeshift<1>
! FIRDialect:               %[[VAL_73:[-0-9A-Za-z._]+]] = fir.embox %[[VAL_70]]#1(%[[VAL_72]]) : (!fir.heap<!fir.array<?xi32>>, !fir.shapeshift<1>) -> !fir.box<!fir.heap<!fir.array<?xi32>>>
! FIRDialect:               fir.store %[[VAL_73]] to %[[VAL_1]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>
! FIRDialect:             }
! FIRDialect:           }
! FIRDialect:           %[[VAL_74:[-0-9A-Za-z._]+]] = arith.constant 1 : i32
! FIRDialect:           return %[[VAL_74]] : i32
! FIRDialect:         }

! FIRDialect-LABEL:   func.func @compute.deinit10(
! FIRDialect-SAME:                                %[[VAL_0:[-0-9A-Za-z._]+]]: !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>,
! FIRDialect-SAME:                                %[[VAL_1:[-0-9A-Za-z._]+]]: i64) -> i32 {
! FIRDialect:           %[[VAL_2:[-0-9A-Za-z._]+]] = fir.load %[[VAL_0]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>
! FIRDialect:           %[[VAL_3:[-0-9A-Za-z._]+]] = fir.box_addr %[[VAL_2]] : (!fir.box<!fir.heap<!fir.array<?xi32>>>) -> !fir.heap<!fir.array<?xi32>>
! FIRDialect:           %[[VAL_4:[-0-9A-Za-z._]+]] = fir.convert %[[VAL_3]] : (!fir.heap<!fir.array<?xi32>>) -> i64
! FIRDialect:           %[[VAL_5:[-0-9A-Za-z._]+]] = arith.constant 0 : i64
! FIRDialect:           %[[VAL_6:[-0-9A-Za-z._]+]] = arith.cmpi ne, %[[VAL_4]], %[[VAL_5]] : i64
! FIRDialect:           fir.if %[[VAL_6]] {
! FIRDialect:             %[[VAL_7:[-0-9A-Za-z._]+]] = arith.constant false
! FIRDialect:             %[[VAL_8:[-0-9A-Za-z._]+]] = fir.absent !fir.box<none>
! FIRDialect:             %[[VAL_9:[-0-9A-Za-z._]+]] = fir.zero_bits !fir.ref<none>
! FIRDialect:             %[[VAL_10:[-0-9A-Za-z._]+]] = arith.constant 0 : i32
! FIRDialect:             %[[VAL_11:[-0-9A-Za-z._]+]] = fir.load %[[VAL_0]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>
! FIRDialect:             %[[VAL_12:[-0-9A-Za-z._]+]] = fir.box_addr %[[VAL_11]] : (!fir.box<!fir.heap<!fir.array<?xi32>>>) -> !fir.heap<!fir.array<?xi32>>
! FIRDialect:             fir.freemem %[[VAL_12]] : !fir.heap<!fir.array<?xi32>>
! FIRDialect:             %[[VAL_13:[-0-9A-Za-z._]+]] = fir.zero_bits !fir.heap<!fir.array<?xi32>>
! FIRDialect:             %[[VAL_14:[-0-9A-Za-z._]+]] = arith.constant 0 : index
! FIRDialect:             %[[VAL_15:[-0-9A-Za-z._]+]] = fir.shape %[[VAL_14]] : (index) -> !fir.shape<1>
! FIRDialect:             %[[VAL_16:[-0-9A-Za-z._]+]] = fir.embox %[[VAL_13]](%[[VAL_15]]) : (!fir.heap<!fir.array<?xi32>>, !fir.shape<1>) -> !fir.box<!fir.heap<!fir.array<?xi32>>>
! FIRDialect:             fir.store %[[VAL_16]] to %[[VAL_0]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xi32>>>>
! FIRDialect:           }
! FIRDialect:           %[[VAL_17:[-0-9A-Za-z._]+]] = arith.constant 1 : i32
! FIRDialect:           return %[[VAL_17]] : i32
! FIRDialect:         }

! FIRDialect-LABEL:   func.func @compute.copy8(
! FIRDialect-SAME:                             %[[VAL_0:[-0-9A-Za-z._]+]]: !fir.ref<!fir.box<!fir.ptr<!fir.array<?xi32>>>>,
! FIRDialect-SAME:                             %[[VAL_1:[-0-9A-Za-z._]+]]: !fir.ref<!fir.box<!fir.ptr<!fir.array<?xi32>>>>,
! FIRDialect-SAME:                             %[[VAL_2:[-0-9A-Za-z._]+]]: i64) -> i32 {
! FIRDialect:           %[[VAL_3:[-0-9A-Za-z._]+]] = fir.load %[[VAL_0]] : !fir.ref<!fir.box<!fir.ptr<!fir.array<?xi32>>>>
! FIRDialect:           %[[VAL_4:[-0-9A-Za-z._]+]] = arith.constant 0 : index
! FIRDialect:           %[[VAL_5:[-0-9A-Za-z._]+]]:3 = fir.box_dims %[[VAL_3]], %[[VAL_4]] : (!fir.box<!fir.ptr<!fir.array<?xi32>>>, index) -> (index, index, index)
! FIRDialect:           %[[VAL_6:[-0-9A-Za-z._]+]] = fir.shift %[[VAL_5]]#0 : (index) -> !fir.shift<1>
! FIRDialect:           %[[VAL_7:[-0-9A-Za-z._]+]] = fir.rebox %[[VAL_3]](%[[VAL_6]]) : (!fir.box<!fir.ptr<!fir.array<?xi32>>>, !fir.shift<1>) -> !fir.box<!fir.ptr<!fir.array<?xi32>>>
! FIRDialect:           fir.store %[[VAL_7]] to %[[VAL_1]] : !fir.ref<!fir.box<!fir.ptr<!fir.array<?xi32>>>>
! FIRDialect:           %[[VAL_8:[-0-9A-Za-z._]+]] = arith.constant 1 : i32
! FIRDialect:           return %[[VAL_8]] : i32
! FIRDialect:         }

! FIRDialect-LABEL:   func.func @compute.deinit11(
! FIRDialect-SAME:                                %[[VAL_0:[-0-9A-Za-z._]+]]: !fir.ref<!fir.box<!fir.ptr<!fir.array<?xi32>>>>,
! FIRDialect-SAME:                                %[[VAL_1:[-0-9A-Za-z._]+]]: i64) -> i32 {
! FIRDialect:           %[[VAL_2:[-0-9A-Za-z._]+]] = fir.zero_bits !fir.ptr<!fir.array<?xi32>>
! FIRDialect:           %[[VAL_3:[-0-9A-Za-z._]+]] = arith.constant 0 : index
! FIRDialect:           %[[VAL_4:[-0-9A-Za-z._]+]] = fir.shape %[[VAL_3]] : (index) -> !fir.shape<1>
! FIRDialect:           %[[VAL_5:[-0-9A-Za-z._]+]] = fir.embox %[[VAL_2]](%[[VAL_4]]) : (!fir.ptr<!fir.array<?xi32>>, !fir.shape<1>) -> !fir.box<!fir.ptr<!fir.array<?xi32>>>
! FIRDialect:           fir.store %[[VAL_5]] to %[[VAL_0]] : !fir.ref<!fir.box<!fir.ptr<!fir.array<?xi32>>>>
! FIRDialect:           %[[VAL_6:[-0-9A-Za-z._]+]] = arith.constant 1 : i32
! FIRDialect:           return %[[VAL_6]] : i32
! FIRDialect:         }

