! NOTE: Assertions have been autogenerated by /home/rpenacob/llvm-mono/mlir/utils/generate-test-checks.py
! RUN: flang-new -fc1 -emit-fir -fompss-2 -o - %s -flang-deprecated-no-hlfir | FileCheck %s --check-prefix=FIRDialect

!$OSS TASK INOUT(X)
SUBROUTINE S1(X)
  IMPLICIT NONE
  INTEGER :: X(10)
END SUBROUTINE S1

MODULE MOO
CONTAINS
  !$OSS TASK INOUT(X)
  SUBROUTINE S2(X)
    IMPLICIT NONE
    INTEGER :: X(10)
  END SUBROUTINE S2
END MODULE MOO

PROGRAM MAIN
  USE MOO, ONLY : S2
  IMPLICIT NONE
  INTEGER :: X(10)
  CALL S1(X)
  CALL S2(X)
  !$OSS TASKWAIT
END PROGRAM MAIN 


! FIRDialect-LABEL:   func.func @_QPs1(
! FIRDialect-SAME:                     %[[VAL_0:[-0-9A-Za-z._]+]]: !fir.ref<!fir.array<10xi32>> {fir.bindc_name = "x"}) {
! FIRDialect:           return
! FIRDialect:         }

! FIRDialect-LABEL:   func.func @_QMmooPs2(
! FIRDialect-SAME:                         %[[VAL_0:[-0-9A-Za-z._]+]]: !fir.ref<!fir.array<10xi32>> {fir.bindc_name = "x"}) {
! FIRDialect:           return
! FIRDialect:         }

! FIRDialect-LABEL:   func.func @_QQmain() attributes {fir.bindc_name = "MAIN"} {
! FIRDialect:           %[[VAL_0:[-0-9A-Za-z._]+]] = fir.address_of(@_QFEx) : !fir.ref<!fir.array<10xi32>>
! FIRDialect:           %[[VAL_1:[-0-9A-Za-z._]+]] = oss.dependency base(%[[VAL_0]] : !fir.ref<!fir.array<10xi32>>) function(@compute.dep0) arguments(%[[VAL_0]] : !fir.ref<!fir.array<10xi32>>) -> i32
! FIRDialect:           %[[VAL_2:[-0-9A-Za-z._]+]] = fir.undefined !fir.oss<!fir.array<10xi32>>
! FIRDialect:           oss.task shared(%[[VAL_0]] : !fir.ref<!fir.array<10xi32>>) shared_type(%[[VAL_2]] : !fir.oss<!fir.array<10xi32>>) inout(%[[VAL_1]] : i32) {
! FIRDialect:             fir.call @_QPs1(%[[VAL_0]]) fastmath<contract> : (!fir.ref<!fir.array<10xi32>>) -> ()
! FIRDialect:             oss.terminator
! FIRDialect:           }
! FIRDialect:           %[[VAL_3:[-0-9A-Za-z._]+]] = oss.dependency base(%[[VAL_0]] : !fir.ref<!fir.array<10xi32>>) function(@compute.dep1) arguments(%[[VAL_0]] : !fir.ref<!fir.array<10xi32>>) -> i32
! FIRDialect:           %[[VAL_4:[-0-9A-Za-z._]+]] = fir.undefined !fir.oss<!fir.array<10xi32>>
! FIRDialect:           oss.task shared(%[[VAL_0]] : !fir.ref<!fir.array<10xi32>>) shared_type(%[[VAL_4]] : !fir.oss<!fir.array<10xi32>>) inout(%[[VAL_3]] : i32) {
! FIRDialect:             fir.call @_QMmooPs2(%[[VAL_0]]) fastmath<contract> : (!fir.ref<!fir.array<10xi32>>) -> ()
! FIRDialect:             oss.terminator
! FIRDialect:           }
! FIRDialect:           oss.taskwait
! FIRDialect:           return
! FIRDialect:         }

! FIRDialect-LABEL:   fir.global internal @_QFEx : !fir.array<10xi32> {
! FIRDialect:           %[[VAL_0:[-0-9A-Za-z._]+]] = fir.zero_bits !fir.array<10xi32>
! FIRDialect:           fir.has_value %[[VAL_0]] : !fir.array<10xi32>
! FIRDialect:         }

! FIRDialect-LABEL:   func.func @compute.dep0(
! FIRDialect-SAME:                            %[[VAL_0:[-0-9A-Za-z._]+]]: !fir.ref<!fir.array<10xi32>>) -> (!fir.ref<!fir.array<10xi32>>, i64, i64, i64) {
! FIRDialect:           %[[VAL_1:[-0-9A-Za-z._]+]] = arith.constant 10 : index
! FIRDialect:           %[[VAL_2:[-0-9A-Za-z._]+]] = arith.constant 10 : i64
! FIRDialect:           %[[VAL_3:[-0-9A-Za-z._]+]] = arith.constant 1 : i64
! FIRDialect:           %[[VAL_4:[-0-9A-Za-z._]+]] = arith.constant 10 : i64
! FIRDialect:           %[[VAL_5:[-0-9A-Za-z._]+]] = arith.constant 1 : i64
! FIRDialect:           %[[VAL_6:[-0-9A-Za-z._]+]] = arith.constant 4 : i64
! FIRDialect:           %[[VAL_7:[-0-9A-Za-z._]+]] = arith.subi %[[VAL_3]], %[[VAL_3]] : i64
! FIRDialect:           %[[VAL_8:[-0-9A-Za-z._]+]] = arith.subi %[[VAL_4]], %[[VAL_3]] : i64
! FIRDialect:           %[[VAL_9:[-0-9A-Za-z._]+]] = arith.addi %[[VAL_8]], %[[VAL_5]] : i64
! FIRDialect:           %[[VAL_10:[-0-9A-Za-z._]+]] = arith.muli %[[VAL_2]], %[[VAL_6]] : i64
! FIRDialect:           %[[VAL_11:[-0-9A-Za-z._]+]] = arith.muli %[[VAL_7]], %[[VAL_6]] : i64
! FIRDialect:           %[[VAL_12:[-0-9A-Za-z._]+]] = arith.muli %[[VAL_9]], %[[VAL_6]] : i64
! FIRDialect:           return %[[VAL_0]], %[[VAL_10]], %[[VAL_11]], %[[VAL_12]] : !fir.ref<!fir.array<10xi32>>, i64, i64, i64
! FIRDialect:         }

! FIRDialect-LABEL:   func.func @compute.dep1(
! FIRDialect-SAME:                            %[[VAL_0:[-0-9A-Za-z._]+]]: !fir.ref<!fir.array<10xi32>>) -> (!fir.ref<!fir.array<10xi32>>, i64, i64, i64) {
! FIRDialect:           %[[VAL_1:[-0-9A-Za-z._]+]] = arith.constant 10 : index
! FIRDialect:           %[[VAL_2:[-0-9A-Za-z._]+]] = arith.constant 10 : i64
! FIRDialect:           %[[VAL_3:[-0-9A-Za-z._]+]] = arith.constant 1 : i64
! FIRDialect:           %[[VAL_4:[-0-9A-Za-z._]+]] = arith.constant 10 : i64
! FIRDialect:           %[[VAL_5:[-0-9A-Za-z._]+]] = arith.constant 1 : i64
! FIRDialect:           %[[VAL_6:[-0-9A-Za-z._]+]] = arith.constant 4 : i64
! FIRDialect:           %[[VAL_7:[-0-9A-Za-z._]+]] = arith.subi %[[VAL_3]], %[[VAL_3]] : i64
! FIRDialect:           %[[VAL_8:[-0-9A-Za-z._]+]] = arith.subi %[[VAL_4]], %[[VAL_3]] : i64
! FIRDialect:           %[[VAL_9:[-0-9A-Za-z._]+]] = arith.addi %[[VAL_8]], %[[VAL_5]] : i64
! FIRDialect:           %[[VAL_10:[-0-9A-Za-z._]+]] = arith.muli %[[VAL_2]], %[[VAL_6]] : i64
! FIRDialect:           %[[VAL_11:[-0-9A-Za-z._]+]] = arith.muli %[[VAL_7]], %[[VAL_6]] : i64
! FIRDialect:           %[[VAL_12:[-0-9A-Za-z._]+]] = arith.muli %[[VAL_9]], %[[VAL_6]] : i64
! FIRDialect:           return %[[VAL_0]], %[[VAL_10]], %[[VAL_11]], %[[VAL_12]] : !fir.ref<!fir.array<10xi32>>, i64, i64, i64
! FIRDialect:         }

