! NOTE: Assertions have been autogenerated by /home/rpenacob/llvm-mono/mlir/utils/generate-test-checks.py
! RUN: flang-new -fc1 -emit-fir -fompss-2 -o - %s -flang-deprecated-no-hlfir | FileCheck %s

! Based on Lower/call-by-value.f90

program call_by_value
  interface
     !$OSS TASK
     subroutine omp_set_nested(enable) bind(c)
       logical, value :: enable
     end subroutine omp_set_nested
  end interface

  logical do_nested
  do_nested = .FALSE.
  call omp_set_nested(do_nested)
end program call_by_value

! CHECK-LABEL:   func.func @_QQmain() attributes {fir.bindc_name = "CALL_BY_VALUE"} {
! CHECK:           %[[VAL_0:[-0-9A-Za-z._]+]] = fir.alloca !fir.logical<4> {bindc_name = "do_nested", uniq_name = "_QFEdo_nested"}
! CHECK:           %[[VAL_1:[-0-9A-Za-z._]+]] = arith.constant false
! CHECK:           %[[VAL_2:[-0-9A-Za-z._]+]] = fir.convert %[[VAL_1]] : (i1) -> !fir.logical<4>
! CHECK:           fir.store %[[VAL_2]] to %[[VAL_0]] : !fir.ref<!fir.logical<4>>
! CHECK:           %[[VAL_3:[-0-9A-Za-z._]+]] = fir.load %[[VAL_0]] : !fir.ref<!fir.logical<4>>
! CHECK:           oss.task captures(%[[VAL_3]] : !fir.logical<4>) {
! CHECK:             fir.call @_QPomp_set_nested(%[[VAL_3]]) fastmath<contract> : (!fir.logical<4>) -> ()
! CHECK:             oss.terminator
! CHECK:           }
! CHECK:           return
! CHECK:         }
! CHECK:         func.func private @_QPomp_set_nested(!fir.logical<4>)

