! NOTE: Assertions have been autogenerated by /home/rpenacob/llvm-mono/mlir/utils/generate-test-checks.py
! RUN: flang-new -fc1 -emit-fir -fompss-2 -o - %s -flang-deprecated-no-hlfir | FileCheck %s

! Based on Lower/dummy-argument-assumed-shape-optional.f90

module tests
interface
  !$OSS TASK
  subroutine takes_contiguous(a)
    real, contiguous :: a(:)
  end subroutine
end interface

contains

! -----------------------------------------------------------------------------
!     Test passing assumed shapes to contiguous assumed shapes
! -----------------------------------------------------------------------------
! Base case.

subroutine test_assumed_shape_to_contiguous(x)
  real :: x(:)
  call takes_contiguous(x)
end subroutine

end module




! CHECK-LABEL:   func.func @_QMtestsPtest_assumed_shape_to_contiguous(
! CHECK-SAME:      %[[ARG0:[-0-9A-Za-z._]+]]: !fir.box<!fir.array<?xf32>> {fir.bindc_name = "x"}) {
! CHECK:           %[[VAL_0:[-0-9A-Za-z._]+]] = fir.alloca !fir.box<!fir.array<?xf32>>
! CHECK:           %[[VAL_1:[-0-9A-Za-z._]+]] = fir.convert %[[ARG0]] : (!fir.box<!fir.array<?xf32>>) -> !fir.box<none>
! CHECK:           %[[VAL_2:[-0-9A-Za-z._]+]] = fir.call @_FortranAIsContiguous(%[[VAL_1]]) fastmath<contract> : (!fir.box<none>) -> i1
! CHECK:           %[[VAL_3:[-0-9A-Za-z._]+]] = fir.if %[[VAL_2]] -> (!fir.heap<!fir.array<?xf32>>) {
! CHECK:             %[[VAL_4:[-0-9A-Za-z._]+]] = fir.box_addr %[[ARG0]] : (!fir.box<!fir.array<?xf32>>) -> !fir.heap<!fir.array<?xf32>>
! CHECK:             fir.result %[[VAL_4]] : !fir.heap<!fir.array<?xf32>>
! CHECK:           } else {
! CHECK:             %[[VAL_5:[-0-9A-Za-z._]+]] = arith.constant 0 : index
! CHECK:             %[[VAL_6:[-0-9A-Za-z._]+]]:3 = fir.box_dims %[[ARG0]], %[[VAL_5]] : (!fir.box<!fir.array<?xf32>>, index) -> (index, index, index)
! CHECK:             %[[VAL_7:[-0-9A-Za-z._]+]] = fir.allocmem !fir.array<?xf32>, %[[VAL_6]]#1 {uniq_name = ".copyinout"}
! CHECK:             %[[VAL_8:[-0-9A-Za-z._]+]] = fir.shape %[[VAL_6]]#1 : (index) -> !fir.shape<1>
! CHECK:             %[[VAL_9:[-0-9A-Za-z._]+]] = fir.embox %[[VAL_7]](%[[VAL_8]]) : (!fir.heap<!fir.array<?xf32>>, !fir.shape<1>) -> !fir.box<!fir.array<?xf32>>
! CHECK:             fir.store %[[VAL_9]] to %[[VAL_0]] : !fir.ref<!fir.box<!fir.array<?xf32>>>
! CHECK:             %[[VAL_10:[-0-9A-Za-z._]+]] = fir.address_of(@_QQ{{.*}})
! CHECK:             %[[VAL_11:[-0-9A-Za-z._]+]] = arith.constant 23 : i32
! CHECK:             %[[VAL_12:[-0-9A-Za-z._]+]] = fir.convert %[[VAL_0]] : (!fir.ref<!fir.box<!fir.array<?xf32>>>) -> !fir.ref<!fir.box<none>>
! CHECK:             %[[VAL_13:[-0-9A-Za-z._]+]] = fir.convert %[[ARG0]] : (!fir.box<!fir.array<?xf32>>) -> !fir.box<none>
! CHECK:             %[[VAL_14:[-0-9A-Za-z._]+]] = fir.convert %[[VAL_10]]
! CHECK:             fir.call @_FortranAAssignTemporary(%[[VAL_12]], %[[VAL_13]], %[[VAL_14]], %[[VAL_11]]) fastmath<contract> : (!fir.ref<!fir.box<none>>, !fir.box<none>, !fir.ref<i8>, i32) -> ()
! CHECK:             fir.result %[[VAL_7]] : !fir.heap<!fir.array<?xf32>>
! CHECK:           }
! CHECK:           %[[VAL_15:[-0-9A-Za-z._]+]] = arith.constant 0 : index
! CHECK:           %[[VAL_16:[-0-9A-Za-z._]+]]:3 = fir.box_dims %[[ARG0]], %[[VAL_15]] : (!fir.box<!fir.array<?xf32>>, index) -> (index, index, index)
! CHECK:           %[[VAL_17:[-0-9A-Za-z._]+]] = arith.constant false
! CHECK:           %[[VAL_18:[-0-9A-Za-z._]+]] = arith.cmpi eq, %[[VAL_2]], %[[VAL_17]] : i1
! CHECK:           %[[VAL_19:[-0-9A-Za-z._]+]] = fir.shape %[[VAL_16]]#1 : (index) -> !fir.shape<1>
! CHECK:           %[[VAL_20:[-0-9A-Za-z._]+]] = fir.embox %[[VAL_3]](%[[VAL_19]]) : (!fir.heap<!fir.array<?xf32>>, !fir.shape<1>) -> !fir.box<!fir.array<?xf32>>
! CHECK:           %[[VAL_21:[-0-9A-Za-z._]+]] = fir.undefined !fir.oss<!fir.heap<!fir.array<?xf32>>>
! CHECK:           %[[VAL_22:[-0-9A-Za-z._]+]] = fir.undefined !fir.oss<!fir.box<!fir.array<?xf32>>>
! CHECK:           %[[VAL_23:[-0-9A-Za-z._]+]] = fir.undefined !fir.oss<!fir.box<!fir.array<?xf32>>>
! CHECK:           oss.task firstprivate(%[[VAL_20]], %[[ARG0]] : !fir.box<!fir.array<?xf32>>, !fir.box<!fir.array<?xf32>>) firstprivate_type(%[[VAL_22]], %[[VAL_23]] : !fir.oss<!fir.box<!fir.array<?xf32>>>, !fir.oss<!fir.box<!fir.array<?xf32>>>) shared(%[[VAL_3]] : !fir.heap<!fir.array<?xf32>>) shared_type(%[[VAL_21]] : !fir.oss<!fir.heap<!fir.array<?xf32>>>) captures(%[[VAL_16]]#1, %[[VAL_18]] : index, i1) {
! CHECK:             %[[VAL_24:[-0-9A-Za-z._]+]] = fir.alloca !fir.box<!fir.array<?xf32>> {pinned}
! CHECK:             %[[VAL_25:[-0-9A-Za-z._]+]] = fir.alloca !fir.box<!fir.heap<!fir.array<?xf32>>> {pinned}
! CHECK:             fir.call @_QPtakes_contiguous(%[[VAL_20]]) fastmath<contract> : (!fir.box<!fir.array<?xf32>>) -> ()
! CHECK:             fir.if %[[VAL_18]] {
! CHECK:               %[[VAL_26:[-0-9A-Za-z._]+]] = fir.shape %[[VAL_16]]#1 : (index) -> !fir.shape<1>
! CHECK:               %[[VAL_27:[-0-9A-Za-z._]+]] = fir.embox %[[VAL_3]](%[[VAL_26]]) : (!fir.heap<!fir.array<?xf32>>, !fir.shape<1>) -> !fir.box<!fir.array<?xf32>>
! CHECK:               %[[VAL_28:[-0-9A-Za-z._]+]] = fir.rebox %[[VAL_27]] : (!fir.box<!fir.array<?xf32>>) -> !fir.box<!fir.heap<!fir.array<?xf32>>>
! CHECK:               fir.store %[[VAL_28]] to %[[VAL_25]] : !fir.ref<!fir.box<!fir.heap<!fir.array<?xf32>>>>
! CHECK:               fir.store %[[ARG0]] to %[[VAL_24]] : !fir.ref<!fir.box<!fir.array<?xf32>>>
! CHECK:               %[[VAL_29:[-0-9A-Za-z._]+]] = fir.address_of(@_QQ{{.*}})
! CHECK:               %[[VAL_30:[-0-9A-Za-z._]+]] = arith.constant 23 : i32
! CHECK:               %[[VAL_31:[-0-9A-Za-z._]+]] = fir.convert %[[VAL_24]] : (!fir.ref<!fir.box<!fir.array<?xf32>>>) -> !fir.ref<!fir.box<none>>
! CHECK:               %[[VAL_32:[-0-9A-Za-z._]+]] = fir.convert %[[VAL_25]] : (!fir.ref<!fir.box<!fir.heap<!fir.array<?xf32>>>>) -> !fir.ref<!fir.box<none>>
! CHECK:               %[[VAL_33:[-0-9A-Za-z._]+]] = fir.convert %[[VAL_29]]
! CHECK:               fir.call @_FortranACopyOutAssign(%[[VAL_31]], %[[VAL_32]], %[[VAL_33]], %[[VAL_30]]) fastmath<contract> : (!fir.ref<!fir.box<none>>, !fir.ref<!fir.box<none>>, !fir.ref<i8>, i32) -> ()
! CHECK:             }
! CHECK:             oss.terminator
! CHECK:           }
! CHECK:           return
! CHECK:         }
