; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --include-generated-funcs
; RUN: opt %s -passes=ompss-2 -S | FileCheck %s
; ModuleID = 'assert.ll'
source_filename = "assert.ll"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

; #pragma oss assert("a == b")
; #pragma oss assert("a == c")
; #pragma oss assert("a == d")
; int main() {
; }

; Function Attrs: noinline nounwind optnone
define dso_local i32 @main() #0 !dbg !10 {
entry:
  ret i32 0, !dbg !14
}

attributes #0 = { noinline nounwind optnone "frame-pointer"="none" "min-legal-vector-width"="0" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-features"="+cx8,+mmx,+sse,+sse2,+x87" }

!llvm.dbg.cu = !{!0}
!llvm.module.flags = !{!2, !3, !4}
!llvm.ident = !{!9}

!0 = distinct !DICompileUnit(language: DW_LANG_C99, file: !1, producer: "", isOptimized: false, runtimeVersion: 0, emissionKind: NoDebug, splitDebugInlining: false, nameTableKind: None)
!1 = !DIFile(filename: "<stdin>", directory: "")
!2 = !{i32 2, !"Debug Info Version", i32 3}
!3 = !{i32 1, !"wchar_size", i32 4}
!4 = !{i32 1, !"OmpSs-2 Metadata", !5}
!5 = !{!6, !7, !8}
!6 = !{!"assert", !"a == b"}
!7 = !{!"assert", !"a == c"}
!8 = !{!"assert", !"a == d"}
!9 = !{!""}
!10 = distinct !DISubprogram(name: "main", scope: !11, file: !11, line: 4, type: !12, scopeLine: 4, spFlags: DISPFlagDefinition, unit: !0, retainedNodes: !13)
!11 = !DIFile(filename: "assert.ll", directory: "")
!12 = !DISubroutineType(types: !13)
!13 = !{}
!14 = !DILocation(line: 5, column: 1, scope: !10)
; CHECK-LABEL: @main(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    ret i32 0, !dbg [[DBG14:![0-9]+]]
;
;
; CHECK-LABEL: @nanos6_constructor_check_version(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    call void @nanos6_check_version(i64 1, ptr @nanos6_versions, ptr @[[GLOB0:[0-9]+]])
; CHECK-NEXT:    ret void
;
;
; CHECK-LABEL: @nanos6_constructor_register_assert(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    call void @nanos6_config_assert(ptr @[[GLOB1:[0-9]+]])
; CHECK-NEXT:    call void @nanos6_config_assert(ptr @[[GLOB2:[0-9]+]])
; CHECK-NEXT:    call void @nanos6_config_assert(ptr @[[GLOB3:[0-9]+]])
; CHECK-NEXT:    ret void
;
