; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --function-signature --include-generated-funcs
; RUN: opt %s -passes=ompss-2 -S | FileCheck %s
; ModuleID = 'collapse_iter_dep.ll'
source_filename = "collapse_iter_dep.ll"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

; Check we build skip unwanted iterations when doing a estimation of
; the number of iterations

; int main() {
;     #pragma oss taskloop collapse(2)
;     for (int i = 0; i < 10; ++i) {
;         for (int j = 0; j < i; ++j) {
;         }
;     }
; }

; Function Attrs: noinline nounwind optnone
define dso_local i32 @main() #0 !dbg !5 {
entry:
  %i = alloca i32, align 4
  %j = alloca i32, align 4
  store i32 0, ptr %i, align 4, !dbg !9
  store i32 0, ptr %j, align 4, !dbg !10
  %0 = call token @llvm.directive.region.entry() [ "DIR.OSS"([9 x i8] c"TASKLOOP\00"), "QUAL.OSS.PRIVATE"(ptr %i, i32 undef), "QUAL.OSS.PRIVATE"(ptr %j, i32 undef), "QUAL.OSS.LOOP.IND.VAR"(ptr %i, ptr %j), "QUAL.OSS.LOOP.LOWER.BOUND"(ptr @compute_lb, ptr @compute_lb.1), "QUAL.OSS.LOOP.UPPER.BOUND"(ptr @compute_ub, ptr @compute_ub.2, ptr %i), "QUAL.OSS.LOOP.STEP"(ptr @compute_step, ptr @compute_step.3), "QUAL.OSS.LOOP.TYPE"(i64 0, i64 1, i64 1, i64 1, i64 1, i64 0, i64 1, i64 1, i64 1, i64 1) ], !dbg !11
  call void @llvm.directive.region.exit(token %0), !dbg !12
  ret i32 0, !dbg !13
}

; Function Attrs: nounwind
declare token @llvm.directive.region.entry() #1

; Function Attrs: nounwind
declare void @llvm.directive.region.exit(token) #1

define internal i32 @compute_lb() #2 !dbg !14 {
entry:
  ret i32 0, !dbg !15
}

define internal i32 @compute_ub() #2 !dbg !17 {
entry:
  ret i32 10, !dbg !18
}

define internal i32 @compute_step() #2 !dbg !20 {
entry:
  ret i32 1, !dbg !21
}

define internal i32 @compute_lb.1() #2 !dbg !23 {
entry:
  ret i32 0, !dbg !24
}

define internal i32 @compute_ub.2(ptr %i) #2 !dbg !26 {
entry:
  %i.addr = alloca ptr, align 8
  store ptr %i, ptr %i.addr, align 8
  %0 = load i32, ptr %i, align 4, !dbg !27
  ret i32 %0, !dbg !27
}

define internal i32 @compute_step.3() #2 !dbg !29 {
entry:
  ret i32 1, !dbg !30
}

attributes #0 = { noinline nounwind optnone "frame-pointer"="none" "min-legal-vector-width"="0" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-features"="+cx8,+mmx,+sse,+sse2,+x87" }
attributes #1 = { nounwind }
attributes #2 = { "min-legal-vector-width"="0" }

!llvm.dbg.cu = !{!0}
!llvm.module.flags = !{!2, !3}
!llvm.ident = !{!4}

!0 = distinct !DICompileUnit(language: DW_LANG_C99, file: !1, producer: "", isOptimized: false, runtimeVersion: 0, emissionKind: NoDebug, splitDebugInlining: false, nameTableKind: None)
!1 = !DIFile(filename: "<stdin>", directory: "")
!2 = !{i32 2, !"Debug Info Version", i32 3}
!3 = !{i32 1, !"wchar_size", i32 4}
!4 = !{!""}
!5 = distinct !DISubprogram(name: "main", scope: !6, file: !6, line: 1, type: !7, scopeLine: 1, spFlags: DISPFlagDefinition, unit: !0, retainedNodes: !8)
!6 = !DIFile(filename: "collapse_iter_dep.ll", directory: "")
!7 = !DISubroutineType(types: !8)
!8 = !{}
!9 = !DILocation(line: 3, column: 14, scope: !5)
!10 = !DILocation(line: 4, column: 18, scope: !5)
!11 = !DILocation(line: 4, column: 14, scope: !5)
!12 = !DILocation(line: 5, column: 9, scope: !5)
!13 = !DILocation(line: 7, column: 1, scope: !5)
!14 = distinct !DISubprogram(linkageName: "compute_lb", scope: !1, file: !1, type: !7, flags: DIFlagArtificial, spFlags: DISPFlagLocalToUnit | DISPFlagDefinition, unit: !0, retainedNodes: !8)
!15 = !DILocation(line: 3, column: 18, scope: !16)
!16 = !DILexicalBlockFile(scope: !14, file: !6, discriminator: 0)
!17 = distinct !DISubprogram(linkageName: "compute_ub", scope: !1, file: !1, type: !7, flags: DIFlagArtificial, spFlags: DISPFlagLocalToUnit | DISPFlagDefinition, unit: !0, retainedNodes: !8)
!18 = !DILocation(line: 3, column: 25, scope: !19)
!19 = !DILexicalBlockFile(scope: !17, file: !6, discriminator: 0)
!20 = distinct !DISubprogram(linkageName: "compute_step", scope: !1, file: !1, type: !7, flags: DIFlagArtificial, spFlags: DISPFlagLocalToUnit | DISPFlagDefinition, unit: !0, retainedNodes: !8)
!21 = !DILocation(line: 3, column: 29, scope: !22)
!22 = !DILexicalBlockFile(scope: !20, file: !6, discriminator: 0)
!23 = distinct !DISubprogram(linkageName: "compute_lb.1", scope: !1, file: !1, type: !7, flags: DIFlagArtificial, spFlags: DISPFlagLocalToUnit | DISPFlagDefinition, unit: !0, retainedNodes: !8)
!24 = !DILocation(line: 4, column: 22, scope: !25)
!25 = !DILexicalBlockFile(scope: !23, file: !6, discriminator: 0)
!26 = distinct !DISubprogram(linkageName: "compute_ub.2", scope: !1, file: !1, type: !7, flags: DIFlagArtificial, spFlags: DISPFlagLocalToUnit | DISPFlagDefinition, unit: !0, retainedNodes: !8)
!27 = !DILocation(line: 4, column: 29, scope: !28)
!28 = !DILexicalBlockFile(scope: !26, file: !6, discriminator: 0)
!29 = distinct !DISubprogram(linkageName: "compute_step.3", scope: !1, file: !1, type: !7, flags: DIFlagArtificial, spFlags: DISPFlagLocalToUnit | DISPFlagDefinition, unit: !0, retainedNodes: !8)
!30 = !DILocation(line: 4, column: 32, scope: !31)
!31 = !DILexicalBlockFile(scope: !29, file: !6, discriminator: 0)
; CHECK-LABEL: define {{[^@]+}}@main
; CHECK-SAME: () #[[ATTR0:[0-9]+]] !dbg [[DBG5:![0-9]+]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[NUM_DEPS:%.*]] = alloca i64, align 8, !dbg [[DBG9:![0-9]+]]
; CHECK-NEXT:    [[TMP0:%.*]] = alloca ptr, align 8, !dbg [[DBG9]]
; CHECK-NEXT:    [[TMP1:%.*]] = alloca ptr, align 8, !dbg [[DBG9]]
; CHECK-NEXT:    [[I:%.*]] = alloca i32, align 4
; CHECK-NEXT:    [[J:%.*]] = alloca i32, align 4
; CHECK-NEXT:    store i32 0, ptr [[I]], align 4, !dbg [[DBG10:![0-9]+]]
; CHECK-NEXT:    store i32 0, ptr [[J]], align 4, !dbg [[DBG11:![0-9]+]]
; CHECK-NEXT:    br label [[FINAL_COND:%.*]], !dbg [[DBG9]]
; CHECK:       codeRepl:
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr [[TMP1]]), !dbg [[DBG9]]
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr [[TMP0]]), !dbg [[DBG9]]
; CHECK-NEXT:    store i64 0, ptr [[NUM_DEPS]], align 8, !dbg [[DBG9]]
; CHECK-NEXT:    [[TMP2:%.*]] = load i64, ptr [[NUM_DEPS]], align 8, !dbg [[DBG9]]
; CHECK-NEXT:    [[TMP3:%.*]] = call i32 @compute_lb(), !dbg [[DBG9]]
; CHECK-NEXT:    [[TMP4:%.*]] = call i32 @compute_ub(), !dbg [[DBG9]]
; CHECK-NEXT:    [[TMP5:%.*]] = call i32 @compute_step(), !dbg [[DBG9]]
; CHECK-NEXT:    [[TMP6:%.*]] = sub i32 [[TMP4]], [[TMP3]], !dbg [[DBG9]]
; CHECK-NEXT:    [[TMP7:%.*]] = sub i32 [[TMP6]], 1, !dbg [[DBG9]]
; CHECK-NEXT:    [[TMP8:%.*]] = sdiv i32 [[TMP7]], [[TMP5]], !dbg [[DBG9]]
; CHECK-NEXT:    [[TMP9:%.*]] = add i32 [[TMP8]], 1, !dbg [[DBG9]]
; CHECK-NEXT:    [[TMP10:%.*]] = sext i32 [[TMP9]] to i64, !dbg [[DBG9]]
; CHECK-NEXT:    [[TMP11:%.*]] = sub i32 [[TMP4]], 1, !dbg [[DBG9]]
; CHECK-NEXT:    store i32 [[TMP3]], ptr [[I]], align 4, !dbg [[DBG9]]
; CHECK-NEXT:    [[TMP12:%.*]] = call i32 @compute_lb.1(), !dbg [[DBG9]]
; CHECK-NEXT:    store i32 [[TMP11]], ptr [[I]], align 4, !dbg [[DBG9]]
; CHECK-NEXT:    [[TMP13:%.*]] = call i32 @compute_ub.2(ptr [[I]]), !dbg [[DBG9]]
; CHECK-NEXT:    [[TMP14:%.*]] = call i32 @compute_step.3(), !dbg [[DBG9]]
; CHECK-NEXT:    [[TMP15:%.*]] = sub i32 [[TMP13]], [[TMP12]], !dbg [[DBG9]]
; CHECK-NEXT:    [[TMP16:%.*]] = sub i32 [[TMP15]], 1, !dbg [[DBG9]]
; CHECK-NEXT:    [[TMP17:%.*]] = sdiv i32 [[TMP16]], [[TMP14]], !dbg [[DBG9]]
; CHECK-NEXT:    [[TMP18:%.*]] = add i32 [[TMP17]], 1, !dbg [[DBG9]]
; CHECK-NEXT:    [[TMP19:%.*]] = sext i32 [[TMP18]] to i64, !dbg [[DBG9]]
; CHECK-NEXT:    [[TMP20:%.*]] = mul i64 1, [[TMP10]], !dbg [[DBG9]]
; CHECK-NEXT:    [[TMP21:%.*]] = mul i64 [[TMP20]], [[TMP19]], !dbg [[DBG9]]
; CHECK-NEXT:    call void @nanos6_create_loop(ptr @task_info_var_main, ptr @task_invocation_info_main, ptr null, i64 16, ptr [[TMP1]], ptr [[TMP0]], i64 4, i64 [[TMP2]], i64 0, i64 [[TMP21]], i64 0, i64 0), !dbg [[DBG9]]
; CHECK-NEXT:    [[TMP22:%.*]] = load ptr, ptr [[TMP1]], align 8, !dbg [[DBG9]]
; CHECK-NEXT:    [[ARGS_END:%.*]] = getelementptr i8, ptr [[TMP22]], i64 16, !dbg [[DBG9]]
; CHECK-NEXT:    [[TMP23:%.*]] = load ptr, ptr [[TMP0]], align 8, !dbg [[DBG9]]
; CHECK-NEXT:    call void @nanos6_submit_task(ptr [[TMP23]]), !dbg [[DBG9]]
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr [[TMP1]]), !dbg [[DBG9]]
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr [[TMP0]]), !dbg [[DBG9]]
; CHECK-NEXT:    br label [[FOR_END7:%.*]], !dbg [[DBG9]]
; CHECK:       final.end:
; CHECK-NEXT:    ret i32 0, !dbg [[DBG12:![0-9]+]]
; CHECK:       final.then:
; CHECK-NEXT:    [[TMP24:%.*]] = call i32 @compute_lb(), !dbg [[DBG9]]
; CHECK-NEXT:    [[TMP25:%.*]] = call i32 @compute_ub(), !dbg [[DBG9]]
; CHECK-NEXT:    [[TMP26:%.*]] = call i32 @compute_step(), !dbg [[DBG9]]
; CHECK-NEXT:    store i32 [[TMP24]], ptr [[I]], align 4, !dbg [[DBG9]]
; CHECK-NEXT:    br label [[FOR_COND1:%.*]], !dbg [[DBG9]]
; CHECK:       for.cond1:
; CHECK-NEXT:    [[TMP27:%.*]] = load i32, ptr [[I]], align 4, !dbg [[DBG9]]
; CHECK-NEXT:    [[TMP28:%.*]] = icmp slt i32 [[TMP27]], [[TMP25]], !dbg [[DBG9]]
; CHECK-NEXT:    br i1 [[TMP28]], label [[TMP29:%.*]], label [[FOR_END3:%.*]], !dbg [[DBG9]]
; CHECK:       29:
; CHECK-NEXT:    br label [[TMP30:%.*]], !dbg [[DBG9]]
; CHECK:       30:
; CHECK-NEXT:    br label [[FOR_BODY2:%.*]], !dbg [[DBG9]]
; CHECK:       for.body2:
; CHECK-NEXT:    [[TMP31:%.*]] = call i32 @compute_lb.1(), !dbg [[DBG9]]
; CHECK-NEXT:    [[TMP32:%.*]] = call i32 @compute_ub.2(ptr [[I]]), !dbg [[DBG9]]
; CHECK-NEXT:    [[TMP33:%.*]] = call i32 @compute_step.3(), !dbg [[DBG9]]
; CHECK-NEXT:    store i32 [[TMP31]], ptr [[J]], align 4, !dbg [[DBG9]]
; CHECK-NEXT:    br label [[FOR_COND:%.*]], !dbg [[DBG9]]
; CHECK:       for.cond:
; CHECK-NEXT:    [[TMP34:%.*]] = load i32, ptr [[J]], align 4, !dbg [[DBG9]]
; CHECK-NEXT:    [[TMP35:%.*]] = icmp slt i32 [[TMP34]], [[TMP32]], !dbg [[DBG9]]
; CHECK-NEXT:    br i1 [[TMP35]], label [[TMP36:%.*]], label [[FOR_END:%.*]], !dbg [[DBG9]]
; CHECK:       36:
; CHECK-NEXT:    br label [[TMP37:%.*]], !dbg [[DBG9]]
; CHECK:       37:
; CHECK-NEXT:    br label [[FOR_BODY:%.*]], !dbg [[DBG9]]
; CHECK:       for.body:
; CHECK-NEXT:    br label [[FOR_INCR:%.*]], !dbg [[DBG12]]
; CHECK:       for.end:
; CHECK-NEXT:    br label [[FOR_INCR4:%.*]], !dbg [[DBG9]]
; CHECK:       for.incr:
; CHECK-NEXT:    [[TMP38:%.*]] = load i32, ptr [[J]], align 4, !dbg [[DBG9]]
; CHECK-NEXT:    [[TMP39:%.*]] = add i32 [[TMP38]], [[TMP33]], !dbg [[DBG9]]
; CHECK-NEXT:    store i32 [[TMP39]], ptr [[J]], align 4, !dbg [[DBG9]]
; CHECK-NEXT:    br label [[FOR_COND]], !dbg [[DBG9]]
; CHECK:       for.end3:
; CHECK-NEXT:    br label [[FINAL_END:%.*]], !dbg [[DBG9]]
; CHECK:       for.incr4:
; CHECK-NEXT:    [[TMP40:%.*]] = load i32, ptr [[I]], align 4, !dbg [[DBG9]]
; CHECK-NEXT:    [[TMP41:%.*]] = add i32 [[TMP40]], [[TMP26]], !dbg [[DBG9]]
; CHECK-NEXT:    store i32 [[TMP41]], ptr [[I]], align 4, !dbg [[DBG9]]
; CHECK-NEXT:    br label [[FOR_COND1]], !dbg [[DBG9]]
; CHECK:       final.cond:
; CHECK-NEXT:    [[TMP42:%.*]] = call i32 @nanos6_in_final(), !dbg [[DBG9]]
; CHECK-NEXT:    [[TMP43:%.*]] = icmp ne i32 [[TMP42]], 0, !dbg [[DBG9]]
; CHECK-NEXT:    br i1 [[TMP43]], label [[FINAL_THEN:%.*]], label [[CODEREPL:%.*]], !dbg [[DBG9]]
; CHECK:       for.end7:
; CHECK-NEXT:    br label [[FINAL_END]], !dbg [[DBG9]]
;
;
; CHECK-LABEL: define {{[^@]+}}@compute_lb
; CHECK-SAME: () #[[ATTR2:[0-9]+]] !dbg [[DBG13:![0-9]+]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    ret i32 0, !dbg [[DBG14:![0-9]+]]
;
;
; CHECK-LABEL: define {{[^@]+}}@compute_ub
; CHECK-SAME: () #[[ATTR2]] !dbg [[DBG16:![0-9]+]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    ret i32 10, !dbg [[DBG17:![0-9]+]]
;
;
; CHECK-LABEL: define {{[^@]+}}@compute_step
; CHECK-SAME: () #[[ATTR2]] !dbg [[DBG19:![0-9]+]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    ret i32 1, !dbg [[DBG20:![0-9]+]]
;
;
; CHECK-LABEL: define {{[^@]+}}@compute_lb.1
; CHECK-SAME: () #[[ATTR2]] !dbg [[DBG22:![0-9]+]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    ret i32 0, !dbg [[DBG23:![0-9]+]]
;
;
; CHECK-LABEL: define {{[^@]+}}@compute_ub.2
; CHECK-SAME: (ptr [[I:%.*]]) #[[ATTR2]] !dbg [[DBG25:![0-9]+]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[I_ADDR:%.*]] = alloca ptr, align 8
; CHECK-NEXT:    store ptr [[I]], ptr [[I_ADDR]], align 8
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[I]], align 4, !dbg [[DBG26:![0-9]+]]
; CHECK-NEXT:    ret i32 [[TMP0]], !dbg [[DBG26]]
;
;
; CHECK-LABEL: define {{[^@]+}}@compute_step.3
; CHECK-SAME: () #[[ATTR2]] !dbg [[DBG28:![0-9]+]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    ret i32 1, !dbg [[DBG29:![0-9]+]]
;
;
; CHECK-LABEL: define {{[^@]+}}@nanos6_constructor_check_version() {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    call void @nanos6_check_version(i64 1, ptr @nanos6_versions, ptr @[[GLOB0:[0-9]+]])
; CHECK-NEXT:    ret void
;
;
; CHECK-LABEL: define {{[^@]+}}@nanos6_unpacked_task_region_main
; CHECK-SAME: (ptr [[I:%.*]], ptr [[J:%.*]], ptr [[LOOP_BOUNDS:%.*]], ptr [[ADDRESS_TRANSLATION_TABLE:%.*]]) #[[ATTR0]] !dbg [[DBG31:![0-9]+]] {
; CHECK-NEXT:  newFuncRoot:
; CHECK-NEXT:    [[LB_GEP:%.*]] = getelementptr [[NANOS6_LOOP_BOUNDS_T:%.*]], ptr [[LOOP_BOUNDS]], i32 0, i32 0, !dbg [[DBG32:![0-9]+]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i64, ptr [[LB_GEP]], align 8, !dbg [[DBG32]]
; CHECK-NEXT:    [[UB_GEP:%.*]] = getelementptr [[NANOS6_LOOP_BOUNDS_T]], ptr [[LOOP_BOUNDS]], i32 0, i32 1, !dbg [[DBG32]]
; CHECK-NEXT:    [[TMP1:%.*]] = load i64, ptr [[UB_GEP]], align 8, !dbg [[DBG32]]
; CHECK-NEXT:    br label [[TMP2:%.*]], !dbg [[DBG32]]
; CHECK:       2:
; CHECK-NEXT:    [[TMP3:%.*]] = call i32 @compute_lb(), !dbg [[DBG32]]
; CHECK-NEXT:    [[TMP4:%.*]] = call i32 @compute_ub(), !dbg [[DBG32]]
; CHECK-NEXT:    [[TMP5:%.*]] = call i32 @compute_step(), !dbg [[DBG32]]
; CHECK-NEXT:    [[TMP6:%.*]] = sub i32 [[TMP4]], [[TMP3]], !dbg [[DBG32]]
; CHECK-NEXT:    [[TMP7:%.*]] = sub i32 [[TMP6]], 1, !dbg [[DBG32]]
; CHECK-NEXT:    [[TMP8:%.*]] = sdiv i32 [[TMP7]], [[TMP5]], !dbg [[DBG32]]
; CHECK-NEXT:    [[TMP9:%.*]] = add i32 [[TMP8]], 1, !dbg [[DBG32]]
; CHECK-NEXT:    [[TMP10:%.*]] = sext i32 [[TMP9]] to i64, !dbg [[DBG32]]
; CHECK-NEXT:    [[TMP11:%.*]] = sub i32 [[TMP4]], 1, !dbg [[DBG32]]
; CHECK-NEXT:    store i32 [[TMP3]], ptr [[I]], align 4, !dbg [[DBG32]]
; CHECK-NEXT:    [[TMP12:%.*]] = call i32 @compute_lb.1(), !dbg [[DBG32]]
; CHECK-NEXT:    store i32 [[TMP11]], ptr [[I]], align 4, !dbg [[DBG32]]
; CHECK-NEXT:    [[TMP13:%.*]] = call i32 @compute_ub.2(ptr [[I]]), !dbg [[DBG32]]
; CHECK-NEXT:    [[TMP14:%.*]] = call i32 @compute_step.3(), !dbg [[DBG32]]
; CHECK-NEXT:    [[TMP15:%.*]] = sub i32 [[TMP13]], [[TMP12]], !dbg [[DBG32]]
; CHECK-NEXT:    [[TMP16:%.*]] = sub i32 [[TMP15]], 1, !dbg [[DBG32]]
; CHECK-NEXT:    [[TMP17:%.*]] = sdiv i32 [[TMP16]], [[TMP14]], !dbg [[DBG32]]
; CHECK-NEXT:    [[TMP18:%.*]] = add i32 [[TMP17]], 1, !dbg [[DBG32]]
; CHECK-NEXT:    [[TMP19:%.*]] = sext i32 [[TMP18]] to i64, !dbg [[DBG32]]
; CHECK-NEXT:    [[TMP20:%.*]] = sext i32 [[TMP3]] to i64, !dbg [[DBG32]]
; CHECK-NEXT:    [[TMP21:%.*]] = sext i32 [[TMP4]] to i64, !dbg [[DBG32]]
; CHECK-NEXT:    [[LOOP:%.*]] = alloca i64, align 8, !dbg [[DBG32]]
; CHECK-NEXT:    store i64 [[TMP0]], ptr [[LOOP]], align 8, !dbg [[DBG32]]
; CHECK-NEXT:    br label [[FOR_COND5:%.*]], !dbg [[DBG32]]
; CHECK:       for.cond5:
; CHECK-NEXT:    [[TMP22:%.*]] = load i64, ptr [[LOOP]], align 8, !dbg [[DBG32]]
; CHECK-NEXT:    [[TMP23:%.*]] = icmp ult i64 [[TMP22]], [[TMP1]], !dbg [[DBG32]]
; CHECK-NEXT:    br i1 [[TMP23]], label [[TMP24:%.*]], label [[FOR_END7_EXITSTUB:%.*]], !dbg [[DBG32]]
; CHECK:       24:
; CHECK-NEXT:    [[TMP25:%.*]] = load i64, ptr [[LOOP]], align 8, !dbg [[DBG32]]
; CHECK-NEXT:    [[TMP26:%.*]] = mul i64 1, [[TMP19]], !dbg [[DBG32]]
; CHECK-NEXT:    [[TMP27:%.*]] = udiv i64 [[TMP25]], [[TMP26]], !dbg [[DBG32]]
; CHECK-NEXT:    [[TMP28:%.*]] = sext i32 [[TMP5]] to i64, !dbg [[DBG32]]
; CHECK-NEXT:    [[TMP29:%.*]] = mul i64 [[TMP27]], [[TMP28]], !dbg [[DBG32]]
; CHECK-NEXT:    [[TMP30:%.*]] = sext i32 [[TMP3]] to i64, !dbg [[DBG32]]
; CHECK-NEXT:    [[TMP31:%.*]] = add i64 [[TMP29]], [[TMP30]], !dbg [[DBG32]]
; CHECK-NEXT:    [[TMP32:%.*]] = mul i64 [[TMP27]], [[TMP26]], !dbg [[DBG32]]
; CHECK-NEXT:    [[TMP33:%.*]] = sub i64 [[TMP25]], [[TMP32]], !dbg [[DBG32]]
; CHECK-NEXT:    [[TMP34:%.*]] = trunc i64 [[TMP31]] to i32, !dbg [[DBG32]]
; CHECK-NEXT:    store i32 [[TMP34]], ptr [[I]], align 4, !dbg [[DBG32]]
; CHECK-NEXT:    br label [[TMP35:%.*]], !dbg [[DBG32]]
; CHECK:       35:
; CHECK-NEXT:    [[TMP36:%.*]] = udiv i64 [[TMP33]], 1, !dbg [[DBG32]]
; CHECK-NEXT:    [[TMP37:%.*]] = sext i32 [[TMP14]] to i64, !dbg [[DBG32]]
; CHECK-NEXT:    [[TMP38:%.*]] = mul i64 [[TMP36]], [[TMP37]], !dbg [[DBG32]]
; CHECK-NEXT:    [[TMP39:%.*]] = sext i32 [[TMP12]] to i64, !dbg [[DBG32]]
; CHECK-NEXT:    [[TMP40:%.*]] = add i64 [[TMP38]], [[TMP39]], !dbg [[DBG32]]
; CHECK-NEXT:    [[TMP41:%.*]] = mul i64 [[TMP36]], 1, !dbg [[DBG32]]
; CHECK-NEXT:    [[TMP42:%.*]] = sub i64 [[TMP33]], [[TMP41]], !dbg [[DBG32]]
; CHECK-NEXT:    [[TMP43:%.*]] = trunc i64 [[TMP40]] to i32, !dbg [[DBG32]]
; CHECK-NEXT:    store i32 [[TMP43]], ptr [[J]], align 4, !dbg [[DBG32]]
; CHECK-NEXT:    [[TMP44:%.*]] = call i32 @compute_ub.2(ptr [[I]]), !dbg [[DBG32]]
; CHECK-NEXT:    [[TMP45:%.*]] = load i32, ptr [[J]], align 4, !dbg [[DBG32]]
; CHECK-NEXT:    [[TMP46:%.*]] = icmp slt i32 [[TMP45]], [[TMP44]], !dbg [[DBG32]]
; CHECK-NEXT:    br i1 [[TMP46]], label [[FOR_BODY6:%.*]], label [[FOR_INCR8:%.*]], !dbg [[DBG32]]
; CHECK:       for.body6:
; CHECK-NEXT:    br label [[FOR_INCR8]], !dbg [[DBG33:![0-9]+]]
; CHECK:       for.incr8:
; CHECK-NEXT:    [[TMP47:%.*]] = load i64, ptr [[LOOP]], align 8, !dbg [[DBG32]]
; CHECK-NEXT:    [[TMP48:%.*]] = add i64 [[TMP47]], 1, !dbg [[DBG32]]
; CHECK-NEXT:    store i64 [[TMP48]], ptr [[LOOP]], align 8, !dbg [[DBG32]]
; CHECK-NEXT:    br label [[FOR_COND5]], !dbg [[DBG32]]
; CHECK:       for.end7.exitStub:
; CHECK-NEXT:    ret void
;
;
; CHECK-LABEL: define {{[^@]+}}@nanos6_ol_task_region_main
; CHECK-SAME: (ptr [[TASK_ARGS:%.*]], ptr [[LOOP_BOUNDS:%.*]], ptr [[ADDRESS_TRANSLATION_TABLE:%.*]]) #[[ATTR3:[0-9]+]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[GEP_I:%.*]] = getelementptr [[NANOS6_TASK_ARGS_MAIN:%.*]], ptr [[TASK_ARGS]], i32 0, i32 0
; CHECK-NEXT:    [[GEP_J:%.*]] = getelementptr [[NANOS6_TASK_ARGS_MAIN]], ptr [[TASK_ARGS]], i32 0, i32 1
; CHECK-NEXT:    [[TMP0:%.*]] = icmp ne ptr [[ADDRESS_TRANSLATION_TABLE]], null
; CHECK-NEXT:    br i1 [[TMP0]], label [[TLATE_IF:%.*]], label [[TLATE_END:%.*]]
; CHECK:       end:
; CHECK-NEXT:    call void @nanos6_unpacked_task_region_main(ptr [[GEP_I]], ptr [[GEP_J]], ptr [[LOOP_BOUNDS]], ptr [[ADDRESS_TRANSLATION_TABLE]])
; CHECK-NEXT:    ret void
; CHECK:       tlate.if:
; CHECK-NEXT:    br label [[TLATE_END]]
; CHECK:       tlate.end:
; CHECK-NEXT:    br label [[END:%.*]]
;
;
; CHECK-LABEL: define {{[^@]+}}@nanos6_constructor_register_task_info() {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    call void @nanos6_register_task_info(ptr @task_info_var_main)
; CHECK-NEXT:    ret void
;
