; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --function-signature --include-generated-funcs
; RUN: opt %s -passes='ompss-2,default<O3>' -S | FileCheck %s
; ModuleID = 'collapse_niters01.ll'
source_filename = "collapse_niters01.ll"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

; int main() {
;     #pragma oss taskloop collapse(2)
;     for (int i = 0; i < 10; ++i) {
;         for (int j = 10; j > i; --j) {
;         }
;     }
;     #pragma oss taskloop collapse(2)
;     for (int i = 0; i < 10; ++i) {
;         for (int j = i; j > 0; --j) {
;         }
;     }
;     #pragma oss taskloop collapse(2)
;     for (int i = 0; i < 10; ++i) {
;         for (int j = 0; j < i; ++j) {
;         }
;     }
;     #pragma oss taskloop collapse(2)
;     for (int i = 0; i < 10; ++i) {
;         for (int j = i; j < 10; ++j) {
;         }
;     }
;     #pragma oss taskwait
; }

; Function Attrs: noinline nounwind uwtable
define dso_local i32 @main() #0 !dbg !7 {
entry:
  %i = alloca i32, align 4
  %j = alloca i32, align 4
  %i1 = alloca i32, align 4
  %j2 = alloca i32, align 4
  %i3 = alloca i32, align 4
  %j4 = alloca i32, align 4
  %i5 = alloca i32, align 4
  %j6 = alloca i32, align 4
  store i32 0, ptr %i, align 4, !dbg !10
  store i32 10, ptr %j, align 4, !dbg !11
  %0 = call token @llvm.directive.region.entry() [ "DIR.OSS"([9 x i8] c"TASKLOOP\00"), "QUAL.OSS.PRIVATE"(ptr %i, i32 undef), "QUAL.OSS.PRIVATE"(ptr %j, i32 undef), "QUAL.OSS.LOOP.IND.VAR"(ptr %i, ptr %j), "QUAL.OSS.LOOP.LOWER.BOUND"(ptr @compute_lb, ptr @compute_lb.1), "QUAL.OSS.LOOP.UPPER.BOUND"(ptr @compute_ub, ptr @compute_ub.2, ptr %i), "QUAL.OSS.LOOP.STEP"(ptr @compute_step, ptr @compute_step.3), "QUAL.OSS.LOOP.TYPE"(i64 0, i64 1, i64 1, i64 1, i64 1, i64 2, i64 1, i64 1, i64 1, i64 1) ], !dbg !12
  call void @llvm.directive.region.exit(token %0), !dbg !13
  store i32 0, ptr %i1, align 4, !dbg !14
  %1 = load i32, ptr %i1, align 4, !dbg !15
  store i32 %1, ptr %j2, align 4, !dbg !16
  %2 = call token @llvm.directive.region.entry() [ "DIR.OSS"([9 x i8] c"TASKLOOP\00"), "QUAL.OSS.PRIVATE"(ptr %i1, i32 undef), "QUAL.OSS.PRIVATE"(ptr %j2, i32 undef), "QUAL.OSS.LOOP.IND.VAR"(ptr %i1, ptr %j2), "QUAL.OSS.LOOP.LOWER.BOUND"(ptr @compute_lb.4, ptr @compute_lb.7, ptr %i1), "QUAL.OSS.LOOP.UPPER.BOUND"(ptr @compute_ub.5, ptr @compute_ub.8), "QUAL.OSS.LOOP.STEP"(ptr @compute_step.6, ptr @compute_step.9), "QUAL.OSS.LOOP.TYPE"(i64 0, i64 1, i64 1, i64 1, i64 1, i64 2, i64 1, i64 1, i64 1, i64 1) ], !dbg !17
  call void @llvm.directive.region.exit(token %2), !dbg !18
  store i32 0, ptr %i3, align 4, !dbg !19
  store i32 0, ptr %j4, align 4, !dbg !20
  %3 = call token @llvm.directive.region.entry() [ "DIR.OSS"([9 x i8] c"TASKLOOP\00"), "QUAL.OSS.PRIVATE"(ptr %i3, i32 undef), "QUAL.OSS.PRIVATE"(ptr %j4, i32 undef), "QUAL.OSS.LOOP.IND.VAR"(ptr %i3, ptr %j4), "QUAL.OSS.LOOP.LOWER.BOUND"(ptr @compute_lb.10, ptr @compute_lb.13), "QUAL.OSS.LOOP.UPPER.BOUND"(ptr @compute_ub.11, ptr @compute_ub.14, ptr %i3), "QUAL.OSS.LOOP.STEP"(ptr @compute_step.12, ptr @compute_step.15), "QUAL.OSS.LOOP.TYPE"(i64 0, i64 1, i64 1, i64 1, i64 1, i64 0, i64 1, i64 1, i64 1, i64 1) ], !dbg !21
  call void @llvm.directive.region.exit(token %3), !dbg !22
  store i32 0, ptr %i5, align 4, !dbg !23
  %4 = load i32, ptr %i5, align 4, !dbg !24
  store i32 %4, ptr %j6, align 4, !dbg !25
  %5 = call token @llvm.directive.region.entry() [ "DIR.OSS"([9 x i8] c"TASKLOOP\00"), "QUAL.OSS.PRIVATE"(ptr %i5, i32 undef), "QUAL.OSS.PRIVATE"(ptr %j6, i32 undef), "QUAL.OSS.LOOP.IND.VAR"(ptr %i5, ptr %j6), "QUAL.OSS.LOOP.LOWER.BOUND"(ptr @compute_lb.16, ptr @compute_lb.19, ptr %i5), "QUAL.OSS.LOOP.UPPER.BOUND"(ptr @compute_ub.17, ptr @compute_ub.20), "QUAL.OSS.LOOP.STEP"(ptr @compute_step.18, ptr @compute_step.21), "QUAL.OSS.LOOP.TYPE"(i64 0, i64 1, i64 1, i64 1, i64 1, i64 0, i64 1, i64 1, i64 1, i64 1) ], !dbg !26
  call void @llvm.directive.region.exit(token %5), !dbg !27
  %6 = call i1 @llvm.directive.marker() [ "DIR.OSS"([9 x i8] c"TASKWAIT\00") ], !dbg !28
  ret i32 0, !dbg !29
}

; Function Attrs: nounwind
declare token @llvm.directive.region.entry() #1

; Function Attrs: nounwind
declare void @llvm.directive.region.exit(token) #1

define internal i32 @compute_lb() #2 !dbg !30 {
entry:
  ret i32 0, !dbg !31
}

define internal i32 @compute_ub() #2 !dbg !32 {
entry:
  ret i32 10, !dbg !33
}

define internal i32 @compute_step() #2 !dbg !34 {
entry:
  ret i32 1, !dbg !35
}

define internal i32 @compute_lb.1() #2 !dbg !36 {
entry:
  ret i32 10, !dbg !37
}

define internal i32 @compute_ub.2(ptr %i) #2 !dbg !38 {
entry:
  %i.addr = alloca ptr, align 8
  store ptr %i, ptr %i.addr, align 8
  %0 = load i32, ptr %i, align 4, !dbg !39
  ret i32 %0, !dbg !39
}

define internal i32 @compute_step.3() #2 !dbg !40 {
entry:
  ret i32 -1, !dbg !41
}

define internal i32 @compute_lb.4() #2 !dbg !42 {
entry:
  ret i32 0, !dbg !43
}

define internal i32 @compute_ub.5() #2 !dbg !44 {
entry:
  ret i32 10, !dbg !45
}

define internal i32 @compute_step.6() #2 !dbg !46 {
entry:
  ret i32 1, !dbg !47
}

define internal i32 @compute_lb.7(ptr %i) #2 !dbg !48 {
entry:
  %i.addr = alloca ptr, align 8
  store ptr %i, ptr %i.addr, align 8
  %0 = load i32, ptr %i, align 4, !dbg !49
  ret i32 %0, !dbg !49
}

define internal i32 @compute_ub.8() #2 !dbg !50 {
entry:
  ret i32 0, !dbg !51
}

define internal i32 @compute_step.9() #2 !dbg !52 {
entry:
  ret i32 -1, !dbg !53
}

define internal i32 @compute_lb.10() #2 !dbg !54 {
entry:
  ret i32 0, !dbg !55
}

define internal i32 @compute_ub.11() #2 !dbg !56 {
entry:
  ret i32 10, !dbg !57
}

define internal i32 @compute_step.12() #2 !dbg !58 {
entry:
  ret i32 1, !dbg !59
}

define internal i32 @compute_lb.13() #2 !dbg !60 {
entry:
  ret i32 0, !dbg !61
}

define internal i32 @compute_ub.14(ptr %i) #2 !dbg !62 {
entry:
  %i.addr = alloca ptr, align 8
  store ptr %i, ptr %i.addr, align 8
  %0 = load i32, ptr %i, align 4, !dbg !63
  ret i32 %0, !dbg !63
}

define internal i32 @compute_step.15() #2 !dbg !64 {
entry:
  ret i32 1, !dbg !65
}

define internal i32 @compute_lb.16() #2 !dbg !66 {
entry:
  ret i32 0, !dbg !67
}

define internal i32 @compute_ub.17() #2 !dbg !68 {
entry:
  ret i32 10, !dbg !69
}

define internal i32 @compute_step.18() #2 !dbg !70 {
entry:
  ret i32 1, !dbg !71
}

define internal i32 @compute_lb.19(ptr %i) #2 !dbg !72 {
entry:
  %i.addr = alloca ptr, align 8
  store ptr %i, ptr %i.addr, align 8
  %0 = load i32, ptr %i, align 4, !dbg !73
  ret i32 %0, !dbg !73
}

define internal i32 @compute_ub.20() #2 !dbg !74 {
entry:
  ret i32 10, !dbg !75
}

define internal i32 @compute_step.21() #2 !dbg !76 {
entry:
  ret i32 1, !dbg !77
}

; Function Attrs: nounwind
declare i1 @llvm.directive.marker() #1

attributes #0 = { noinline nounwind uwtable "frame-pointer"="all" "min-legal-vector-width"="0" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cmov,+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "tune-cpu"="generic" }
attributes #1 = { nounwind }
attributes #2 = { "min-legal-vector-width"="0" }

!llvm.dbg.cu = !{!0}
!llvm.module.flags = !{!2, !3, !4, !5}
!llvm.ident = !{!6}

!0 = distinct !DICompileUnit(language: DW_LANG_C11, file: !1, producer: "clang version 21.0.0git (git@bscpm04.bsc.es:llvm-ompss/llvm-mono.git e482556a80a52b54ca562602ba8eb05ce9bf2f6d)", isOptimized: false, runtimeVersion: 0, emissionKind: NoDebug, splitDebugInlining: false, nameTableKind: None)
!1 = !DIFile(filename: "kaka.c", directory: "/home/rpenacob/llvm-mono-bld1/bin")
!2 = !{i32 2, !"Debug Info Version", i32 3}
!3 = !{i32 1, !"wchar_size", i32 4}
!4 = !{i32 7, !"uwtable", i32 2}
!5 = !{i32 7, !"frame-pointer", i32 2}
!6 = !{!"clang version 21.0.0git (git@bscpm04.bsc.es:llvm-ompss/llvm-mono.git e482556a80a52b54ca562602ba8eb05ce9bf2f6d)"}
!7 = distinct !DISubprogram(name: "main", scope: !1, file: !1, line: 1, type: !8, scopeLine: 1, spFlags: DISPFlagDefinition, unit: !0)
!8 = !DISubroutineType(types: !9)
!9 = !{}
!10 = !DILocation(line: 3, column: 14, scope: !7)
!11 = !DILocation(line: 4, column: 18, scope: !7)
!12 = !DILocation(line: 4, column: 14, scope: !7)
!13 = !DILocation(line: 5, column: 9, scope: !7)
!14 = !DILocation(line: 8, column: 14, scope: !7)
!15 = !DILocation(line: 9, column: 22, scope: !7)
!16 = !DILocation(line: 9, column: 18, scope: !7)
!17 = !DILocation(line: 9, column: 14, scope: !7)
!18 = !DILocation(line: 10, column: 9, scope: !7)
!19 = !DILocation(line: 13, column: 14, scope: !7)
!20 = !DILocation(line: 14, column: 18, scope: !7)
!21 = !DILocation(line: 14, column: 14, scope: !7)
!22 = !DILocation(line: 15, column: 9, scope: !7)
!23 = !DILocation(line: 18, column: 14, scope: !7)
!24 = !DILocation(line: 19, column: 22, scope: !7)
!25 = !DILocation(line: 19, column: 18, scope: !7)
!26 = !DILocation(line: 19, column: 14, scope: !7)
!27 = !DILocation(line: 20, column: 9, scope: !7)
!28 = !DILocation(line: 22, column: 5, scope: !7)
!29 = !DILocation(line: 23, column: 1, scope: !7)
!30 = distinct !DISubprogram(linkageName: "compute_lb", scope: !1, file: !1, type: !8, flags: DIFlagArtificial, spFlags: DISPFlagLocalToUnit | DISPFlagDefinition, unit: !0)
!31 = !DILocation(line: 3, column: 18, scope: !30)
!32 = distinct !DISubprogram(linkageName: "compute_ub", scope: !1, file: !1, type: !8, flags: DIFlagArtificial, spFlags: DISPFlagLocalToUnit | DISPFlagDefinition, unit: !0)
!33 = !DILocation(line: 3, column: 25, scope: !32)
!34 = distinct !DISubprogram(linkageName: "compute_step", scope: !1, file: !1, type: !8, flags: DIFlagArtificial, spFlags: DISPFlagLocalToUnit | DISPFlagDefinition, unit: !0)
!35 = !DILocation(line: 3, column: 29, scope: !34)
!36 = distinct !DISubprogram(linkageName: "compute_lb.1", scope: !1, file: !1, type: !8, flags: DIFlagArtificial, spFlags: DISPFlagLocalToUnit | DISPFlagDefinition, unit: !0)
!37 = !DILocation(line: 4, column: 22, scope: !36)
!38 = distinct !DISubprogram(linkageName: "compute_ub.2", scope: !1, file: !1, type: !8, flags: DIFlagArtificial, spFlags: DISPFlagLocalToUnit | DISPFlagDefinition, unit: !0)
!39 = !DILocation(line: 4, column: 30, scope: !38)
!40 = distinct !DISubprogram(linkageName: "compute_step.3", scope: !1, file: !1, type: !8, flags: DIFlagArtificial, spFlags: DISPFlagLocalToUnit | DISPFlagDefinition, unit: !0)
!41 = !DILocation(line: 4, column: 33, scope: !40)
!42 = distinct !DISubprogram(linkageName: "compute_lb.4", scope: !1, file: !1, type: !8, flags: DIFlagArtificial, spFlags: DISPFlagLocalToUnit | DISPFlagDefinition, unit: !0)
!43 = !DILocation(line: 8, column: 18, scope: !42)
!44 = distinct !DISubprogram(linkageName: "compute_ub.5", scope: !1, file: !1, type: !8, flags: DIFlagArtificial, spFlags: DISPFlagLocalToUnit | DISPFlagDefinition, unit: !0)
!45 = !DILocation(line: 8, column: 25, scope: !44)
!46 = distinct !DISubprogram(linkageName: "compute_step.6", scope: !1, file: !1, type: !8, flags: DIFlagArtificial, spFlags: DISPFlagLocalToUnit | DISPFlagDefinition, unit: !0)
!47 = !DILocation(line: 8, column: 29, scope: !46)
!48 = distinct !DISubprogram(linkageName: "compute_lb.7", scope: !1, file: !1, type: !8, flags: DIFlagArtificial, spFlags: DISPFlagLocalToUnit | DISPFlagDefinition, unit: !0)
!49 = !DILocation(line: 9, column: 22, scope: !48)
!50 = distinct !DISubprogram(linkageName: "compute_ub.8", scope: !1, file: !1, type: !8, flags: DIFlagArtificial, spFlags: DISPFlagLocalToUnit | DISPFlagDefinition, unit: !0)
!51 = !DILocation(line: 9, column: 29, scope: !50)
!52 = distinct !DISubprogram(linkageName: "compute_step.9", scope: !1, file: !1, type: !8, flags: DIFlagArtificial, spFlags: DISPFlagLocalToUnit | DISPFlagDefinition, unit: !0)
!53 = !DILocation(line: 9, column: 32, scope: !52)
!54 = distinct !DISubprogram(linkageName: "compute_lb.10", scope: !1, file: !1, type: !8, flags: DIFlagArtificial, spFlags: DISPFlagLocalToUnit | DISPFlagDefinition, unit: !0)
!55 = !DILocation(line: 13, column: 18, scope: !54)
!56 = distinct !DISubprogram(linkageName: "compute_ub.11", scope: !1, file: !1, type: !8, flags: DIFlagArtificial, spFlags: DISPFlagLocalToUnit | DISPFlagDefinition, unit: !0)
!57 = !DILocation(line: 13, column: 25, scope: !56)
!58 = distinct !DISubprogram(linkageName: "compute_step.12", scope: !1, file: !1, type: !8, flags: DIFlagArtificial, spFlags: DISPFlagLocalToUnit | DISPFlagDefinition, unit: !0)
!59 = !DILocation(line: 13, column: 29, scope: !58)
!60 = distinct !DISubprogram(linkageName: "compute_lb.13", scope: !1, file: !1, type: !8, flags: DIFlagArtificial, spFlags: DISPFlagLocalToUnit | DISPFlagDefinition, unit: !0)
!61 = !DILocation(line: 14, column: 22, scope: !60)
!62 = distinct !DISubprogram(linkageName: "compute_ub.14", scope: !1, file: !1, type: !8, flags: DIFlagArtificial, spFlags: DISPFlagLocalToUnit | DISPFlagDefinition, unit: !0)
!63 = !DILocation(line: 14, column: 29, scope: !62)
!64 = distinct !DISubprogram(linkageName: "compute_step.15", scope: !1, file: !1, type: !8, flags: DIFlagArtificial, spFlags: DISPFlagLocalToUnit | DISPFlagDefinition, unit: !0)
!65 = !DILocation(line: 14, column: 32, scope: !64)
!66 = distinct !DISubprogram(linkageName: "compute_lb.16", scope: !1, file: !1, type: !8, flags: DIFlagArtificial, spFlags: DISPFlagLocalToUnit | DISPFlagDefinition, unit: !0)
!67 = !DILocation(line: 18, column: 18, scope: !66)
!68 = distinct !DISubprogram(linkageName: "compute_ub.17", scope: !1, file: !1, type: !8, flags: DIFlagArtificial, spFlags: DISPFlagLocalToUnit | DISPFlagDefinition, unit: !0)
!69 = !DILocation(line: 18, column: 25, scope: !68)
!70 = distinct !DISubprogram(linkageName: "compute_step.18", scope: !1, file: !1, type: !8, flags: DIFlagArtificial, spFlags: DISPFlagLocalToUnit | DISPFlagDefinition, unit: !0)
!71 = !DILocation(line: 18, column: 29, scope: !70)
!72 = distinct !DISubprogram(linkageName: "compute_lb.19", scope: !1, file: !1, type: !8, flags: DIFlagArtificial, spFlags: DISPFlagLocalToUnit | DISPFlagDefinition, unit: !0)
!73 = !DILocation(line: 19, column: 22, scope: !72)
!74 = distinct !DISubprogram(linkageName: "compute_ub.20", scope: !1, file: !1, type: !8, flags: DIFlagArtificial, spFlags: DISPFlagLocalToUnit | DISPFlagDefinition, unit: !0)
!75 = !DILocation(line: 19, column: 29, scope: !74)
!76 = distinct !DISubprogram(linkageName: "compute_step.21", scope: !1, file: !1, type: !8, flags: DIFlagArtificial, spFlags: DISPFlagLocalToUnit | DISPFlagDefinition, unit: !0)
!77 = !DILocation(line: 19, column: 33, scope: !76)
; CHECK-LABEL: define {{[^@]+}}@main
; CHECK-SAME: () local_unnamed_addr #[[ATTR0:[0-9]+]] !dbg [[DBG7:![0-9]+]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = alloca ptr, align 8, !dbg [[DBG10:![0-9]+]]
; CHECK-NEXT:    [[TMP1:%.*]] = alloca ptr, align 8, !dbg [[DBG10]]
; CHECK-NEXT:    [[TMP2:%.*]] = alloca ptr, align 8, !dbg [[DBG11:![0-9]+]]
; CHECK-NEXT:    [[TMP3:%.*]] = alloca ptr, align 8, !dbg [[DBG11]]
; CHECK-NEXT:    [[TMP4:%.*]] = alloca ptr, align 8, !dbg [[DBG12:![0-9]+]]
; CHECK-NEXT:    [[TMP5:%.*]] = alloca ptr, align 8, !dbg [[DBG12]]
; CHECK-NEXT:    [[TMP6:%.*]] = alloca ptr, align 8, !dbg [[DBG13:![0-9]+]]
; CHECK-NEXT:    [[TMP7:%.*]] = alloca ptr, align 8, !dbg [[DBG13]]
; CHECK-NEXT:    [[TMP8:%.*]] = tail call i32 @nanos6_in_final() #[[ATTR4:[0-9]+]], !dbg [[DBG13]]
; CHECK-NEXT:    [[DOTNOT:%.*]] = icmp eq i32 [[TMP8]], 0, !dbg [[DBG13]]
; CHECK-NEXT:    br i1 [[DOTNOT]], label [[CODEREPL:%.*]], label [[FINAL_END:%.*]], !dbg [[DBG13]]
; CHECK:       codeRepl:
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr nonnull [[TMP7]]), !dbg [[DBG13]]
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr nonnull [[TMP6]]), !dbg [[DBG13]]
; CHECK-NEXT:    call void @nanos6_create_loop(ptr nonnull @task_info_var_main, ptr nonnull @task_invocation_info_main, ptr null, i64 16, ptr nonnull [[TMP7]], ptr nonnull [[TMP6]], i64 4, i64 0, i64 0, i64 100, i64 0, i64 0) #[[ATTR4]], !dbg [[DBG13]]
; CHECK-NEXT:    [[TMP9:%.*]] = load ptr, ptr [[TMP6]], align 8, !dbg [[DBG13]]
; CHECK-NEXT:    call void @nanos6_submit_task(ptr [[TMP9]]) #[[ATTR4]], !dbg [[DBG13]]
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr nonnull [[TMP7]]), !dbg [[DBG13]]
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr nonnull [[TMP6]]), !dbg [[DBG13]]
; CHECK-NEXT:    br label [[FINAL_END]], !dbg [[DBG13]]
; CHECK:       final.end:
; CHECK-NEXT:    [[TMP10:%.*]] = call i32 @nanos6_in_final() #[[ATTR4]], !dbg [[DBG12]]
; CHECK-NEXT:    [[DOTNOT67:%.*]] = icmp eq i32 [[TMP10]], 0, !dbg [[DBG12]]
; CHECK-NEXT:    br i1 [[DOTNOT67]], label [[CODEREPL24:%.*]], label [[FINAL_END17:%.*]], !dbg [[DBG12]]
; CHECK:       codeRepl24:
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr nonnull [[TMP5]]), !dbg [[DBG12]]
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr nonnull [[TMP4]]), !dbg [[DBG12]]
; CHECK-NEXT:    call void @nanos6_create_loop(ptr nonnull @task_info_var_main.10, ptr nonnull @task_invocation_info_main.6, ptr null, i64 16, ptr nonnull [[TMP5]], ptr nonnull [[TMP4]], i64 4, i64 0, i64 0, i64 90, i64 0, i64 0) #[[ATTR4]], !dbg [[DBG12]]
; CHECK-NEXT:    [[TMP11:%.*]] = load ptr, ptr [[TMP4]], align 8, !dbg [[DBG12]]
; CHECK-NEXT:    call void @nanos6_submit_task(ptr [[TMP11]]) #[[ATTR4]], !dbg [[DBG12]]
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr nonnull [[TMP5]]), !dbg [[DBG12]]
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr nonnull [[TMP4]]), !dbg [[DBG12]]
; CHECK-NEXT:    br label [[FINAL_END17]], !dbg [[DBG12]]
; CHECK:       final.end17:
; CHECK-NEXT:    [[TMP12:%.*]] = call i32 @nanos6_in_final() #[[ATTR4]], !dbg [[DBG11]]
; CHECK-NEXT:    [[DOTNOT69:%.*]] = icmp eq i32 [[TMP12]], 0, !dbg [[DBG11]]
; CHECK-NEXT:    br i1 [[DOTNOT69]], label [[CODEREPL42:%.*]], label [[FINAL_END35:%.*]], !dbg [[DBG11]]
; CHECK:       codeRepl42:
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr nonnull [[TMP3]]), !dbg [[DBG11]]
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr nonnull [[TMP2]]), !dbg [[DBG11]]
; CHECK-NEXT:    call void @nanos6_create_loop(ptr nonnull @task_info_var_main.20, ptr nonnull @task_invocation_info_main.16, ptr null, i64 16, ptr nonnull [[TMP3]], ptr nonnull [[TMP2]], i64 4, i64 0, i64 0, i64 90, i64 0, i64 0) #[[ATTR4]], !dbg [[DBG11]]
; CHECK-NEXT:    [[TMP13:%.*]] = load ptr, ptr [[TMP2]], align 8, !dbg [[DBG11]]
; CHECK-NEXT:    call void @nanos6_submit_task(ptr [[TMP13]]) #[[ATTR4]], !dbg [[DBG11]]
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr nonnull [[TMP3]]), !dbg [[DBG11]]
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr nonnull [[TMP2]]), !dbg [[DBG11]]
; CHECK-NEXT:    br label [[FINAL_END35]], !dbg [[DBG11]]
; CHECK:       final.end35:
; CHECK-NEXT:    [[TMP14:%.*]] = call i32 @nanos6_in_final() #[[ATTR4]], !dbg [[DBG10]]
; CHECK-NEXT:    [[DOTNOT71:%.*]] = icmp eq i32 [[TMP14]], 0, !dbg [[DBG10]]
; CHECK-NEXT:    br i1 [[DOTNOT71]], label [[CODEREPL60:%.*]], label [[FINAL_END53:%.*]], !dbg [[DBG10]]
; CHECK:       codeRepl60:
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr nonnull [[TMP1]]), !dbg [[DBG10]]
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr nonnull [[TMP0]]), !dbg [[DBG10]]
; CHECK-NEXT:    call void @nanos6_create_loop(ptr nonnull @task_info_var_main.30, ptr nonnull @task_invocation_info_main.26, ptr null, i64 16, ptr nonnull [[TMP1]], ptr nonnull [[TMP0]], i64 4, i64 0, i64 0, i64 100, i64 0, i64 0) #[[ATTR4]], !dbg [[DBG10]]
; CHECK-NEXT:    [[TMP15:%.*]] = load ptr, ptr [[TMP0]], align 8, !dbg [[DBG10]]
; CHECK-NEXT:    call void @nanos6_submit_task(ptr [[TMP15]]) #[[ATTR4]], !dbg [[DBG10]]
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr nonnull [[TMP1]]), !dbg [[DBG10]]
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr nonnull [[TMP0]]), !dbg [[DBG10]]
; CHECK-NEXT:    br label [[FINAL_END53]], !dbg [[DBG10]]
; CHECK:       final.end53:
; CHECK-NEXT:    call void @nanos6_taskwait(ptr nonnull @[[GLOB5:[0-9]+]]) #[[ATTR4]], !dbg [[DBG14:![0-9]+]]
; CHECK-NEXT:    ret i32 0, !dbg [[DBG15:![0-9]+]]
;
;
; CHECK-LABEL: define {{[^@]+}}@nanos6_constructor_check_version() {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    tail call void @nanos6_check_version(i64 1, ptr nonnull @nanos6_versions, ptr nonnull @[[GLOB0:[0-9]+]])
; CHECK-NEXT:    ret void
;
;
; CHECK-LABEL: define {{[^@]+}}@nanos6_unpacked_task_region_main
; CHECK-SAME: (ptr writeonly captures(none) initializes((0, 4)) [[I:%.*]], ptr writeonly captures(none) [[J:%.*]], i64 [[LOOP_BOUNDS_0_VAL:%.*]], i64 [[LOOP_BOUNDS_8_VAL:%.*]]) unnamed_addr #[[ATTR1:[0-9]+]] !dbg [[DBG16:![0-9]+]] {
; CHECK-NEXT:  newFuncRoot:
; CHECK-NEXT:    store i32 0, ptr [[I]], align 4, !dbg [[DBG18:![0-9]+]]
; CHECK-NEXT:    [[TMP0:%.*]] = icmp ult i64 [[LOOP_BOUNDS_0_VAL]], [[LOOP_BOUNDS_8_VAL]], !dbg [[DBG18]]
; CHECK-NEXT:    br i1 [[TMP0]], label [[FOR_INCR8_PREHEADER:%.*]], label [[FOR_END7_EXITSTUB:%.*]], !dbg [[DBG18]]
; CHECK:       for.incr8.preheader:
; CHECK-NEXT:    [[TMP1:%.*]] = sub nuw i64 [[LOOP_BOUNDS_8_VAL]], [[LOOP_BOUNDS_0_VAL]], !dbg [[DBG18]]
; CHECK-NEXT:    [[DOTNEG2:%.*]] = add i64 [[LOOP_BOUNDS_0_VAL]], 1, !dbg [[DBG18]]
; CHECK-NEXT:    [[XTRAITER:%.*]] = and i64 [[TMP1]], 1, !dbg [[DBG18]]
; CHECK-NEXT:    [[LCMP_MOD_NOT:%.*]] = icmp eq i64 [[XTRAITER]], 0, !dbg [[DBG18]]
; CHECK-NEXT:    br i1 [[LCMP_MOD_NOT]], label [[FOR_INCR8_PROL_LOOPEXIT:%.*]], label [[FOR_INCR8_PROL:%.*]], !dbg [[DBG18]]
; CHECK:       for.incr8.prol:
; CHECK-NEXT:    [[TMP2:%.*]] = udiv i64 [[LOOP_BOUNDS_0_VAL]], 10, !dbg [[DBG18]]
; CHECK-NEXT:    [[TMP3:%.*]] = mul nuw i64 [[TMP2]], 10, !dbg [[DBG18]]
; CHECK-NEXT:    [[DOTNEG_PROL:%.*]] = sub i64 [[TMP3]], [[LOOP_BOUNDS_0_VAL]], !dbg [[DBG18]]
; CHECK-NEXT:    [[TMP4:%.*]] = trunc i64 [[TMP2]] to i32, !dbg [[DBG18]]
; CHECK-NEXT:    store i32 [[TMP4]], ptr [[I]], align 4, !dbg [[DBG18]]
; CHECK-NEXT:    [[TMP5:%.*]] = trunc i64 [[DOTNEG_PROL]] to i32, !dbg [[DBG18]]
; CHECK-NEXT:    [[TMP6:%.*]] = add i32 [[TMP5]], 10, !dbg [[DBG18]]
; CHECK-NEXT:    store i32 [[TMP6]], ptr [[J]], align 4, !dbg [[DBG18]]
; CHECK-NEXT:    [[TMP7:%.*]] = add nuw i64 [[LOOP_BOUNDS_0_VAL]], 1, !dbg [[DBG18]]
; CHECK-NEXT:    br label [[FOR_INCR8_PROL_LOOPEXIT]], !dbg [[DBG18]]
; CHECK:       for.incr8.prol.loopexit:
; CHECK-NEXT:    [[LOOP_01_UNR:%.*]] = phi i64 [ [[LOOP_BOUNDS_0_VAL]], [[FOR_INCR8_PREHEADER]] ], [ [[TMP7]], [[FOR_INCR8_PROL]] ]
; CHECK-NEXT:    [[TMP8:%.*]] = icmp eq i64 [[LOOP_BOUNDS_8_VAL]], [[DOTNEG2]], !dbg [[DBG18]]
; CHECK-NEXT:    br i1 [[TMP8]], label [[FOR_END7_EXITSTUB]], label [[FOR_INCR8:%.*]], !dbg [[DBG18]]
; CHECK:       for.incr8:
; CHECK-NEXT:    [[LOOP_01:%.*]] = phi i64 [ [[TMP20:%.*]], [[FOR_INCR8]] ], [ [[LOOP_01_UNR]], [[FOR_INCR8_PROL_LOOPEXIT]] ]
; CHECK-NEXT:    [[TMP9:%.*]] = udiv i64 [[LOOP_01]], 10, !dbg [[DBG18]]
; CHECK-NEXT:    [[TMP10:%.*]] = mul nuw i64 [[TMP9]], 10, !dbg [[DBG18]]
; CHECK-NEXT:    [[DOTNEG:%.*]] = sub i64 [[TMP10]], [[LOOP_01]], !dbg [[DBG18]]
; CHECK-NEXT:    [[TMP11:%.*]] = trunc i64 [[TMP9]] to i32, !dbg [[DBG18]]
; CHECK-NEXT:    store i32 [[TMP11]], ptr [[I]], align 4, !dbg [[DBG18]]
; CHECK-NEXT:    [[TMP12:%.*]] = trunc i64 [[DOTNEG]] to i32, !dbg [[DBG18]]
; CHECK-NEXT:    [[TMP13:%.*]] = add i32 [[TMP12]], 10, !dbg [[DBG18]]
; CHECK-NEXT:    store i32 [[TMP13]], ptr [[J]], align 4, !dbg [[DBG18]]
; CHECK-NEXT:    [[TMP14:%.*]] = add nuw i64 [[LOOP_01]], 1, !dbg [[DBG18]]
; CHECK-NEXT:    [[TMP15:%.*]] = udiv i64 [[TMP14]], 10, !dbg [[DBG18]]
; CHECK-NEXT:    [[TMP16:%.*]] = mul nuw i64 [[TMP15]], 10, !dbg [[DBG18]]
; CHECK-NEXT:    [[DOTNEG_1:%.*]] = sub i64 [[TMP16]], [[TMP14]], !dbg [[DBG18]]
; CHECK-NEXT:    [[TMP17:%.*]] = trunc i64 [[TMP15]] to i32, !dbg [[DBG18]]
; CHECK-NEXT:    store i32 [[TMP17]], ptr [[I]], align 4, !dbg [[DBG18]]
; CHECK-NEXT:    [[TMP18:%.*]] = trunc i64 [[DOTNEG_1]] to i32, !dbg [[DBG18]]
; CHECK-NEXT:    [[TMP19:%.*]] = add i32 [[TMP18]], 10, !dbg [[DBG18]]
; CHECK-NEXT:    store i32 [[TMP19]], ptr [[J]], align 4, !dbg [[DBG18]]
; CHECK-NEXT:    [[TMP20]] = add nuw i64 [[LOOP_01]], 2, !dbg [[DBG18]]
; CHECK-NEXT:    [[EXITCOND_NOT_1:%.*]] = icmp eq i64 [[TMP20]], [[LOOP_BOUNDS_8_VAL]], !dbg [[DBG18]]
; CHECK-NEXT:    br i1 [[EXITCOND_NOT_1]], label [[FOR_END7_EXITSTUB]], label [[FOR_INCR8]], !dbg [[DBG18]]
; CHECK:       for.end7.exitStub:
; CHECK-NEXT:    ret void
;
;
; CHECK-LABEL: define {{[^@]+}}@nanos6_ol_task_region_main
; CHECK-SAME: (ptr writeonly captures(none) [[TASK_ARGS:%.*]], ptr readonly captures(none) [[LOOP_BOUNDS:%.*]], ptr readnone captures(none) [[ADDRESS_TRANSLATION_TABLE:%.*]]) #[[ATTR2:[0-9]+]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[GEP_J:%.*]] = getelementptr i8, ptr [[TASK_ARGS]], i64 4
; CHECK-NEXT:    [[LOOP_BOUNDS_VAL:%.*]] = load i64, ptr [[LOOP_BOUNDS]], align 8
; CHECK-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr [[LOOP_BOUNDS]], i64 8
; CHECK-NEXT:    [[LOOP_BOUNDS_VAL1:%.*]] = load i64, ptr [[TMP0]], align 8
; CHECK-NEXT:    tail call fastcc void @nanos6_unpacked_task_region_main(ptr [[TASK_ARGS]], ptr [[GEP_J]], i64 [[LOOP_BOUNDS_VAL]], i64 [[LOOP_BOUNDS_VAL1]])
; CHECK-NEXT:    ret void
;
;
; CHECK-LABEL: define {{[^@]+}}@nanos6_constructor_register_task_info() {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    tail call void @nanos6_register_task_info(ptr nonnull @task_info_var_main)
; CHECK-NEXT:    tail call void @nanos6_register_task_info(ptr nonnull @task_info_var_main.10)
; CHECK-NEXT:    tail call void @nanos6_register_task_info(ptr nonnull @task_info_var_main.20)
; CHECK-NEXT:    tail call void @nanos6_register_task_info(ptr nonnull @task_info_var_main.30)
; CHECK-NEXT:    ret void
;
;
; CHECK-LABEL: define {{[^@]+}}@nanos6_unpacked_task_region_main.4
; CHECK-SAME: (ptr writeonly captures(none) initializes((0, 4)) [[I1:%.*]], ptr writeonly captures(none) [[J2:%.*]], i64 [[LOOP_BOUNDS_0_VAL:%.*]], i64 [[LOOP_BOUNDS_8_VAL:%.*]]) unnamed_addr #[[ATTR1]] !dbg [[DBG19:![0-9]+]] {
; CHECK-NEXT:  newFuncRoot:
; CHECK-NEXT:    store i32 0, ptr [[I1]], align 4, !dbg [[DBG20:![0-9]+]]
; CHECK-NEXT:    [[TMP0:%.*]] = icmp ult i64 [[LOOP_BOUNDS_0_VAL]], [[LOOP_BOUNDS_8_VAL]], !dbg [[DBG20]]
; CHECK-NEXT:    br i1 [[TMP0]], label [[FOR_INCR23_PREHEADER:%.*]], label [[FOR_END22_EXITSTUB:%.*]], !dbg [[DBG20]]
; CHECK:       for.incr23.preheader:
; CHECK-NEXT:    [[TMP1:%.*]] = sub nuw i64 [[LOOP_BOUNDS_8_VAL]], [[LOOP_BOUNDS_0_VAL]], !dbg [[DBG20]]
; CHECK-NEXT:    [[DOTNEG2:%.*]] = add i64 [[LOOP_BOUNDS_0_VAL]], 1, !dbg [[DBG20]]
; CHECK-NEXT:    [[XTRAITER:%.*]] = and i64 [[TMP1]], 1, !dbg [[DBG20]]
; CHECK-NEXT:    [[LCMP_MOD_NOT:%.*]] = icmp eq i64 [[XTRAITER]], 0, !dbg [[DBG20]]
; CHECK-NEXT:    br i1 [[LCMP_MOD_NOT]], label [[FOR_INCR23_PROL_LOOPEXIT:%.*]], label [[FOR_INCR23_PROL:%.*]], !dbg [[DBG20]]
; CHECK:       for.incr23.prol:
; CHECK-NEXT:    [[TMP2:%.*]] = udiv i64 [[LOOP_BOUNDS_0_VAL]], 9, !dbg [[DBG20]]
; CHECK-NEXT:    [[TMP3:%.*]] = mul nuw i64 [[TMP2]], 9, !dbg [[DBG20]]
; CHECK-NEXT:    [[DOTNEG_PROL:%.*]] = sub i64 [[TMP3]], [[LOOP_BOUNDS_0_VAL]], !dbg [[DBG20]]
; CHECK-NEXT:    [[TMP4:%.*]] = trunc i64 [[TMP2]] to i32, !dbg [[DBG20]]
; CHECK-NEXT:    store i32 [[TMP4]], ptr [[I1]], align 4, !dbg [[DBG20]]
; CHECK-NEXT:    [[TMP5:%.*]] = trunc i64 [[DOTNEG_PROL]] to i32, !dbg [[DBG20]]
; CHECK-NEXT:    [[TMP6:%.*]] = add i32 [[TMP5]], 9, !dbg [[DBG20]]
; CHECK-NEXT:    store i32 [[TMP6]], ptr [[J2]], align 4, !dbg [[DBG20]]
; CHECK-NEXT:    [[TMP7:%.*]] = add nuw i64 [[LOOP_BOUNDS_0_VAL]], 1, !dbg [[DBG20]]
; CHECK-NEXT:    br label [[FOR_INCR23_PROL_LOOPEXIT]], !dbg [[DBG20]]
; CHECK:       for.incr23.prol.loopexit:
; CHECK-NEXT:    [[LOOP_01_UNR:%.*]] = phi i64 [ [[LOOP_BOUNDS_0_VAL]], [[FOR_INCR23_PREHEADER]] ], [ [[TMP7]], [[FOR_INCR23_PROL]] ]
; CHECK-NEXT:    [[TMP8:%.*]] = icmp eq i64 [[LOOP_BOUNDS_8_VAL]], [[DOTNEG2]], !dbg [[DBG20]]
; CHECK-NEXT:    br i1 [[TMP8]], label [[FOR_END22_EXITSTUB]], label [[FOR_INCR23:%.*]], !dbg [[DBG20]]
; CHECK:       for.incr23:
; CHECK-NEXT:    [[LOOP_01:%.*]] = phi i64 [ [[TMP20:%.*]], [[FOR_INCR23]] ], [ [[LOOP_01_UNR]], [[FOR_INCR23_PROL_LOOPEXIT]] ]
; CHECK-NEXT:    [[TMP9:%.*]] = udiv i64 [[LOOP_01]], 9, !dbg [[DBG20]]
; CHECK-NEXT:    [[TMP10:%.*]] = mul nuw i64 [[TMP9]], 9, !dbg [[DBG20]]
; CHECK-NEXT:    [[DOTNEG:%.*]] = sub i64 [[TMP10]], [[LOOP_01]], !dbg [[DBG20]]
; CHECK-NEXT:    [[TMP11:%.*]] = trunc i64 [[TMP9]] to i32, !dbg [[DBG20]]
; CHECK-NEXT:    store i32 [[TMP11]], ptr [[I1]], align 4, !dbg [[DBG20]]
; CHECK-NEXT:    [[TMP12:%.*]] = trunc i64 [[DOTNEG]] to i32, !dbg [[DBG20]]
; CHECK-NEXT:    [[TMP13:%.*]] = add i32 [[TMP12]], 9, !dbg [[DBG20]]
; CHECK-NEXT:    store i32 [[TMP13]], ptr [[J2]], align 4, !dbg [[DBG20]]
; CHECK-NEXT:    [[TMP14:%.*]] = add nuw i64 [[LOOP_01]], 1, !dbg [[DBG20]]
; CHECK-NEXT:    [[TMP15:%.*]] = udiv i64 [[TMP14]], 9, !dbg [[DBG20]]
; CHECK-NEXT:    [[TMP16:%.*]] = mul nuw i64 [[TMP15]], 9, !dbg [[DBG20]]
; CHECK-NEXT:    [[DOTNEG_1:%.*]] = sub i64 [[TMP16]], [[TMP14]], !dbg [[DBG20]]
; CHECK-NEXT:    [[TMP17:%.*]] = trunc i64 [[TMP15]] to i32, !dbg [[DBG20]]
; CHECK-NEXT:    store i32 [[TMP17]], ptr [[I1]], align 4, !dbg [[DBG20]]
; CHECK-NEXT:    [[TMP18:%.*]] = trunc i64 [[DOTNEG_1]] to i32, !dbg [[DBG20]]
; CHECK-NEXT:    [[TMP19:%.*]] = add i32 [[TMP18]], 9, !dbg [[DBG20]]
; CHECK-NEXT:    store i32 [[TMP19]], ptr [[J2]], align 4, !dbg [[DBG20]]
; CHECK-NEXT:    [[TMP20]] = add nuw i64 [[LOOP_01]], 2, !dbg [[DBG20]]
; CHECK-NEXT:    [[EXITCOND_NOT_1:%.*]] = icmp eq i64 [[TMP20]], [[LOOP_BOUNDS_8_VAL]], !dbg [[DBG20]]
; CHECK-NEXT:    br i1 [[EXITCOND_NOT_1]], label [[FOR_END22_EXITSTUB]], label [[FOR_INCR23]], !dbg [[DBG20]]
; CHECK:       for.end22.exitStub:
; CHECK-NEXT:    ret void
;
;
; CHECK-LABEL: define {{[^@]+}}@nanos6_ol_task_region_main.5
; CHECK-SAME: (ptr writeonly captures(none) [[TASK_ARGS:%.*]], ptr readonly captures(none) [[LOOP_BOUNDS:%.*]], ptr readnone captures(none) [[ADDRESS_TRANSLATION_TABLE:%.*]]) #[[ATTR2]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[GEP_J2:%.*]] = getelementptr i8, ptr [[TASK_ARGS]], i64 4
; CHECK-NEXT:    [[LOOP_BOUNDS_VAL:%.*]] = load i64, ptr [[LOOP_BOUNDS]], align 8
; CHECK-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr [[LOOP_BOUNDS]], i64 8
; CHECK-NEXT:    [[LOOP_BOUNDS_VAL1:%.*]] = load i64, ptr [[TMP0]], align 8
; CHECK-NEXT:    tail call fastcc void @nanos6_unpacked_task_region_main.4(ptr [[TASK_ARGS]], ptr [[GEP_J2]], i64 [[LOOP_BOUNDS_VAL]], i64 [[LOOP_BOUNDS_VAL1]])
; CHECK-NEXT:    ret void
;
;
; CHECK-LABEL: define {{[^@]+}}@nanos6_unpacked_task_region_main.14
; CHECK-SAME: (ptr writeonly captures(none) initializes((0, 4)) [[I3:%.*]], ptr writeonly captures(none) [[J4:%.*]], i64 [[LOOP_BOUNDS_0_VAL:%.*]], i64 [[LOOP_BOUNDS_8_VAL:%.*]]) unnamed_addr #[[ATTR1]] !dbg [[DBG21:![0-9]+]] {
; CHECK-NEXT:  newFuncRoot:
; CHECK-NEXT:    store i32 9, ptr [[I3]], align 4, !dbg [[DBG22:![0-9]+]]
; CHECK-NEXT:    [[TMP0:%.*]] = icmp ult i64 [[LOOP_BOUNDS_0_VAL]], [[LOOP_BOUNDS_8_VAL]], !dbg [[DBG22]]
; CHECK-NEXT:    br i1 [[TMP0]], label [[FOR_INCR41_PREHEADER:%.*]], label [[FOR_END40_EXITSTUB:%.*]], !dbg [[DBG22]]
; CHECK:       for.incr41.preheader:
; CHECK-NEXT:    [[TMP1:%.*]] = sub nuw i64 [[LOOP_BOUNDS_8_VAL]], [[LOOP_BOUNDS_0_VAL]], !dbg [[DBG22]]
; CHECK-NEXT:    [[DOTNEG2:%.*]] = add i64 [[LOOP_BOUNDS_0_VAL]], 1, !dbg [[DBG22]]
; CHECK-NEXT:    [[XTRAITER:%.*]] = and i64 [[TMP1]], 1, !dbg [[DBG22]]
; CHECK-NEXT:    [[LCMP_MOD_NOT:%.*]] = icmp eq i64 [[XTRAITER]], 0, !dbg [[DBG22]]
; CHECK-NEXT:    br i1 [[LCMP_MOD_NOT]], label [[FOR_INCR41_PROL_LOOPEXIT:%.*]], label [[FOR_INCR41_PROL:%.*]], !dbg [[DBG22]]
; CHECK:       for.incr41.prol:
; CHECK-NEXT:    [[TMP2:%.*]] = udiv i64 [[LOOP_BOUNDS_0_VAL]], 9, !dbg [[DBG22]]
; CHECK-NEXT:    [[DOTNEG_PROL:%.*]] = mul i64 [[TMP2]], 4294967287, !dbg [[DBG22]]
; CHECK-NEXT:    [[TMP3:%.*]] = add i64 [[DOTNEG_PROL]], [[LOOP_BOUNDS_0_VAL]], !dbg [[DBG22]]
; CHECK-NEXT:    [[TMP4:%.*]] = trunc i64 [[TMP2]] to i32, !dbg [[DBG22]]
; CHECK-NEXT:    store i32 [[TMP4]], ptr [[I3]], align 4, !dbg [[DBG22]]
; CHECK-NEXT:    [[TMP5:%.*]] = trunc i64 [[TMP3]] to i32, !dbg [[DBG22]]
; CHECK-NEXT:    store i32 [[TMP5]], ptr [[J4]], align 4, !dbg [[DBG22]]
; CHECK-NEXT:    [[TMP6:%.*]] = add nuw i64 [[LOOP_BOUNDS_0_VAL]], 1, !dbg [[DBG22]]
; CHECK-NEXT:    br label [[FOR_INCR41_PROL_LOOPEXIT]], !dbg [[DBG22]]
; CHECK:       for.incr41.prol.loopexit:
; CHECK-NEXT:    [[LOOP_01_UNR:%.*]] = phi i64 [ [[LOOP_BOUNDS_0_VAL]], [[FOR_INCR41_PREHEADER]] ], [ [[TMP6]], [[FOR_INCR41_PROL]] ]
; CHECK-NEXT:    [[TMP7:%.*]] = icmp eq i64 [[LOOP_BOUNDS_8_VAL]], [[DOTNEG2]], !dbg [[DBG22]]
; CHECK-NEXT:    br i1 [[TMP7]], label [[FOR_END40_EXITSTUB]], label [[FOR_INCR41:%.*]], !dbg [[DBG22]]
; CHECK:       for.incr41:
; CHECK-NEXT:    [[LOOP_01:%.*]] = phi i64 [ [[TMP17:%.*]], [[FOR_INCR41]] ], [ [[LOOP_01_UNR]], [[FOR_INCR41_PROL_LOOPEXIT]] ]
; CHECK-NEXT:    [[TMP8:%.*]] = udiv i64 [[LOOP_01]], 9, !dbg [[DBG22]]
; CHECK-NEXT:    [[DOTNEG:%.*]] = mul i64 [[TMP8]], 4294967287, !dbg [[DBG22]]
; CHECK-NEXT:    [[TMP9:%.*]] = add i64 [[DOTNEG]], [[LOOP_01]], !dbg [[DBG22]]
; CHECK-NEXT:    [[TMP10:%.*]] = trunc i64 [[TMP8]] to i32, !dbg [[DBG22]]
; CHECK-NEXT:    store i32 [[TMP10]], ptr [[I3]], align 4, !dbg [[DBG22]]
; CHECK-NEXT:    [[TMP11:%.*]] = trunc i64 [[TMP9]] to i32, !dbg [[DBG22]]
; CHECK-NEXT:    store i32 [[TMP11]], ptr [[J4]], align 4, !dbg [[DBG22]]
; CHECK-NEXT:    [[TMP12:%.*]] = add nuw i64 [[LOOP_01]], 1, !dbg [[DBG22]]
; CHECK-NEXT:    [[TMP13:%.*]] = udiv i64 [[TMP12]], 9, !dbg [[DBG22]]
; CHECK-NEXT:    [[DOTNEG_1:%.*]] = mul i64 [[TMP13]], 4294967287, !dbg [[DBG22]]
; CHECK-NEXT:    [[TMP14:%.*]] = add i64 [[DOTNEG_1]], [[TMP12]], !dbg [[DBG22]]
; CHECK-NEXT:    [[TMP15:%.*]] = trunc i64 [[TMP13]] to i32, !dbg [[DBG22]]
; CHECK-NEXT:    store i32 [[TMP15]], ptr [[I3]], align 4, !dbg [[DBG22]]
; CHECK-NEXT:    [[TMP16:%.*]] = trunc i64 [[TMP14]] to i32, !dbg [[DBG22]]
; CHECK-NEXT:    store i32 [[TMP16]], ptr [[J4]], align 4, !dbg [[DBG22]]
; CHECK-NEXT:    [[TMP17]] = add nuw i64 [[LOOP_01]], 2, !dbg [[DBG22]]
; CHECK-NEXT:    [[EXITCOND_NOT_1:%.*]] = icmp eq i64 [[TMP17]], [[LOOP_BOUNDS_8_VAL]], !dbg [[DBG22]]
; CHECK-NEXT:    br i1 [[EXITCOND_NOT_1]], label [[FOR_END40_EXITSTUB]], label [[FOR_INCR41]], !dbg [[DBG22]]
; CHECK:       for.end40.exitStub:
; CHECK-NEXT:    ret void
;
;
; CHECK-LABEL: define {{[^@]+}}@nanos6_ol_task_region_main.15
; CHECK-SAME: (ptr writeonly captures(none) [[TASK_ARGS:%.*]], ptr readonly captures(none) [[LOOP_BOUNDS:%.*]], ptr readnone captures(none) [[ADDRESS_TRANSLATION_TABLE:%.*]]) #[[ATTR2]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[GEP_J4:%.*]] = getelementptr i8, ptr [[TASK_ARGS]], i64 4
; CHECK-NEXT:    [[LOOP_BOUNDS_VAL:%.*]] = load i64, ptr [[LOOP_BOUNDS]], align 8
; CHECK-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr [[LOOP_BOUNDS]], i64 8
; CHECK-NEXT:    [[LOOP_BOUNDS_VAL1:%.*]] = load i64, ptr [[TMP0]], align 8
; CHECK-NEXT:    tail call fastcc void @nanos6_unpacked_task_region_main.14(ptr [[TASK_ARGS]], ptr [[GEP_J4]], i64 [[LOOP_BOUNDS_VAL]], i64 [[LOOP_BOUNDS_VAL1]])
; CHECK-NEXT:    ret void
;
;
; CHECK-LABEL: define {{[^@]+}}@nanos6_unpacked_task_region_main.24
; CHECK-SAME: (ptr writeonly captures(none) initializes((0, 4)) [[I5:%.*]], ptr writeonly captures(none) [[J6:%.*]], i64 [[LOOP_BOUNDS_0_VAL:%.*]], i64 [[LOOP_BOUNDS_8_VAL:%.*]]) unnamed_addr #[[ATTR1]] !dbg [[DBG23:![0-9]+]] {
; CHECK-NEXT:  newFuncRoot:
; CHECK-NEXT:    store i32 9, ptr [[I5]], align 4, !dbg [[DBG24:![0-9]+]]
; CHECK-NEXT:    [[TMP0:%.*]] = icmp ult i64 [[LOOP_BOUNDS_0_VAL]], [[LOOP_BOUNDS_8_VAL]], !dbg [[DBG24]]
; CHECK-NEXT:    br i1 [[TMP0]], label [[FOR_INCR59_PREHEADER:%.*]], label [[FOR_END58_EXITSTUB:%.*]], !dbg [[DBG24]]
; CHECK:       for.incr59.preheader:
; CHECK-NEXT:    [[TMP1:%.*]] = sub nuw i64 [[LOOP_BOUNDS_8_VAL]], [[LOOP_BOUNDS_0_VAL]], !dbg [[DBG24]]
; CHECK-NEXT:    [[DOTNEG2:%.*]] = add i64 [[LOOP_BOUNDS_0_VAL]], 1, !dbg [[DBG24]]
; CHECK-NEXT:    [[XTRAITER:%.*]] = and i64 [[TMP1]], 1, !dbg [[DBG24]]
; CHECK-NEXT:    [[LCMP_MOD_NOT:%.*]] = icmp eq i64 [[XTRAITER]], 0, !dbg [[DBG24]]
; CHECK-NEXT:    br i1 [[LCMP_MOD_NOT]], label [[FOR_INCR59_PROL_LOOPEXIT:%.*]], label [[FOR_INCR59_PROL:%.*]], !dbg [[DBG24]]
; CHECK:       for.incr59.prol:
; CHECK-NEXT:    [[TMP2:%.*]] = udiv i64 [[LOOP_BOUNDS_0_VAL]], 10, !dbg [[DBG24]]
; CHECK-NEXT:    [[DOTNEG_PROL:%.*]] = mul i64 [[TMP2]], 4294967286, !dbg [[DBG24]]
; CHECK-NEXT:    [[TMP3:%.*]] = add i64 [[DOTNEG_PROL]], [[LOOP_BOUNDS_0_VAL]], !dbg [[DBG24]]
; CHECK-NEXT:    [[TMP4:%.*]] = trunc i64 [[TMP2]] to i32, !dbg [[DBG24]]
; CHECK-NEXT:    store i32 [[TMP4]], ptr [[I5]], align 4, !dbg [[DBG24]]
; CHECK-NEXT:    [[TMP5:%.*]] = trunc i64 [[TMP3]] to i32, !dbg [[DBG24]]
; CHECK-NEXT:    store i32 [[TMP5]], ptr [[J6]], align 4, !dbg [[DBG24]]
; CHECK-NEXT:    [[TMP6:%.*]] = add nuw i64 [[LOOP_BOUNDS_0_VAL]], 1, !dbg [[DBG24]]
; CHECK-NEXT:    br label [[FOR_INCR59_PROL_LOOPEXIT]], !dbg [[DBG24]]
; CHECK:       for.incr59.prol.loopexit:
; CHECK-NEXT:    [[LOOP_01_UNR:%.*]] = phi i64 [ [[LOOP_BOUNDS_0_VAL]], [[FOR_INCR59_PREHEADER]] ], [ [[TMP6]], [[FOR_INCR59_PROL]] ]
; CHECK-NEXT:    [[TMP7:%.*]] = icmp eq i64 [[LOOP_BOUNDS_8_VAL]], [[DOTNEG2]], !dbg [[DBG24]]
; CHECK-NEXT:    br i1 [[TMP7]], label [[FOR_END58_EXITSTUB]], label [[FOR_INCR59:%.*]], !dbg [[DBG24]]
; CHECK:       for.incr59:
; CHECK-NEXT:    [[LOOP_01:%.*]] = phi i64 [ [[TMP17:%.*]], [[FOR_INCR59]] ], [ [[LOOP_01_UNR]], [[FOR_INCR59_PROL_LOOPEXIT]] ]
; CHECK-NEXT:    [[TMP8:%.*]] = udiv i64 [[LOOP_01]], 10, !dbg [[DBG24]]
; CHECK-NEXT:    [[DOTNEG:%.*]] = mul i64 [[TMP8]], 4294967286, !dbg [[DBG24]]
; CHECK-NEXT:    [[TMP9:%.*]] = add i64 [[DOTNEG]], [[LOOP_01]], !dbg [[DBG24]]
; CHECK-NEXT:    [[TMP10:%.*]] = trunc i64 [[TMP8]] to i32, !dbg [[DBG24]]
; CHECK-NEXT:    store i32 [[TMP10]], ptr [[I5]], align 4, !dbg [[DBG24]]
; CHECK-NEXT:    [[TMP11:%.*]] = trunc i64 [[TMP9]] to i32, !dbg [[DBG24]]
; CHECK-NEXT:    store i32 [[TMP11]], ptr [[J6]], align 4, !dbg [[DBG24]]
; CHECK-NEXT:    [[TMP12:%.*]] = add nuw i64 [[LOOP_01]], 1, !dbg [[DBG24]]
; CHECK-NEXT:    [[TMP13:%.*]] = udiv i64 [[TMP12]], 10, !dbg [[DBG24]]
; CHECK-NEXT:    [[DOTNEG_1:%.*]] = mul i64 [[TMP13]], 4294967286, !dbg [[DBG24]]
; CHECK-NEXT:    [[TMP14:%.*]] = add i64 [[DOTNEG_1]], [[TMP12]], !dbg [[DBG24]]
; CHECK-NEXT:    [[TMP15:%.*]] = trunc i64 [[TMP13]] to i32, !dbg [[DBG24]]
; CHECK-NEXT:    store i32 [[TMP15]], ptr [[I5]], align 4, !dbg [[DBG24]]
; CHECK-NEXT:    [[TMP16:%.*]] = trunc i64 [[TMP14]] to i32, !dbg [[DBG24]]
; CHECK-NEXT:    store i32 [[TMP16]], ptr [[J6]], align 4, !dbg [[DBG24]]
; CHECK-NEXT:    [[TMP17]] = add nuw i64 [[LOOP_01]], 2, !dbg [[DBG24]]
; CHECK-NEXT:    [[EXITCOND_NOT_1:%.*]] = icmp eq i64 [[TMP17]], [[LOOP_BOUNDS_8_VAL]], !dbg [[DBG24]]
; CHECK-NEXT:    br i1 [[EXITCOND_NOT_1]], label [[FOR_END58_EXITSTUB]], label [[FOR_INCR59]], !dbg [[DBG24]]
; CHECK:       for.end58.exitStub:
; CHECK-NEXT:    ret void
;
;
; CHECK-LABEL: define {{[^@]+}}@nanos6_ol_task_region_main.25
; CHECK-SAME: (ptr writeonly captures(none) [[TASK_ARGS:%.*]], ptr readonly captures(none) [[LOOP_BOUNDS:%.*]], ptr readnone captures(none) [[ADDRESS_TRANSLATION_TABLE:%.*]]) #[[ATTR2]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[GEP_J6:%.*]] = getelementptr i8, ptr [[TASK_ARGS]], i64 4
; CHECK-NEXT:    [[LOOP_BOUNDS_VAL:%.*]] = load i64, ptr [[LOOP_BOUNDS]], align 8
; CHECK-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr [[LOOP_BOUNDS]], i64 8
; CHECK-NEXT:    [[LOOP_BOUNDS_VAL1:%.*]] = load i64, ptr [[TMP0]], align 8
; CHECK-NEXT:    tail call fastcc void @nanos6_unpacked_task_region_main.24(ptr [[TASK_ARGS]], ptr [[GEP_J6]], i64 [[LOOP_BOUNDS_VAL]], i64 [[LOOP_BOUNDS_VAL1]])
; CHECK-NEXT:    ret void
;
