; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt %s -ompss-2 -S | FileCheck %s
; ModuleID = 'task_array.cpp'
source_filename = "task_array.cpp"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

%struct.S = type { i32 }

; void pod_array() {
;     int array[10];
;     #pragma oss task private(array)
;     {}
;     #pragma oss task firstprivate(array)
;     {}
; }
;
; struct S {
;     int x;
;     ~S();
; };
;
; void non_pod_array() {
;     S array[10];
;     #pragma oss task private(array)
;     {}
;     #pragma oss task firstprivate(array)
;     {}
; }

; Function Attrs: noinline nounwind optnone uwtable
define dso_local void @_Z9pod_arrayv() #0 !dbg !6 {
; CHECK-LABEL: @_Z9pod_arrayv(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[ARRAY:%.*]] = alloca [10 x i32], align 16
; CHECK-NEXT:    br label [[FINAL_COND:%.*]], [[DBG8:!dbg !.*]]
; CHECK:       codeRepl:
; CHECK-NEXT:    [[TMP0:%.*]] = alloca %nanos6_task_args__Z9pod_arrayv0*, align 8, [[DBG8]]
; CHECK-NEXT:    [[TMP1:%.*]] = bitcast %nanos6_task_args__Z9pod_arrayv0** [[TMP0]] to i8**, [[DBG8]]
; CHECK-NEXT:    [[TMP2:%.*]] = alloca i8*, align 8, [[DBG8]]
; CHECK-NEXT:    [[NUM_DEPS:%.*]] = alloca i64, align 8, [[DBG8]]
; CHECK-NEXT:    store i64 0, i64* [[NUM_DEPS]], align 8, [[DBG8]]
; CHECK-NEXT:    [[TMP3:%.*]] = load i64, i64* [[NUM_DEPS]], align 8, [[DBG8]]
; CHECK-NEXT:    call void @nanos6_create_task(%nanos6_task_info_t* @task_info_var__Z9pod_arrayv0, %nanos6_task_invocation_info_t* @task_invocation_info__Z9pod_arrayv0, i64 48, i8** [[TMP1]], i8** [[TMP2]], i64 0, i64 [[TMP3]]), [[DBG8]]
; CHECK-NEXT:    [[TMP4:%.*]] = load %nanos6_task_args__Z9pod_arrayv0*, %nanos6_task_args__Z9pod_arrayv0** [[TMP0]], align 8, [[DBG8]]
; CHECK-NEXT:    [[TMP5:%.*]] = bitcast %nanos6_task_args__Z9pod_arrayv0* [[TMP4]] to i8*, [[DBG8]]
; CHECK-NEXT:    [[ARGS_END:%.*]] = getelementptr i8, i8* [[TMP5]], i64 48, [[DBG8]]
; CHECK-NEXT:    [[TMP6:%.*]] = load i8*, i8** [[TMP2]], align 8, [[DBG8]]
; CHECK-NEXT:    call void @nanos6_submit_task(i8* [[TMP6]]), [[DBG8]]
; CHECK-NEXT:    br label [[FINAL_END:%.*]], [[DBG8]]
; CHECK:       final.end:
; CHECK-NEXT:    br label [[FINAL_COND2:%.*]], [[DBG9:!dbg !.*]]
; CHECK:       codeRepl4:
; CHECK-NEXT:    [[TMP7:%.*]] = alloca %nanos6_task_args__Z9pod_arrayv1*, align 8, [[DBG9]]
; CHECK-NEXT:    [[TMP8:%.*]] = bitcast %nanos6_task_args__Z9pod_arrayv1** [[TMP7]] to i8**, [[DBG9]]
; CHECK-NEXT:    [[TMP9:%.*]] = alloca i8*, align 8, [[DBG9]]
; CHECK-NEXT:    [[NUM_DEPS5:%.*]] = alloca i64, align 8, [[DBG9]]
; CHECK-NEXT:    store i64 0, i64* [[NUM_DEPS5]], align 8, [[DBG9]]
; CHECK-NEXT:    [[TMP10:%.*]] = load i64, i64* [[NUM_DEPS5]], align 8, [[DBG9]]
; CHECK-NEXT:    call void @nanos6_create_task(%nanos6_task_info_t* @task_info_var__Z9pod_arrayv1, %nanos6_task_invocation_info_t* @task_invocation_info__Z9pod_arrayv1, i64 48, i8** [[TMP8]], i8** [[TMP9]], i64 0, i64 [[TMP10]]), [[DBG9]]
; CHECK-NEXT:    [[TMP11:%.*]] = load %nanos6_task_args__Z9pod_arrayv1*, %nanos6_task_args__Z9pod_arrayv1** [[TMP7]], align 8, [[DBG9]]
; CHECK-NEXT:    [[TMP12:%.*]] = bitcast %nanos6_task_args__Z9pod_arrayv1* [[TMP11]] to i8*, [[DBG9]]
; CHECK-NEXT:    [[ARGS_END6:%.*]] = getelementptr i8, i8* [[TMP12]], i64 48, [[DBG9]]
; CHECK-NEXT:    [[GEP_ARRAY:%.*]] = getelementptr [[NANOS6_TASK_ARGS__Z9POD_ARRAYV1:%.*]], %nanos6_task_args__Z9pod_arrayv1* [[TMP11]], i32 0, i32 0, [[DBG9]]
; CHECK-NEXT:    [[TMP13:%.*]] = bitcast [10 x i32]* [[GEP_ARRAY]] to i8*, [[DBG9]]
; CHECK-NEXT:    [[TMP14:%.*]] = bitcast [10 x i32]* [[ARRAY]] to i8*, [[DBG9]]
; CHECK-NEXT:    call void @llvm.memcpy.p0i8.p0i8.i64(i8* align 4 [[TMP13]], i8* align 4 [[TMP14]], i64 40, i1 false), [[DBG9]]
; CHECK-NEXT:    [[TMP15:%.*]] = load i8*, i8** [[TMP9]], align 8, [[DBG9]]
; CHECK-NEXT:    call void @nanos6_submit_task(i8* [[TMP15]]), [[DBG9]]
; CHECK-NEXT:    br label [[FINAL_END1:%.*]], [[DBG9]]
; CHECK:       final.end1:
; CHECK-NEXT:    ret void, [[DBG10:!dbg !.*]]
; CHECK:       final.then:
; CHECK-NEXT:    br label [[FINAL_END]], [[DBG9]]
; CHECK:       final.then3:
; CHECK-NEXT:    br label [[FINAL_END1]], [[DBG10]]
; CHECK:       final.cond:
; CHECK-NEXT:    [[TMP16:%.*]] = call i32 @nanos6_in_final(), [[DBG8]]
; CHECK-NEXT:    [[TMP17:%.*]] = icmp ne i32 [[TMP16]], 0, [[DBG8]]
; CHECK-NEXT:    br i1 [[TMP17]], label [[FINAL_THEN:%.*]], label [[CODEREPL:%.*]], [[DBG8]]
; CHECK:       final.cond2:
; CHECK-NEXT:    [[TMP18:%.*]] = call i32 @nanos6_in_final(), [[DBG9]]
; CHECK-NEXT:    [[TMP19:%.*]] = icmp ne i32 [[TMP18]], 0, [[DBG9]]
; CHECK-NEXT:    br i1 [[TMP19]], label [[FINAL_THEN3:%.*]], label [[CODEREPL4:%.*]], [[DBG9]]
;
entry:
  %array = alloca [10 x i32], align 16
  %0 = call token @llvm.directive.region.entry() [ "DIR.OSS"([5 x i8] c"TASK\00"), "QUAL.OSS.PRIVATE"([10 x i32]* %array) ], !dbg !8
  call void @llvm.directive.region.exit(token %0), !dbg !9
  %1 = call token @llvm.directive.region.entry() [ "DIR.OSS"([5 x i8] c"TASK\00"), "QUAL.OSS.FIRSTPRIVATE"([10 x i32]* %array) ], !dbg !10
  call void @llvm.directive.region.exit(token %1), !dbg !11
  ret void, !dbg !12
}

; Function Attrs: nounwind
declare token @llvm.directive.region.entry() #1

; Function Attrs: nounwind
declare void @llvm.directive.region.exit(token) #1

; Function Attrs: noinline nounwind optnone uwtable
define dso_local void @_Z13non_pod_arrayv() #0 !dbg !13 {
; CHECK-LABEL: @_Z13non_pod_arrayv(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[ARRAY:%.*]] = alloca [10 x %struct.S], align 16
; CHECK-NEXT:    br label [[FINAL_COND:%.*]], [[DBG12:!dbg !.*]]
; CHECK:       codeRepl:
; CHECK-NEXT:    [[TMP0:%.*]] = alloca %nanos6_task_args__Z13non_pod_arrayv0*, align 8, [[DBG12]]
; CHECK-NEXT:    [[TMP1:%.*]] = bitcast %nanos6_task_args__Z13non_pod_arrayv0** [[TMP0]] to i8**, [[DBG12]]
; CHECK-NEXT:    [[TMP2:%.*]] = alloca i8*, align 8, [[DBG12]]
; CHECK-NEXT:    [[NUM_DEPS:%.*]] = alloca i64, align 8, [[DBG12]]
; CHECK-NEXT:    store i64 0, i64* [[NUM_DEPS]], align 8, [[DBG12]]
; CHECK-NEXT:    [[TMP3:%.*]] = load i64, i64* [[NUM_DEPS]], align 8, [[DBG12]]
; CHECK-NEXT:    call void @nanos6_create_task(%nanos6_task_info_t* @task_info_var__Z13non_pod_arrayv0, %nanos6_task_invocation_info_t* @task_invocation_info__Z13non_pod_arrayv0, i64 48, i8** [[TMP1]], i8** [[TMP2]], i64 0, i64 [[TMP3]]), [[DBG12]]
; CHECK-NEXT:    [[TMP4:%.*]] = load %nanos6_task_args__Z13non_pod_arrayv0*, %nanos6_task_args__Z13non_pod_arrayv0** [[TMP0]], align 8, [[DBG12]]
; CHECK-NEXT:    [[TMP5:%.*]] = bitcast %nanos6_task_args__Z13non_pod_arrayv0* [[TMP4]] to i8*, [[DBG12]]
; CHECK-NEXT:    [[ARGS_END:%.*]] = getelementptr i8, i8* [[TMP5]], i64 48, [[DBG12]]
; CHECK-NEXT:    [[GEP_ARRAY:%.*]] = getelementptr [[NANOS6_TASK_ARGS__Z13NON_POD_ARRAYV0:%.*]], %nanos6_task_args__Z13non_pod_arrayv0* [[TMP4]], i32 0, i32 0, [[DBG12]]
; CHECK-NEXT:    [[TMP6:%.*]] = bitcast [10 x %struct.S]* [[GEP_ARRAY]] to %struct.S*, [[DBG12]]
; CHECK-NEXT:    call void @oss_ctor_ZN1SC1Ev(%struct.S* [[TMP6]], i64 10), [[DBG12]]
; CHECK-NEXT:    [[TMP7:%.*]] = load i8*, i8** [[TMP2]], align 8, [[DBG12]]
; CHECK-NEXT:    call void @nanos6_submit_task(i8* [[TMP7]]), [[DBG12]]
; CHECK-NEXT:    br label [[FINAL_END:%.*]], [[DBG12]]
; CHECK:       final.end:
; CHECK-NEXT:    br label [[FINAL_COND2:%.*]], [[DBG13:!dbg !.*]]
; CHECK:       codeRepl4:
; CHECK-NEXT:    [[TMP8:%.*]] = alloca %nanos6_task_args__Z13non_pod_arrayv1*, align 8, [[DBG13]]
; CHECK-NEXT:    [[TMP9:%.*]] = bitcast %nanos6_task_args__Z13non_pod_arrayv1** [[TMP8]] to i8**, [[DBG13]]
; CHECK-NEXT:    [[TMP10:%.*]] = alloca i8*, align 8, [[DBG13]]
; CHECK-NEXT:    [[NUM_DEPS5:%.*]] = alloca i64, align 8, [[DBG13]]
; CHECK-NEXT:    store i64 0, i64* [[NUM_DEPS5]], align 8, [[DBG13]]
; CHECK-NEXT:    [[TMP11:%.*]] = load i64, i64* [[NUM_DEPS5]], align 8, [[DBG13]]
; CHECK-NEXT:    call void @nanos6_create_task(%nanos6_task_info_t* @task_info_var__Z13non_pod_arrayv1, %nanos6_task_invocation_info_t* @task_invocation_info__Z13non_pod_arrayv1, i64 48, i8** [[TMP9]], i8** [[TMP10]], i64 0, i64 [[TMP11]]), [[DBG13]]
; CHECK-NEXT:    [[TMP12:%.*]] = load %nanos6_task_args__Z13non_pod_arrayv1*, %nanos6_task_args__Z13non_pod_arrayv1** [[TMP8]], align 8, [[DBG13]]
; CHECK-NEXT:    [[TMP13:%.*]] = bitcast %nanos6_task_args__Z13non_pod_arrayv1* [[TMP12]] to i8*, [[DBG13]]
; CHECK-NEXT:    [[ARGS_END6:%.*]] = getelementptr i8, i8* [[TMP13]], i64 48, [[DBG13]]
; CHECK-NEXT:    [[GEP_ARRAY7:%.*]] = getelementptr [[NANOS6_TASK_ARGS__Z13NON_POD_ARRAYV1:%.*]], %nanos6_task_args__Z13non_pod_arrayv1* [[TMP12]], i32 0, i32 0, [[DBG13]]
; CHECK-NEXT:    [[TMP14:%.*]] = bitcast [10 x %struct.S]* [[GEP_ARRAY7]] to %struct.S*, [[DBG13]]
; CHECK-NEXT:    [[TMP15:%.*]] = bitcast [10 x %struct.S]* [[ARRAY]] to %struct.S*, [[DBG13]]
; CHECK-NEXT:    call void @oss_copy_ctor_ZN1SC1ERKS_(%struct.S* [[TMP15]], %struct.S* [[TMP14]], i64 10), [[DBG13]]
; CHECK-NEXT:    [[TMP16:%.*]] = load i8*, i8** [[TMP10]], align 8, [[DBG13]]
; CHECK-NEXT:    call void @nanos6_submit_task(i8* [[TMP16]]), [[DBG13]]
; CHECK-NEXT:    br label [[FINAL_END1:%.*]], [[DBG13]]
; CHECK:       final.end1:
; CHECK-NEXT:    [[ARRAY_BEGIN:%.*]] = getelementptr inbounds [10 x %struct.S], [10 x %struct.S]* [[ARRAY]], i32 0, i32 0, [[DBG14:!dbg !.*]]
; CHECK-NEXT:    [[TMP17:%.*]] = getelementptr inbounds [[STRUCT_S:%.*]], %struct.S* [[ARRAY_BEGIN]], i64 10, [[DBG14]]
; CHECK-NEXT:    br label [[ARRAYDESTROY_BODY:%.*]], [[DBG14]]
; CHECK:       arraydestroy.body:
; CHECK-NEXT:    [[ARRAYDESTROY_ELEMENTPAST:%.*]] = phi %struct.S* [ [[TMP17]], [[FINAL_END1]] ], [ [[ARRAYDESTROY_ELEMENT:%.*]], [[ARRAYDESTROY_BODY]] ], [[DBG14]]
; CHECK-NEXT:    [[ARRAYDESTROY_ELEMENT]] = getelementptr inbounds [[STRUCT_S]], %struct.S* [[ARRAYDESTROY_ELEMENTPAST]], i64 -1, [[DBG14]]
; CHECK-NEXT:    call void @_ZN1SD1Ev(%struct.S* [[ARRAYDESTROY_ELEMENT]]) [[ATTR1:#.*]], [[DBG14]]
; CHECK-NEXT:    [[ARRAYDESTROY_DONE:%.*]] = icmp eq %struct.S* [[ARRAYDESTROY_ELEMENT]], [[ARRAY_BEGIN]], [[DBG14]]
; CHECK-NEXT:    br i1 [[ARRAYDESTROY_DONE]], label [[ARRAYDESTROY_DONE1:%.*]], label [[ARRAYDESTROY_BODY]], [[DBG14]]
; CHECK:       arraydestroy.done1:
; CHECK-NEXT:    ret void, [[DBG14]]
; CHECK:       final.then:
; CHECK-NEXT:    br label [[FINAL_END]], [[DBG13]]
; CHECK:       final.then3:
; CHECK-NEXT:    br label [[FINAL_END1]], [[DBG14]]
; CHECK:       final.cond:
; CHECK-NEXT:    [[TMP18:%.*]] = call i32 @nanos6_in_final(), [[DBG12]]
; CHECK-NEXT:    [[TMP19:%.*]] = icmp ne i32 [[TMP18]], 0, [[DBG12]]
; CHECK-NEXT:    br i1 [[TMP19]], label [[FINAL_THEN:%.*]], label [[CODEREPL:%.*]], [[DBG12]]
; CHECK:       final.cond2:
; CHECK-NEXT:    [[TMP20:%.*]] = call i32 @nanos6_in_final(), [[DBG13]]
; CHECK-NEXT:    [[TMP21:%.*]] = icmp ne i32 [[TMP20]], 0, [[DBG13]]
; CHECK-NEXT:    br i1 [[TMP21]], label [[FINAL_THEN3:%.*]], label [[CODEREPL4:%.*]], [[DBG13]]
;
entry:
  %array = alloca [10 x %struct.S], align 16
  %0 = call token @llvm.directive.region.entry() [ "DIR.OSS"([5 x i8] c"TASK\00"), "QUAL.OSS.PRIVATE"([10 x %struct.S]* %array), "QUAL.OSS.INIT"([10 x %struct.S]* %array, void (%struct.S*, i64)* @oss_ctor_ZN1SC1Ev), "QUAL.OSS.DEINIT"([10 x %struct.S]* %array, void (%struct.S*, i64)* @oss_dtor_ZN1SD1Ev) ], !dbg !14
  call void @llvm.directive.region.exit(token %0), !dbg !15
  %1 = call token @llvm.directive.region.entry() [ "DIR.OSS"([5 x i8] c"TASK\00"), "QUAL.OSS.FIRSTPRIVATE"([10 x %struct.S]* %array), "QUAL.OSS.COPY"([10 x %struct.S]* %array, void (%struct.S*, %struct.S*, i64)* @oss_copy_ctor_ZN1SC1ERKS_), "QUAL.OSS.DEINIT"([10 x %struct.S]* %array, void (%struct.S*, i64)* @oss_dtor_ZN1SD1Ev) ], !dbg !16
  call void @llvm.directive.region.exit(token %1), !dbg !17
  %array.begin = getelementptr inbounds [10 x %struct.S], [10 x %struct.S]* %array, i32 0, i32 0, !dbg !18
  %2 = getelementptr inbounds %struct.S, %struct.S* %array.begin, i64 10, !dbg !18
  br label %arraydestroy.body, !dbg !18

arraydestroy.body:                                ; preds = %arraydestroy.body, %entry
  %arraydestroy.elementPast = phi %struct.S* [ %2, %entry ], [ %arraydestroy.element, %arraydestroy.body ], !dbg !18
  %arraydestroy.element = getelementptr inbounds %struct.S, %struct.S* %arraydestroy.elementPast, i64 -1, !dbg !18
  call void @_ZN1SD1Ev(%struct.S* %arraydestroy.element) #1, !dbg !18
  %arraydestroy.done = icmp eq %struct.S* %arraydestroy.element, %array.begin, !dbg !18
  br i1 %arraydestroy.done, label %arraydestroy.done1, label %arraydestroy.body, !dbg !18

arraydestroy.done1:                               ; preds = %arraydestroy.body
  ret void, !dbg !18
}


declare void @oss_ctor_ZN1SC1Ev(%struct.S* %0, i64 %1)

; Function Attrs: nounwind
declare dso_local void @_ZN1SD1Ev(%struct.S*) unnamed_addr #3

; Function Attrs: noinline norecurse uwtable
declare void @oss_dtor_ZN1SD1Ev(%struct.S* %0, i64 %1)

declare void @oss_copy_ctor_ZN1SC1ERKS_(%struct.S* %0, %struct.S* %1, i64 %2)

; CHECK: define internal void @nanos6_unpacked_destroy__Z13non_pod_arrayv0([10 x %struct.S]* %array) {
; CHECK: entry:
; CHECK-NEXT:   %0 = bitcast [10 x %struct.S]* %array to %struct.S*
; CHECK-NEXT:   call void @oss_dtor_ZN1SD1Ev(%struct.S* %0, i64 10)
; CHECK-NEXT:   ret void
; CHECK-NEXT: }

; CHECK: define internal void @nanos6_unpacked_destroy__Z13non_pod_arrayv1([10 x %struct.S]* %array) {
; CHECK-NEXT: entry:
; CHECK-NEXT:   %0 = bitcast [10 x %struct.S]* %array to %struct.S*
; CHECK-NEXT:   call void @oss_dtor_ZN1SD1Ev(%struct.S* %0, i64 10)
; CHECK-NEXT:   ret void
; CHECK-NEXT: }

; Function Attrs: argmemonly nounwind willreturn
declare void @llvm.memcpy.p0i8.p0i8.i64(i8* noalias nocapture writeonly, i8* noalias nocapture readonly, i64, i1 immarg) #4

attributes #0 = { noinline nounwind optnone uwtable "correctly-rounded-divide-sqrt-fp-math"="false" "disable-tail-calls"="false" "frame-pointer"="all" "less-precise-fpmad"="false" "min-legal-vector-width"="0" "no-infs-fp-math"="false" "no-jump-tables"="false" "no-nans-fp-math"="false" "no-signed-zeros-fp-math"="false" "no-trapping-math"="false" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "unsafe-fp-math"="false" "use-soft-float"="false" }
attributes #1 = { nounwind }
attributes #2 = { noinline norecurse uwtable "correctly-rounded-divide-sqrt-fp-math"="false" "disable-tail-calls"="false" "frame-pointer"="all" "less-precise-fpmad"="false" "min-legal-vector-width"="0" "no-infs-fp-math"="false" "no-jump-tables"="false" "no-nans-fp-math"="false" "no-signed-zeros-fp-math"="false" "no-trapping-math"="false" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "unsafe-fp-math"="false" "use-soft-float"="false" }
attributes #3 = { nounwind "correctly-rounded-divide-sqrt-fp-math"="false" "disable-tail-calls"="false" "frame-pointer"="all" "less-precise-fpmad"="false" "no-infs-fp-math"="false" "no-nans-fp-math"="false" "no-signed-zeros-fp-math"="false" "no-trapping-math"="false" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "unsafe-fp-math"="false" "use-soft-float"="false" }
attributes #4 = { argmemonly nounwind willreturn }

!llvm.dbg.cu = !{!0}
!llvm.module.flags = !{!3, !4}
!llvm.ident = !{!5}

!0 = distinct !DICompileUnit(language: DW_LANG_C_plus_plus_14, file: !1, producer: "", isOptimized: false, runtimeVersion: 0, emissionKind: NoDebug, enums: !2, splitDebugInlining: false, nameTableKind: None)
!1 = !DIFile(filename: "task_array.cpp", directory: "")
!2 = !{}
!3 = !{i32 2, !"Debug Info Version", i32 3}
!4 = !{i32 1, !"wchar_size", i32 4}
!5 = !{!""}
!6 = distinct !DISubprogram(name: "pod_array", scope: !1, file: !1, line: 1, type: !7, scopeLine: 1, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !0, retainedNodes: !2)
!7 = !DISubroutineType(types: !2)
!8 = !DILocation(line: 3, column: 13, scope: !6)
!9 = !DILocation(line: 4, column: 6, scope: !6)
!10 = !DILocation(line: 5, column: 13, scope: !6)
!11 = !DILocation(line: 6, column: 6, scope: !6)
!12 = !DILocation(line: 7, column: 1, scope: !6)
!13 = distinct !DISubprogram(name: "non_pod_array", scope: !1, file: !1, line: 14, type: !7, scopeLine: 14, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !0, retainedNodes: !2)
!14 = !DILocation(line: 16, column: 13, scope: !13)
!15 = !DILocation(line: 17, column: 6, scope: !13)
!16 = !DILocation(line: 18, column: 13, scope: !13)
!17 = !DILocation(line: 19, column: 6, scope: !13)
!18 = !DILocation(line: 20, column: 1, scope: !13)
!19 = distinct !DISubprogram(name: "S", scope: !1, file: !1, line: 9, type: !7, scopeLine: 9, flags: DIFlagArtificial | DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !0, retainedNodes: !2)
!20 = !DILocation(line: 9, column: 8, scope: !19)
!21 = distinct !DISubprogram(linkageName: "oss_ctor_ZN1SC1Ev", scope: !1, file: !1, type: !7, flags: DIFlagArtificial, spFlags: DISPFlagLocalToUnit | DISPFlagDefinition, unit: !0, retainedNodes: !2)
!22 = !DILocation(line: 0, scope: !21)
!23 = !DILocation(line: 16, column: 30, scope: !21)
!24 = distinct !DISubprogram(linkageName: "oss_dtor_ZN1SD1Ev", scope: !1, file: !1, type: !7, flags: DIFlagArtificial, spFlags: DISPFlagLocalToUnit | DISPFlagDefinition, unit: !0, retainedNodes: !2)
!25 = !DILocation(line: 0, scope: !24)
!26 = distinct !DISubprogram(name: "S", scope: !1, file: !1, line: 9, type: !7, scopeLine: 9, flags: DIFlagArtificial | DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !0, retainedNodes: !2)
!27 = !DILocation(line: 9, column: 8, scope: !26)
!28 = distinct !DISubprogram(linkageName: "oss_copy_ctor_ZN1SC1ERKS_", scope: !1, file: !1, type: !7, flags: DIFlagArtificial, spFlags: DISPFlagLocalToUnit | DISPFlagDefinition, unit: !0, retainedNodes: !2)
!29 = !DILocation(line: 0, scope: !28)
!30 = !DILocation(line: 18, column: 35, scope: !28)
