; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt %s -passes=ompss-2 -S | FileCheck %s
; RUN: opt %s -passes='ompss-2,default<O3>' -o /dev/null

; TaskArgsVar/TaskPtrVar allocas must land at the very start of the entry
; block — before any call — so that when the inliner later splits entry at a
; call site the allocas remain in the entry block and keep their static-alloca
; semantics.  If they end up in a non-entry block, passes such as
; JumpThreading can duplicate that block, producing two alloca sites joined by
; a phi.  llvm.lifetime.start/end require an alloca (or poison), never a phi,
; so the resulting IR would be invalid and crash LoopVectorize's verifier.

source_filename = "task_alloca_before_call.ll"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

; Inlinable helper called from the entry block of @foo.  When the inliner
; processes @foo it will split the entry block at this call, pushing any
; instructions that follow the call into a new block.  Task allocas placed
; *after* this call would therefore end up in a non-entry block.
define internal i64 @helper(i64 %n) {
; CHECK-LABEL: define internal i64 @helper(
; CHECK-SAME: i64 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[CMP:%.*]] = icmp slt i64 [[N]], 64
; CHECK-NEXT:    [[SEL:%.*]] = select i1 [[CMP]], i64 [[N]], i64 64
; CHECK-NEXT:    ret i64 [[SEL]]
;
entry:
  %cmp = icmp slt i64 %n, 64
  %sel = select i1 %cmp, i64 %n, i64 64
  ret i64 %sel
}

; @foo calls @helper in its entry block and then submits a task.
; The task body only uses values local to the task region (no DSA needed).
; After OmpSs lowering the TaskArgsVar/TaskPtrVar allocas must appear in
; 'entry' BEFORE the call to @helper.
define dso_local void @foo(i64 noundef %n) #0 !dbg !5 {
; CHECK-LABEL: define dso_local void @foo(
; CHECK-SAME: i64 noundef [[N:%.*]]) #[[ATTR0:[0-9]+]] !dbg [[DBG4:![0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[NUM_DEPS:%.*]] = alloca i64, align 8, !dbg [[DBG7:![0-9]+]]
; CHECK-NEXT:    [[TMP0:%.*]] = alloca ptr, align 8, !dbg [[DBG7]]
; CHECK-NEXT:    [[TMP1:%.*]] = alloca ptr, align 8, !dbg [[DBG7]]
; CHECK-NEXT:    [[I_CLONE:%.*]] = alloca i64, align 8
; CHECK-NEXT:    [[BOUND:%.*]] = call i64 @helper(i64 [[N]])
; CHECK-NEXT:    br label %[[FINAL_COND:.*]], !dbg [[DBG7]]
; CHECK:       [[CODEREPL:.*]]:
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr [[TMP1]]), !dbg [[DBG7]]
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr [[TMP0]]), !dbg [[DBG7]]
; CHECK-NEXT:    store i64 0, ptr [[NUM_DEPS]], align 8, !dbg [[DBG7]]
; CHECK-NEXT:    [[TMP2:%.*]] = load i64, ptr [[NUM_DEPS]], align 8, !dbg [[DBG7]]
; CHECK-NEXT:    call void @nanos6_create_task(ptr @task_info_var_foo, ptr @task_invocation_info_foo, ptr null, i64 0, ptr [[TMP1]], ptr [[TMP0]], i64 0, i64 [[TMP2]]), !dbg [[DBG7]]
; CHECK-NEXT:    [[TMP3:%.*]] = load ptr, ptr [[TMP1]], align 8, !dbg [[DBG7]]
; CHECK-NEXT:    [[ARGS_END:%.*]] = getelementptr i8, ptr [[TMP3]], i64 0, !dbg [[DBG7]]
; CHECK-NEXT:    [[TMP4:%.*]] = load ptr, ptr [[TMP0]], align 8, !dbg [[DBG7]]
; CHECK-NEXT:    call void @nanos6_submit_task(ptr [[TMP4]]), !dbg [[DBG7]]
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr [[TMP1]]), !dbg [[DBG7]]
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr [[TMP0]]), !dbg [[DBG7]]
; CHECK-NEXT:    br label %[[FINAL_END:.*]], !dbg [[DBG7]]
; CHECK:       [[FINAL_END]]:
; CHECK-NEXT:    ret void, !dbg [[DBG7]]
; CHECK:       [[FINAL_THEN:.*]]:
; CHECK-NEXT:    store i64 0, ptr [[I_CLONE]], align 8, !dbg [[DBG7]]
; CHECK-NEXT:    br label %[[FOR_COND_CLONE:.*]], !dbg [[DBG7]]
; CHECK:       [[FOR_COND_CLONE]]:
; CHECK-NEXT:    [[I_VAL_CLONE:%.*]] = load i64, ptr [[I_CLONE]], align 8, !dbg [[DBG7]]
; CHECK-NEXT:    [[CMP2_CLONE:%.*]] = icmp slt i64 [[I_VAL_CLONE]], 10, !dbg [[DBG7]]
; CHECK-NEXT:    br i1 [[CMP2_CLONE]], label %[[FOR_BODY_CLONE:.*]], label %[[FOR_END_CLONE:.*]], !dbg [[DBG7]]
; CHECK:       [[FOR_BODY_CLONE]]:
; CHECK-NEXT:    [[INC_CLONE:%.*]] = add nsw i64 [[I_VAL_CLONE]], 1, !dbg [[DBG7]]
; CHECK-NEXT:    store i64 [[INC_CLONE]], ptr [[I_CLONE]], align 8, !dbg [[DBG7]]
; CHECK-NEXT:    br label %[[FOR_COND_CLONE]], !dbg [[DBG7]]
; CHECK:       [[FOR_END_CLONE]]:
; CHECK-NEXT:    br label %[[FINAL_END]], !dbg [[DBG7]]
; CHECK:       [[FINAL_COND]]:
; CHECK-NEXT:    [[TMP5:%.*]] = call i32 @nanos6_in_final(), !dbg [[DBG7]]
; CHECK-NEXT:    [[TMP6:%.*]] = icmp ne i32 [[TMP5]], 0, !dbg [[DBG7]]
; CHECK-NEXT:    br i1 [[TMP6]], label %[[FINAL_THEN]], label %[[CODEREPL]], !dbg [[DBG7]]
;
entry:
  ; Call in entry block — this is the call site the inliner splits at.
  %bound = call i64 @helper(i64 %n)
  ; Task immediately after. Body only touches %i (an alloca inside the region).
  %0 = call token @llvm.directive.region.entry() [ "DIR.OSS"([5 x i8] c"TASK\00") ], !dbg !9
  %i = alloca i64, align 8
  store i64 0, ptr %i, align 8, !dbg !9
  br label %for.cond, !dbg !9

for.cond:
  %i_val = load i64, ptr %i, align 8, !dbg !9
  %cmp2 = icmp slt i64 %i_val, 10, !dbg !9
  br i1 %cmp2, label %for.body, label %for.end, !dbg !9

for.body:
  %inc = add nsw i64 %i_val, 1, !dbg !9
  store i64 %inc, ptr %i, align 8, !dbg !9
  br label %for.cond, !dbg !9

for.end:
  call void @llvm.directive.region.exit(token %0), !dbg !9
  ret void, !dbg !9
}

declare token @llvm.directive.region.entry() #1
declare void @llvm.directive.region.exit(token) #1

attributes #0 = { noinline nounwind uwtable }
attributes #1 = { nounwind }

!llvm.dbg.cu = !{!0}
!llvm.module.flags = !{!2, !3}

!0 = distinct !DICompileUnit(language: DW_LANG_C99, file: !1, producer: "", isOptimized: false, runtimeVersion: 0, emissionKind: NoDebug, splitDebugInlining: false, nameTableKind: None)
!1 = !DIFile(filename: "<stdin>", directory: "")
!2 = !{i32 2, !"Debug Info Version", i32 3}
!3 = !{i32 1, !"wchar_size", i32 4}
!5 = distinct !DISubprogram(name: "foo", scope: !1, file: !1, line: 1, type: !7, scopeLine: 1, spFlags: DISPFlagDefinition, unit: !0, retainedNodes: !8)
!7 = !DISubroutineType(types: !8)
!8 = !{}
!9 = !DILocation(line: 1, column: 1, scope: !5)
;.
; CHECK: [[META0:![0-9]+]] = distinct !DICompileUnit(language: DW_LANG_C99, file: [[META1:![0-9]+]], isOptimized: false, runtimeVersion: 0, emissionKind: NoDebug, splitDebugInlining: false, nameTableKind: None)
; CHECK: [[META1]] = !DIFile(filename: "<stdin>", directory: "")
; CHECK: [[DBG4]] = distinct !DISubprogram(name: "foo", scope: [[META1]], file: [[META1]], line: 1, type: [[META5:![0-9]+]], scopeLine: 1, spFlags: DISPFlagDefinition, unit: [[META0]], retainedNodes: [[META6:![0-9]+]])
; CHECK: [[META5]] = !DISubroutineType(types: [[META6]])
; CHECK: [[META6]] = !{}
; CHECK: [[DBG7]] = !DILocation(line: 1, column: 1, scope: [[DBG4]])
;.
