; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --include-generated-funcs --version 2
; RUN: opt %s -passes=ompss-2-pre -S | FileCheck %s
; ModuleID = 'unreachable_patch1.ll'
source_filename = "unreachable_patch1.ll"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

; C++
; [[noreturn]] void bar();
; void y() {
;   #pragma oss task
;   bar();
; }

$__clang_call_terminate = comdat any

; Function Attrs: mustprogress noinline nounwind optnone uwtable
define dso_local void @_Z1yv() #0 personality ptr @__gxx_personality_v0 !dbg !7 {
entry:
  %0 = call token @llvm.directive.region.entry() [ "DIR.OSS"([5 x i8] c"TASK\00") ], !dbg !10
  invoke void @_Z3barv() #4
          to label %invoke.cont unwind label %terminate.lpad, !dbg !11

invoke.cont:                                      ; preds = %entry
  call void @llvm.directive.region.exit(token %0), !dbg !11
  ret void, !dbg !12

terminate.lpad:                                   ; preds = %entry
  %1 = landingpad { ptr, i32 }
          catch ptr null, !dbg !11
  %2 = extractvalue { ptr, i32 } %1, 0, !dbg !11
  call void @__clang_call_terminate(ptr %2) #5, !dbg !11
  unreachable, !dbg !11
}

; Function Attrs: nounwind
declare token @llvm.directive.region.entry() #1

; Function Attrs: nounwind
declare void @llvm.directive.region.exit(token) #1

; Function Attrs: noreturn
declare dso_local void @_Z3barv() #2

declare dso_local i32 @__gxx_personality_v0(...)

; Function Attrs: noinline noreturn nounwind uwtable
define linkonce_odr hidden void @__clang_call_terminate(ptr noundef %0) #3 comdat {
  %2 = call ptr @__cxa_begin_catch(ptr %0) #1
  call void @_ZSt9terminatev() #5
  unreachable
}

declare dso_local ptr @__cxa_begin_catch(ptr)

declare dso_local void @_ZSt9terminatev()

attributes #0 = { mustprogress noinline nounwind optnone uwtable "frame-pointer"="all" "min-legal-vector-width"="0" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "tune-cpu"="generic" }
attributes #1 = { nounwind }
attributes #2 = { noreturn "frame-pointer"="all" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "tune-cpu"="generic" }
attributes #3 = { noinline noreturn nounwind uwtable "frame-pointer"="all" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "tune-cpu"="generic" }
attributes #4 = { noreturn }
attributes #5 = { noreturn nounwind }

!llvm.dbg.cu = !{!0}
!llvm.module.flags = !{!2, !3, !4, !5}
!llvm.ident = !{!6}

!0 = distinct !DICompileUnit(language: DW_LANG_C_plus_plus_14, file: !1, producer: "", isOptimized: false, runtimeVersion: 0, emissionKind: NoDebug, splitDebugInlining: false, nameTableKind: None)
!1 = !DIFile(filename: "unreachable_patch1.ll", directory: "")
!2 = !{i32 2, !"Debug Info Version", i32 3}
!3 = !{i32 1, !"wchar_size", i32 4}
!4 = !{i32 7, !"uwtable", i32 2}
!5 = !{i32 7, !"frame-pointer", i32 2}
!6 = !{!""}
!7 = distinct !DISubprogram(name: "y", scope: !1, file: !1, line: 12, type: !8, scopeLine: 12, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !0)
!8 = !DISubroutineType(types: !9)
!9 = !{}
!10 = !DILocation(line: 13, column: 11, scope: !7)
!11 = !DILocation(line: 14, column: 3, scope: !7)
!12 = !DILocation(line: 15, column: 1, scope: !7)
; CHECK-LABEL: define dso_local void @_Z1yv
; CHECK-SAME: () #[[ATTR0:[0-9]+]] personality ptr @__gxx_personality_v0 !dbg [[DBG7:![0-9]+]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OSS"([5 x i8] c"TASK\00") ], !dbg [[DBG10:![0-9]+]]
; CHECK-NEXT:    invoke void @_Z3barv() #[[ATTR4:[0-9]+]]
; CHECK-NEXT:            to label [[INVOKE_CONT:%.*]] unwind label [[TERMINATE_LPAD:%.*]], !dbg [[DBG11:![0-9]+]]
; CHECK:       invoke.cont:
; CHECK-NEXT:    call void @llvm.directive.region.exit(token [[TMP0]]), !dbg [[DBG11]]
; CHECK-NEXT:    ret void, !dbg [[DBG12:![0-9]+]]
; CHECK:       terminate.lpad:
; CHECK-NEXT:    [[TMP1:%.*]] = landingpad { ptr, i32 }
; CHECK-NEXT:            catch ptr null, !dbg [[DBG11]]
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { ptr, i32 } [[TMP1]], 0, !dbg [[DBG11]]
; CHECK-NEXT:    call void @__clang_call_terminate(ptr [[TMP2]]) #[[ATTR5:[0-9]+]], !dbg [[DBG11]]
; CHECK-NEXT:    unreachable, !dbg [[DBG11]]
;
;
; CHECK-LABEL: define linkonce_odr hidden void @__clang_call_terminate
; CHECK-SAME: (ptr noundef [[TMP0:%.*]]) #[[ATTR3:[0-9]+]] comdat {
; CHECK-NEXT:    [[TMP2:%.*]] = call ptr @__cxa_begin_catch(ptr [[TMP0]]) #[[ATTR1:[0-9]+]]
; CHECK-NEXT:    call void @_ZSt9terminatev() #[[ATTR5]]
; CHECK-NEXT:    unreachable
;
