find_package(PkgConfig REQUIRED)
pkg_check_modules(NOSV_PKG REQUIRED IMPORTED_TARGET nos-v)
pkg_check_modules(OVNI_PKG IMPORTED_TARGET ovni)
if (NOT OVNI_PKG_FOUND)
  message(WARNING "OpenMP instrumentation is disabled")
  set(LIBOMP_ENABLE_INSTRUMENTATION FALSE)
else()
  set(LIBOMP_ENABLE_INSTRUMENTATION TRUE)
endif()
