! NOTE: Assertions have been autogenerated by /home/rpenacob/llvm-mono/mlir/utils/generate-test-checks.py
! This test checks lowering of OmpSs-2 DepOp.

! Test for program

! RUN: flang-new -fc1 -fompss-2 -emit-llvm -flang-deprecated-no-hlfir -fdisable-ompss-2-pass -mmlir --mlir-print-ir-after-all %s -o /dev/null |& tail -n +$(flang-new -fc1 -fompss-2 -emit-llvm -flang-deprecated-no-hlfir -fdisable-ompss-2-pass -mmlir --mlir-print-ir-after-all %s -o /dev/null |& grep -n FIRToLLVMLowering | cut -f1 -d:) | FileCheck %s --check-prefix=LLVMIRDialect

! Support list
! - [x] scalar
! - [x] explicit-shape array (no region)
! - [x] explicit-shape array (region)
! - [ ] assumed-size array
! - [ ] assumed-shape array
! - [ ] deferred-shape array

program task
    INTEGER :: J

    INTEGER :: I
    INTEGER :: ARRAY(10)
    INTEGER :: ARRAY1(5:10)
    TYPE TY
       INTEGER :: X
       INTEGER :: ARRAY(10)
    END TYPE
    TYPE(TY) T

    !$OSS TASK DO DEPEND(OUT: I)
    DO J=1,10
    END DO
    !$OSS END TASK DO

    !$OSS TASK DO DEPEND(OUT: ARRAY)
    DO J=1,10
    END DO
    !$OSS END TASK DO

    !$OSS TASK DO DEPEND(OUT: ARRAY(I))
    DO J=1,10
    END DO
    !$OSS END TASK DO

    !$OSS TASK DO DEPEND(OUT: T%X)
    DO J=1,10
    END DO
    !$OSS END TASK DO

    ! TODO
    !$OSS TASK DO DEPEND(OUT: T%ARRAY)
    DO J=1,10
    END DO
    !$OSS END TASK DO

    ! TODO
    ! !$OSS TASK DO DEPEND(OUT: T%ARRAY(2))
    ! DO J=1,10
    ! END DO
    ! !$OSS END TASK DO

    !$OSS TASK DO DEPEND(OUT: ARRAY1)
    DO J=1,10
    END DO
    !$OSS END TASK DO

    !$OSS TASK DO DEPEND(OUT: ARRAY(I : I + 10))
    DO J=1,10
    END DO
    !$OSS END TASK DO

    !$OSS TASK DO DEPEND(OUT: ARRAY(:))
    DO J=1,10
    END DO
    !$OSS END TASK DO

end program


! LLVMIRDialect-LABEL:   llvm.func @_QQmain() attributes {fir.bindc_name = "TASK"} {
! LLVMIRDialect:           %[[VAL_0:[-0-9A-Za-z._]+]] = llvm.mlir.constant(1 : i64) : i64
! LLVMIRDialect:           %[[VAL_1:[-0-9A-Za-z._]+]] = llvm.alloca %[[VAL_0]] x i32 {bindc_name = "j"} : (i64) -> !llvm.ptr
! LLVMIRDialect:           %[[VAL_2:[-0-9A-Za-z._]+]] = llvm.mlir.constant(1 : i64) : i64
! LLVMIRDialect:           %[[VAL_3:[-0-9A-Za-z._]+]] = llvm.alloca %[[VAL_2]] x i32 {bindc_name = "i"} : (i64) -> !llvm.ptr
! LLVMIRDialect:           %[[VAL_4:[-0-9A-Za-z._]+]] = llvm.mlir.constant(1 : i64) : i64
! LLVMIRDialect:           %[[VAL_5:[-0-9A-Za-z._]+]] = llvm.alloca %[[VAL_4]] x !llvm.array<6 x i32> {bindc_name = "array1"} : (i64) -> !llvm.ptr
! LLVMIRDialect:           %[[VAL_6:[-0-9A-Za-z._]+]] = llvm.mlir.constant(1 : i64) : i64
! LLVMIRDialect:           %[[VAL_7:[-0-9A-Za-z._]+]] = llvm.mlir.constant(10 : i32) : i32
! LLVMIRDialect:           %[[VAL_8:[-0-9A-Za-z._]+]] = llvm.mlir.constant(1 : i32) : i32
! LLVMIRDialect:           %[[VAL_9:[-0-9A-Za-z._]+]] = llvm.mlir.constant(6 : index) : i64
! LLVMIRDialect:           %[[VAL_10:[-0-9A-Za-z._]+]] = llvm.mlir.constant(5 : index) : i64
! LLVMIRDialect:           %[[VAL_11:[-0-9A-Za-z._]+]] = llvm.mlir.constant(10 : index) : i64
! LLVMIRDialect:           %[[VAL_12:[-0-9A-Za-z._]+]] = llvm.mlir.addressof @_QFEarray : !llvm.ptr
! LLVMIRDialect:           %[[VAL_13:[-0-9A-Za-z._]+]] = llvm.mlir.constant(1 : i64) : i64
! LLVMIRDialect:           %[[VAL_14:[-0-9A-Za-z._]+]] = llvm.mlir.constant(1 : i64) : i64
! LLVMIRDialect:           %[[VAL_15:[-0-9A-Za-z._]+]] = llvm.mlir.constant(1 : i64) : i64
! LLVMIRDialect:           %[[VAL_16:[-0-9A-Za-z._]+]] = llvm.mlir.addressof @_QFEt : !llvm.ptr
! LLVMIRDialect:           %[[VAL_17:[-0-9A-Za-z._]+]] = llvm.mlir.undef : i32
! LLVMIRDialect:           %[[VAL_18:[-0-9A-Za-z._]+]] = oss.dependency base(%[[VAL_3]] : !llvm.ptr) function(@compute.dep0) arguments(%[[VAL_3]] : !llvm.ptr) -> i32
! LLVMIRDialect:           oss.task_for lower_bound(%[[VAL_8]] : i32) upper_bound(%[[VAL_7]] : i32) step(%[[VAL_8]] : i32) loop_type(%[[VAL_6]] : i64) ind_var(%[[VAL_1]] : !llvm.ptr) private(%[[VAL_1]] : !llvm.ptr) private_type(%[[VAL_17]] : i32) shared(%[[VAL_3]] : !llvm.ptr) shared_type(%[[VAL_17]] : i32) out(%[[VAL_18]] : i32) {
! LLVMIRDialect:             oss.terminator
! LLVMIRDialect:           }
! LLVMIRDialect:           %[[VAL_19:[-0-9A-Za-z._]+]] = llvm.mlir.undef : !llvm.array<10 x i32>
! LLVMIRDialect:           %[[VAL_20:[-0-9A-Za-z._]+]] = oss.dependency base(%[[VAL_12]] : !llvm.ptr) function(@compute.dep1) arguments(%[[VAL_12]] : !llvm.ptr) -> i32
! LLVMIRDialect:           oss.task_for lower_bound(%[[VAL_8]] : i32) upper_bound(%[[VAL_7]] : i32) step(%[[VAL_8]] : i32) loop_type(%[[VAL_6]] : i64) ind_var(%[[VAL_1]] : !llvm.ptr) private(%[[VAL_1]] : !llvm.ptr) private_type(%[[VAL_17]] : i32) shared(%[[VAL_12]] : !llvm.ptr) shared_type(%[[VAL_19]] : !llvm.array<10 x i32>) captures(%[[VAL_11]] : i64) out(%[[VAL_20]] : i32) {
! LLVMIRDialect:             oss.terminator
! LLVMIRDialect:           }
! LLVMIRDialect:           %[[VAL_21:[-0-9A-Za-z._]+]] = oss.dependency base(%[[VAL_12]] : !llvm.ptr) function(@compute.dep2) arguments(%[[VAL_12]], %[[VAL_3]] : !llvm.ptr, !llvm.ptr) -> i32
! LLVMIRDialect:           oss.task_for lower_bound(%[[VAL_8]] : i32) upper_bound(%[[VAL_7]] : i32) step(%[[VAL_8]] : i32) loop_type(%[[VAL_6]] : i64) ind_var(%[[VAL_1]] : !llvm.ptr) private(%[[VAL_1]] : !llvm.ptr) private_type(%[[VAL_17]] : i32) firstprivate(%[[VAL_3]] : !llvm.ptr) firstprivate_type(%[[VAL_17]] : i32) shared(%[[VAL_12]] : !llvm.ptr) shared_type(%[[VAL_19]] : !llvm.array<10 x i32>) captures(%[[VAL_11]] : i64) out(%[[VAL_21]] : i32) {
! LLVMIRDialect:             oss.terminator
! LLVMIRDialect:           }
! LLVMIRDialect:           %[[VAL_22:[-0-9A-Za-z._]+]] = llvm.mlir.undef : !llvm.struct<"_QFTty", (i32, array<10 x i32>)>
! LLVMIRDialect:           %[[VAL_23:[-0-9A-Za-z._]+]] = oss.dependency base(%[[VAL_16]] : !llvm.ptr) function(@compute.dep3) arguments(%[[VAL_16]] : !llvm.ptr) -> i32
! LLVMIRDialect:           oss.task_for lower_bound(%[[VAL_8]] : i32) upper_bound(%[[VAL_7]] : i32) step(%[[VAL_8]] : i32) loop_type(%[[VAL_6]] : i64) ind_var(%[[VAL_1]] : !llvm.ptr) private(%[[VAL_1]] : !llvm.ptr) private_type(%[[VAL_17]] : i32) shared(%[[VAL_16]] : !llvm.ptr) shared_type(%[[VAL_22]] : !llvm.struct<"_QFTty", (i32, array<10 x i32>)>) out(%[[VAL_23]] : i32) {
! LLVMIRDialect:             oss.terminator
! LLVMIRDialect:           }
! LLVMIRDialect:           %[[VAL_24:[-0-9A-Za-z._]+]] = oss.dependency base(%[[VAL_16]] : !llvm.ptr) function(@compute.dep4) arguments(%[[VAL_16]] : !llvm.ptr) -> i32
! LLVMIRDialect:           oss.task_for lower_bound(%[[VAL_8]] : i32) upper_bound(%[[VAL_7]] : i32) step(%[[VAL_8]] : i32) loop_type(%[[VAL_6]] : i64) ind_var(%[[VAL_1]] : !llvm.ptr) private(%[[VAL_1]] : !llvm.ptr) private_type(%[[VAL_17]] : i32) shared(%[[VAL_16]] : !llvm.ptr) shared_type(%[[VAL_22]] : !llvm.struct<"_QFTty", (i32, array<10 x i32>)>) out(%[[VAL_24]] : i32) {
! LLVMIRDialect:             oss.terminator
! LLVMIRDialect:           }
! LLVMIRDialect:           %[[VAL_25:[-0-9A-Za-z._]+]] = llvm.mlir.undef : !llvm.array<6 x i32>
! LLVMIRDialect:           %[[VAL_26:[-0-9A-Za-z._]+]] = oss.dependency base(%[[VAL_5]] : !llvm.ptr) function(@compute.dep5) arguments(%[[VAL_5]] : !llvm.ptr) -> i32
! LLVMIRDialect:           oss.task_for lower_bound(%[[VAL_8]] : i32) upper_bound(%[[VAL_7]] : i32) step(%[[VAL_8]] : i32) loop_type(%[[VAL_6]] : i64) ind_var(%[[VAL_1]] : !llvm.ptr) private(%[[VAL_1]] : !llvm.ptr) private_type(%[[VAL_17]] : i32) shared(%[[VAL_5]] : !llvm.ptr) shared_type(%[[VAL_25]] : !llvm.array<6 x i32>) captures(%[[VAL_9]], %[[VAL_10]] : i64, i64) out(%[[VAL_26]] : i32) {
! LLVMIRDialect:             oss.terminator
! LLVMIRDialect:           }
! LLVMIRDialect:           %[[VAL_27:[-0-9A-Za-z._]+]] = oss.dependency base(%[[VAL_12]] : !llvm.ptr) function(@compute.dep6) arguments(%[[VAL_12]], %[[VAL_3]] : !llvm.ptr, !llvm.ptr) -> i32
! LLVMIRDialect:           oss.task_for lower_bound(%[[VAL_8]] : i32) upper_bound(%[[VAL_7]] : i32) step(%[[VAL_8]] : i32) loop_type(%[[VAL_6]] : i64) ind_var(%[[VAL_1]] : !llvm.ptr) private(%[[VAL_1]] : !llvm.ptr) private_type(%[[VAL_17]] : i32) firstprivate(%[[VAL_3]] : !llvm.ptr) firstprivate_type(%[[VAL_17]] : i32) shared(%[[VAL_12]] : !llvm.ptr) shared_type(%[[VAL_19]] : !llvm.array<10 x i32>) captures(%[[VAL_11]] : i64) out(%[[VAL_27]] : i32) {
! LLVMIRDialect:             oss.terminator
! LLVMIRDialect:           }
! LLVMIRDialect:           %[[VAL_28:[-0-9A-Za-z._]+]] = oss.dependency base(%[[VAL_12]] : !llvm.ptr) function(@compute.dep7) arguments(%[[VAL_12]] : !llvm.ptr) -> i32
! LLVMIRDialect:           oss.task_for lower_bound(%[[VAL_8]] : i32) upper_bound(%[[VAL_7]] : i32) step(%[[VAL_8]] : i32) loop_type(%[[VAL_6]] : i64) ind_var(%[[VAL_1]] : !llvm.ptr) private(%[[VAL_1]] : !llvm.ptr) private_type(%[[VAL_17]] : i32) shared(%[[VAL_12]] : !llvm.ptr) shared_type(%[[VAL_19]] : !llvm.array<10 x i32>) captures(%[[VAL_11]] : i64) out(%[[VAL_28]] : i32) {
! LLVMIRDialect:             oss.terminator
! LLVMIRDialect:           }
! LLVMIRDialect:           llvm.return
! LLVMIRDialect:         }

! LLVMIRDialect-LABEL:   llvm.func @compute.dep0(
! LLVMIRDialect-SAME:      %[[ARG0:[-0-9A-Za-z._]+]]: !llvm.ptr {llvm.noalias}) -> !llvm.struct<(ptr, i64, i64, i64)> {
! LLVMIRDialect:           %[[VAL_0:[-0-9A-Za-z._]+]] = llvm.mlir.constant(4 : i64) : i64
! LLVMIRDialect:           %[[VAL_1:[-0-9A-Za-z._]+]] = llvm.mlir.constant(0 : i64) : i64
! LLVMIRDialect:           %[[VAL_2:[-0-9A-Za-z._]+]] = llvm.mlir.poison : !llvm.struct<(ptr, i64, i64, i64)>
! LLVMIRDialect:           %[[VAL_3:[-0-9A-Za-z._]+]] = llvm.insertvalue %[[ARG0]], %[[VAL_2]][0] : !llvm.struct<(ptr, i64, i64, i64)>
! LLVMIRDialect:           %[[VAL_4:[-0-9A-Za-z._]+]] = llvm.insertvalue %[[VAL_0]], %[[VAL_3]][1] : !llvm.struct<(ptr, i64, i64, i64)>
! LLVMIRDialect:           %[[VAL_5:[-0-9A-Za-z._]+]] = llvm.insertvalue %[[VAL_1]], %[[VAL_4]][2] : !llvm.struct<(ptr, i64, i64, i64)>
! LLVMIRDialect:           %[[VAL_6:[-0-9A-Za-z._]+]] = llvm.insertvalue %[[VAL_0]], %[[VAL_5]][3] : !llvm.struct<(ptr, i64, i64, i64)>
! LLVMIRDialect:           llvm.return %[[VAL_6]] : !llvm.struct<(ptr, i64, i64, i64)>
! LLVMIRDialect:         }

! LLVMIRDialect-LABEL:   llvm.func @compute.dep1(
! LLVMIRDialect-SAME:      %[[ARG0:[-0-9A-Za-z._]+]]: !llvm.ptr {llvm.noalias}) -> !llvm.struct<(ptr, i64, i64, i64)> {
! LLVMIRDialect:           %[[VAL_0:[-0-9A-Za-z._]+]] = llvm.mlir.constant(40 : i64) : i64
! LLVMIRDialect:           %[[VAL_1:[-0-9A-Za-z._]+]] = llvm.mlir.constant(0 : i64) : i64
! LLVMIRDialect:           %[[VAL_2:[-0-9A-Za-z._]+]] = llvm.mlir.poison : !llvm.struct<(ptr, i64, i64, i64)>
! LLVMIRDialect:           %[[VAL_3:[-0-9A-Za-z._]+]] = llvm.insertvalue %[[ARG0]], %[[VAL_2]][0] : !llvm.struct<(ptr, i64, i64, i64)>
! LLVMIRDialect:           %[[VAL_4:[-0-9A-Za-z._]+]] = llvm.insertvalue %[[VAL_0]], %[[VAL_3]][1] : !llvm.struct<(ptr, i64, i64, i64)>
! LLVMIRDialect:           %[[VAL_5:[-0-9A-Za-z._]+]] = llvm.insertvalue %[[VAL_1]], %[[VAL_4]][2] : !llvm.struct<(ptr, i64, i64, i64)>
! LLVMIRDialect:           %[[VAL_6:[-0-9A-Za-z._]+]] = llvm.insertvalue %[[VAL_0]], %[[VAL_5]][3] : !llvm.struct<(ptr, i64, i64, i64)>
! LLVMIRDialect:           llvm.return %[[VAL_6]] : !llvm.struct<(ptr, i64, i64, i64)>
! LLVMIRDialect:         }

! LLVMIRDialect-LABEL:   llvm.func @compute.dep2(
! LLVMIRDialect-SAME:      %[[ARG0:[-0-9A-Za-z._]+]]: !llvm.ptr {llvm.noalias},
! LLVMIRDialect-SAME:      %[[ARG1:[-0-9A-Za-z._]+]]: !llvm.ptr {llvm.noalias}) -> !llvm.struct<(ptr, i64, i64, i64)> {
! LLVMIRDialect:           %[[VAL_0:[-0-9A-Za-z._]+]] = llvm.mlir.constant(40 : i64) : i64
! LLVMIRDialect:           %[[VAL_1:[-0-9A-Za-z._]+]] = llvm.mlir.constant(4 : i64) : i64
! LLVMIRDialect:           %[[VAL_2:[-0-9A-Za-z._]+]] = llvm.mlir.constant(1 : i64) : i64
! LLVMIRDialect:           %[[VAL_3:[-0-9A-Za-z._]+]] = llvm.load %[[ARG1]] : !llvm.ptr -> i32
! LLVMIRDialect:           %[[VAL_4:[-0-9A-Za-z._]+]] = llvm.sext %[[VAL_3]] : i32 to i64
! LLVMIRDialect:           %[[VAL_5:[-0-9A-Za-z._]+]] = llvm.sub %[[VAL_4]], %[[VAL_2]] : i64
! LLVMIRDialect:           %[[VAL_6:[-0-9A-Za-z._]+]] = llvm.mul %[[VAL_5]], %[[VAL_1]] : i64
! LLVMIRDialect:           %[[VAL_7:[-0-9A-Za-z._]+]] = llvm.mul %[[VAL_4]], %[[VAL_1]] : i64
! LLVMIRDialect:           %[[VAL_8:[-0-9A-Za-z._]+]] = llvm.mlir.poison : !llvm.struct<(ptr, i64, i64, i64)>
! LLVMIRDialect:           %[[VAL_9:[-0-9A-Za-z._]+]] = llvm.insertvalue %[[ARG0]], %[[VAL_8]][0] : !llvm.struct<(ptr, i64, i64, i64)>
! LLVMIRDialect:           %[[VAL_10:[-0-9A-Za-z._]+]] = llvm.insertvalue %[[VAL_0]], %[[VAL_9]][1] : !llvm.struct<(ptr, i64, i64, i64)>
! LLVMIRDialect:           %[[VAL_11:[-0-9A-Za-z._]+]] = llvm.insertvalue %[[VAL_6]], %[[VAL_10]][2] : !llvm.struct<(ptr, i64, i64, i64)>
! LLVMIRDialect:           %[[VAL_12:[-0-9A-Za-z._]+]] = llvm.insertvalue %[[VAL_7]], %[[VAL_11]][3] : !llvm.struct<(ptr, i64, i64, i64)>
! LLVMIRDialect:           llvm.return %[[VAL_12]] : !llvm.struct<(ptr, i64, i64, i64)>
! LLVMIRDialect:         }

! LLVMIRDialect-LABEL:   llvm.func @compute.dep3(
! LLVMIRDialect-SAME:      %[[ARG0:[-0-9A-Za-z._]+]]: !llvm.ptr {llvm.noalias}) -> !llvm.struct<(ptr, i64, i64, i64)> {
! LLVMIRDialect:           %[[VAL_0:[-0-9A-Za-z._]+]] = llvm.mlir.constant(0 : i64) : i64
! LLVMIRDialect:           %[[VAL_1:[-0-9A-Za-z._]+]] = llvm.mlir.constant(4 : i64) : i64
! LLVMIRDialect:           %[[VAL_2:[-0-9A-Za-z._]+]] = llvm.getelementptr %[[ARG0]][0, 0] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<"_QFTty", (i32, array<10 x i32>)>
! LLVMIRDialect:           %[[VAL_3:[-0-9A-Za-z._]+]] = llvm.mlir.poison : !llvm.struct<(ptr, i64, i64, i64)>
! LLVMIRDialect:           %[[VAL_4:[-0-9A-Za-z._]+]] = llvm.insertvalue %[[VAL_2]], %[[VAL_3]][0] : !llvm.struct<(ptr, i64, i64, i64)>
! LLVMIRDialect:           %[[VAL_5:[-0-9A-Za-z._]+]] = llvm.insertvalue %[[VAL_1]], %[[VAL_4]][1] : !llvm.struct<(ptr, i64, i64, i64)>
! LLVMIRDialect:           %[[VAL_6:[-0-9A-Za-z._]+]] = llvm.insertvalue %[[VAL_0]], %[[VAL_5]][2] : !llvm.struct<(ptr, i64, i64, i64)>
! LLVMIRDialect:           %[[VAL_7:[-0-9A-Za-z._]+]] = llvm.insertvalue %[[VAL_1]], %[[VAL_6]][3] : !llvm.struct<(ptr, i64, i64, i64)>
! LLVMIRDialect:           llvm.return %[[VAL_7]] : !llvm.struct<(ptr, i64, i64, i64)>
! LLVMIRDialect:         }

! LLVMIRDialect-LABEL:   llvm.func @compute.dep4(
! LLVMIRDialect-SAME:      %[[ARG0:[-0-9A-Za-z._]+]]: !llvm.ptr {llvm.noalias}) -> !llvm.struct<(ptr, i64, i64, i64)> {
! LLVMIRDialect:           %[[VAL_0:[-0-9A-Za-z._]+]] = llvm.mlir.constant(0 : i64) : i64
! LLVMIRDialect:           %[[VAL_1:[-0-9A-Za-z._]+]] = llvm.mlir.constant(40 : i64) : i64
! LLVMIRDialect:           %[[VAL_2:[-0-9A-Za-z._]+]] = llvm.getelementptr %[[ARG0]][0, 1] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<"_QFTty", (i32, array<10 x i32>)>
! LLVMIRDialect:           %[[VAL_3:[-0-9A-Za-z._]+]] = llvm.mlir.poison : !llvm.struct<(ptr, i64, i64, i64)>
! LLVMIRDialect:           %[[VAL_4:[-0-9A-Za-z._]+]] = llvm.insertvalue %[[VAL_2]], %[[VAL_3]][0] : !llvm.struct<(ptr, i64, i64, i64)>
! LLVMIRDialect:           %[[VAL_5:[-0-9A-Za-z._]+]] = llvm.insertvalue %[[VAL_1]], %[[VAL_4]][1] : !llvm.struct<(ptr, i64, i64, i64)>
! LLVMIRDialect:           %[[VAL_6:[-0-9A-Za-z._]+]] = llvm.insertvalue %[[VAL_0]], %[[VAL_5]][2] : !llvm.struct<(ptr, i64, i64, i64)>
! LLVMIRDialect:           %[[VAL_7:[-0-9A-Za-z._]+]] = llvm.insertvalue %[[VAL_1]], %[[VAL_6]][3] : !llvm.struct<(ptr, i64, i64, i64)>
! LLVMIRDialect:           llvm.return %[[VAL_7]] : !llvm.struct<(ptr, i64, i64, i64)>
! LLVMIRDialect:         }

! LLVMIRDialect-LABEL:   llvm.func @compute.dep5(
! LLVMIRDialect-SAME:      %[[ARG0:[-0-9A-Za-z._]+]]: !llvm.ptr {llvm.noalias}) -> !llvm.struct<(ptr, i64, i64, i64)> {
! LLVMIRDialect:           %[[VAL_0:[-0-9A-Za-z._]+]] = llvm.mlir.constant(24 : i64) : i64
! LLVMIRDialect:           %[[VAL_1:[-0-9A-Za-z._]+]] = llvm.mlir.constant(0 : i64) : i64
! LLVMIRDialect:           %[[VAL_2:[-0-9A-Za-z._]+]] = llvm.mlir.poison : !llvm.struct<(ptr, i64, i64, i64)>
! LLVMIRDialect:           %[[VAL_3:[-0-9A-Za-z._]+]] = llvm.insertvalue %[[ARG0]], %[[VAL_2]][0] : !llvm.struct<(ptr, i64, i64, i64)>
! LLVMIRDialect:           %[[VAL_4:[-0-9A-Za-z._]+]] = llvm.insertvalue %[[VAL_0]], %[[VAL_3]][1] : !llvm.struct<(ptr, i64, i64, i64)>
! LLVMIRDialect:           %[[VAL_5:[-0-9A-Za-z._]+]] = llvm.insertvalue %[[VAL_1]], %[[VAL_4]][2] : !llvm.struct<(ptr, i64, i64, i64)>
! LLVMIRDialect:           %[[VAL_6:[-0-9A-Za-z._]+]] = llvm.insertvalue %[[VAL_0]], %[[VAL_5]][3] : !llvm.struct<(ptr, i64, i64, i64)>
! LLVMIRDialect:           llvm.return %[[VAL_6]] : !llvm.struct<(ptr, i64, i64, i64)>
! LLVMIRDialect:         }

! LLVMIRDialect-LABEL:   llvm.func @compute.dep6(
! LLVMIRDialect-SAME:      %[[ARG0:[-0-9A-Za-z._]+]]: !llvm.ptr {llvm.noalias},
! LLVMIRDialect-SAME:      %[[ARG1:[-0-9A-Za-z._]+]]: !llvm.ptr {llvm.noalias}) -> !llvm.struct<(ptr, i64, i64, i64)> {
! LLVMIRDialect:           %[[VAL_0:[-0-9A-Za-z._]+]] = llvm.mlir.constant(40 : i64) : i64
! LLVMIRDialect:           %[[VAL_1:[-0-9A-Za-z._]+]] = llvm.mlir.constant(4 : i64) : i64
! LLVMIRDialect:           %[[VAL_2:[-0-9A-Za-z._]+]] = llvm.mlir.constant(10 : i32) : i32
! LLVMIRDialect:           %[[VAL_3:[-0-9A-Za-z._]+]] = llvm.mlir.constant(1 : i64) : i64
! LLVMIRDialect:           %[[VAL_4:[-0-9A-Za-z._]+]] = llvm.load %[[ARG1]] : !llvm.ptr -> i32
! LLVMIRDialect:           %[[VAL_5:[-0-9A-Za-z._]+]] = llvm.sext %[[VAL_4]] : i32 to i64
! LLVMIRDialect:           %[[VAL_6:[-0-9A-Za-z._]+]] = llvm.add %[[VAL_4]], %[[VAL_2]] : i32
! LLVMIRDialect:           %[[VAL_7:[-0-9A-Za-z._]+]] = llvm.sext %[[VAL_6]] : i32 to i64
! LLVMIRDialect:           %[[VAL_8:[-0-9A-Za-z._]+]] = llvm.sub %[[VAL_5]], %[[VAL_3]] : i64
! LLVMIRDialect:           %[[VAL_9:[-0-9A-Za-z._]+]] = llvm.mul %[[VAL_8]], %[[VAL_1]] : i64
! LLVMIRDialect:           %[[VAL_10:[-0-9A-Za-z._]+]] = llvm.mul %[[VAL_7]], %[[VAL_1]] : i64
! LLVMIRDialect:           %[[VAL_11:[-0-9A-Za-z._]+]] = llvm.mlir.poison : !llvm.struct<(ptr, i64, i64, i64)>
! LLVMIRDialect:           %[[VAL_12:[-0-9A-Za-z._]+]] = llvm.insertvalue %[[ARG0]], %[[VAL_11]][0] : !llvm.struct<(ptr, i64, i64, i64)>
! LLVMIRDialect:           %[[VAL_13:[-0-9A-Za-z._]+]] = llvm.insertvalue %[[VAL_0]], %[[VAL_12]][1] : !llvm.struct<(ptr, i64, i64, i64)>
! LLVMIRDialect:           %[[VAL_14:[-0-9A-Za-z._]+]] = llvm.insertvalue %[[VAL_9]], %[[VAL_13]][2] : !llvm.struct<(ptr, i64, i64, i64)>
! LLVMIRDialect:           %[[VAL_15:[-0-9A-Za-z._]+]] = llvm.insertvalue %[[VAL_10]], %[[VAL_14]][3] : !llvm.struct<(ptr, i64, i64, i64)>
! LLVMIRDialect:           llvm.return %[[VAL_15]] : !llvm.struct<(ptr, i64, i64, i64)>
! LLVMIRDialect:         }

! LLVMIRDialect-LABEL:   llvm.func @compute.dep7(
! LLVMIRDialect-SAME:      %[[ARG0:[-0-9A-Za-z._]+]]: !llvm.ptr {llvm.noalias}) -> !llvm.struct<(ptr, i64, i64, i64)> {
! LLVMIRDialect:           %[[VAL_0:[-0-9A-Za-z._]+]] = llvm.mlir.constant(40 : i64) : i64
! LLVMIRDialect:           %[[VAL_1:[-0-9A-Za-z._]+]] = llvm.mlir.constant(0 : i64) : i64
! LLVMIRDialect:           %[[VAL_2:[-0-9A-Za-z._]+]] = llvm.mlir.poison : !llvm.struct<(ptr, i64, i64, i64)>
! LLVMIRDialect:           %[[VAL_3:[-0-9A-Za-z._]+]] = llvm.insertvalue %[[ARG0]], %[[VAL_2]][0] : !llvm.struct<(ptr, i64, i64, i64)>
! LLVMIRDialect:           %[[VAL_4:[-0-9A-Za-z._]+]] = llvm.insertvalue %[[VAL_0]], %[[VAL_3]][1] : !llvm.struct<(ptr, i64, i64, i64)>
! LLVMIRDialect:           %[[VAL_5:[-0-9A-Za-z._]+]] = llvm.insertvalue %[[VAL_1]], %[[VAL_4]][2] : !llvm.struct<(ptr, i64, i64, i64)>
! LLVMIRDialect:           %[[VAL_6:[-0-9A-Za-z._]+]] = llvm.insertvalue %[[VAL_0]], %[[VAL_5]][3] : !llvm.struct<(ptr, i64, i64, i64)>
! LLVMIRDialect:           llvm.return %[[VAL_6]] : !llvm.struct<(ptr, i64, i64, i64)>
! LLVMIRDialect:         }

