! NOTE: Assertions have been autogenerated by /home/rpenacob/llvm-mono/mlir/utils/generate-test-checks.py
! RUN: bbc -hlfir=false -fompss-2 -hlfir -emit-fir %s -o - | tco | FileCheck %s --check-prefix=HLFIRToLLVMIR

! Here we check we eliminate HLFIR generated duplicates

PROGRAM P
  IMPLICIT NONE
  INTEGER :: X
  !$OSS TASK
  X = 777
  !$OSS END TASK
END

! HLFIRToLLVMIR:         %[[VAL_0:[-0-9A-Za-z._]+]] = alloca i32, i64 1, align 4
! HLFIRToLLVMIR:         %[[VAL_1:[-0-9A-Za-z._]+]] = call token @llvm.directive.region.entry() [ "DIR.OSS"([5 x i8] c"TASK\00"), "QUAL.OSS.FIRSTPRIVATE"(ptr %[[VAL_0]], i32 undef) ]
! HLFIRToLLVMIR:         br label %[[VAL_2:[-0-9A-Za-z._]+]]
! HLFIRToLLVMIR:       oss.end:                                          ; preds = %[[VAL_2]]
! HLFIRToLLVMIR:         call void @llvm.directive.region.exit(token %[[VAL_1]])
! HLFIRToLLVMIR:         ret void
! HLFIRToLLVMIR:       oss.task.region:                                  ; preds = %[[VAL_3:[-0-9A-Za-z._]+]]
! HLFIRToLLVMIR:         store i32 777, ptr %[[VAL_0]], align 4, !tbaa !1
! HLFIRToLLVMIR:         br label %[[VAL_4:[-0-9A-Za-z._]+]]

