; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -S < %s | FileCheck --check-prefix=NOFOLD %s
; RUN: opt -S -epi-fold-broadcast < %s | FileCheck --check-prefix=FOLD %s

define dso_local <vscale x 1 x double> @fold_broadcast_different_gvl(<vscale x 1 x double> %v_a, double %b, i64 %gvl) nounwind {
; NOFOLD-LABEL: @fold_broadcast_different_gvl(
; NOFOLD-NEXT:  entry:
; NOFOLD-NEXT:    [[TMP0:%.*]] = tail call i64 @llvm.epi.vsetvlmax(i64 3, i64 0)
; NOFOLD-NEXT:    [[TMP1:%.*]] = tail call <vscale x 1 x double> @llvm.epi.vfmv.v.f.nxv1f64.f64(double [[B:%.*]], i64 [[TMP0]])
; NOFOLD-NEXT:    [[TMP2:%.*]] = tail call <vscale x 1 x double> @llvm.epi.vfadd.nxv1f64.nxv1f64(<vscale x 1 x double> [[V_A:%.*]], <vscale x 1 x double> [[TMP1]], i64 [[GVL:%.*]])
; NOFOLD-NEXT:    ret <vscale x 1 x double> [[TMP2]]
;
; FOLD-LABEL: @fold_broadcast_different_gvl(
; FOLD-NEXT:  entry:
; FOLD-NEXT:    [[TMP0:%.*]] = tail call i64 @llvm.epi.vsetvlmax(i64 3, i64 0)
; FOLD-NEXT:    [[TMP1:%.*]] = call <vscale x 1 x double> @llvm.epi.vfadd.nxv1f64.f64(<vscale x 1 x double> [[V_A:%.*]], double [[B:%.*]], i64 [[GVL:%.*]])
; FOLD-NEXT:    ret <vscale x 1 x double> [[TMP1]]
;
entry:
  %0 = tail call i64 @llvm.epi.vsetvlmax(i64 3, i64 0)
  %1 = tail call <vscale x 1 x double> @llvm.epi.vfmv.v.f.nxv1f64.f64(double %b, i64 %0)
  %2 = tail call <vscale x 1 x double> @llvm.epi.vfadd.nxv1f64.nxv1f64(<vscale x 1 x double> %v_a, <vscale x 1 x double> %1, i64 %gvl)
  ret <vscale x 1 x double> %2
}

; Function Attrs: nounwind readnone
declare i64 @llvm.epi.vsetvlmax(i64, i64) #1

; Function Attrs: nounwind readnone
declare <vscale x 1 x double> @llvm.epi.vfmv.v.f.nxv1f64.f64(double, i64) #1

; Function Attrs: nounwind readnone
declare <vscale x 1 x double> @llvm.epi.vfadd.nxv1f64.nxv1f64(<vscale x 1 x double>, <vscale x 1 x double>, i64) #1


