; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -relocation-model=pic < %s \
; RUN:    | FileCheck %s
; RUN: llc -mtriple=riscv64 -relocation-model=pic < %s \
; RUN:    | FileCheck %s

@y = thread_local(initialexec) local_unnamed_addr global i32 42, align 4

define void @foo() nounwind {
; CHECK-LABEL: foo:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    la.tls.ie a0, y
; CHECK-NEXT:    add a0, a0, tp
; CHECK-NEXT:    lw a1, 0(a0)
; CHECK-NEXT:    addi a1, a1, 1
; CHECK-NEXT:    sw a1, 0(a0)
; CHECK-NEXT:    ret
entry:
  %0 = load i32, i32* @y, align 4
  %inc = add nsw i32 %0, 1
  store i32 %inc, i32* @y, align 4
  ret void
}
