// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -verify -fompss-2 -disable-llvm-passes -ferror-limit 100 %s -emit-llvm -o - | FileCheck %s
// expected-no-diagnostics
// CHECK-LABEL: @main(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[I:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[J:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[I1:%.*]] = alloca i32, align 4
// CHECK-NEXT:    store i32 0, ptr [[RETVAL]], align 4
// CHECK-NEXT:    store i32 0, ptr [[I]], align 4, !dbg [[DBG9:![0-9]+]]
// CHECK-NEXT:    store i32 0, ptr [[J]], align 4, !dbg [[DBG10:![0-9]+]]
// CHECK-NEXT:    [[TMP0:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OSS"([9 x i8] c"TASKLOOP\00"), "QUAL.OSS.PRIVATE"(ptr [[I]], i32 undef), "QUAL.OSS.PRIVATE"(ptr [[J]], i32 undef), "QUAL.OSS.LOOP.IND.VAR"(ptr [[I]], ptr [[J]]), "QUAL.OSS.LOOP.LOWER.BOUND"(ptr @compute_lb, ptr @compute_lb.1), "QUAL.OSS.LOOP.UPPER.BOUND"(ptr @compute_ub, ptr @compute_ub.2), "QUAL.OSS.LOOP.STEP"(ptr @compute_step, ptr @compute_step.3), "QUAL.OSS.LOOP.TYPE"(i64 0, i64 1, i64 1, i64 1, i64 1, i64 0, i64 1, i64 1, i64 1, i64 1) ], !dbg [[DBG11:![0-9]+]]
// CHECK-NEXT:    call void @llvm.directive.region.exit(token [[TMP0]]), !dbg [[DBG12:![0-9]+]]
// CHECK-NEXT:    store i32 0, ptr [[I1]], align 4, !dbg [[DBG13:![0-9]+]]
// CHECK-NEXT:    [[TMP1:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OSS"([9 x i8] c"TASKLOOP\00"), "QUAL.OSS.PRIVATE"(ptr [[I1]], i32 undef), "QUAL.OSS.LOOP.IND.VAR"(ptr [[I1]]), "QUAL.OSS.LOOP.LOWER.BOUND"(ptr @compute_lb.4), "QUAL.OSS.LOOP.UPPER.BOUND"(ptr @compute_ub.5), "QUAL.OSS.LOOP.STEP"(ptr @compute_step.6), "QUAL.OSS.LOOP.TYPE"(i64 0, i64 1, i64 1, i64 1, i64 1) ], !dbg [[DBG14:![0-9]+]]
// CHECK-NEXT:    [[J2:%.*]] = alloca i32, align 4
// CHECK-NEXT:    store i32 0, ptr [[J2]], align 4, !dbg [[DBG15:![0-9]+]]
// CHECK-NEXT:    br label [[FOR_COND:%.*]], !dbg [[DBG16:![0-9]+]]
// CHECK:       for.cond:
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[J2]], align 4, !dbg [[DBG17:![0-9]+]]
// CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[TMP2]], 10, !dbg [[DBG18:![0-9]+]]
// CHECK-NEXT:    br i1 [[CMP]], label [[FOR_BODY:%.*]], label [[FOR_END:%.*]], !dbg [[DBG19:![0-9]+]]
// CHECK:       for.body:
// CHECK-NEXT:    br label [[FOR_INC:%.*]], !dbg [[DBG20:![0-9]+]]
// CHECK:       for.inc:
// CHECK-NEXT:    [[TMP3:%.*]] = load i32, ptr [[J2]], align 4, !dbg [[DBG21:![0-9]+]]
// CHECK-NEXT:    [[INC:%.*]] = add nsw i32 [[TMP3]], 1, !dbg [[DBG21]]
// CHECK-NEXT:    store i32 [[INC]], ptr [[J2]], align 4, !dbg [[DBG21]]
// CHECK-NEXT:    br label [[FOR_COND]], !dbg [[DBG19]], !llvm.loop [[LOOP22:![0-9]+]]
// CHECK:       for.end:
// CHECK-NEXT:    call void @llvm.directive.region.exit(token [[TMP1]]), !dbg [[DBG24:![0-9]+]]
// CHECK-NEXT:    [[TMP4:%.*]] = load i32, ptr [[RETVAL]], align 4, !dbg [[DBG25:![0-9]+]]
// CHECK-NEXT:    ret i32 [[TMP4]], !dbg [[DBG25]]
//
int main() {
  #pragma oss taskloop collapse(2)
  for (int i = 0; i < 10; ++i) {
    for (int j = 0; j < 10; ++j)
    {
    }
  }
  #pragma oss taskloop collapse(1)
  for (int i = 0; i < 10; ++i) {
    for (int j = 0; j < 10; ++j)
    {
    }
  }
}










