// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -verify -fompss-2 -disable-llvm-passes -ferror-limit 100 %s -emit-llvm -o - | FileCheck %s
// expected-no-diagnostics

int sum;
// CHECK-LABEL: @task_taskfor(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OSS"([5 x i8] c"TASK\00"), "QUAL.OSS.SHARED"(ptr @sum, i32 undef) ], !dbg [[DBG9:![0-9]+]]
// CHECK-NEXT:    [[SUM_LOCAL:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[I:%.*]] = alloca i32, align 4
// CHECK-NEXT:    store i32 0, ptr [[SUM_LOCAL]], align 4, !dbg [[DBG10:![0-9]+]]
// CHECK-NEXT:    store i32 0, ptr [[I]], align 4, !dbg [[DBG11:![0-9]+]]
// CHECK-NEXT:    [[TMP1:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OSS"([9 x i8] c"TASK.FOR\00"), "QUAL.OSS.SHARED"(ptr @sum, i32 undef), "QUAL.OSS.PRIVATE"(ptr [[I]], i32 undef), "QUAL.OSS.FIRSTPRIVATE"(ptr [[SUM_LOCAL]], i32 undef), "QUAL.OSS.LOOP.IND.VAR"(ptr [[I]]), "QUAL.OSS.LOOP.LOWER.BOUND"(ptr @compute_lb), "QUAL.OSS.LOOP.UPPER.BOUND"(ptr @compute_ub), "QUAL.OSS.LOOP.STEP"(ptr @compute_step), "QUAL.OSS.LOOP.TYPE"(i64 0, i64 1, i64 1, i64 1, i64 1) ], !dbg [[DBG12:![0-9]+]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[I]], align 4, !dbg [[DBG13:![0-9]+]]
// CHECK-NEXT:    [[TMP3:%.*]] = load i32, ptr [[SUM_LOCAL]], align 4, !dbg [[DBG14:![0-9]+]]
// CHECK-NEXT:    [[ADD:%.*]] = add nsw i32 [[TMP3]], [[TMP2]], !dbg [[DBG14]]
// CHECK-NEXT:    store i32 [[ADD]], ptr [[SUM_LOCAL]], align 4, !dbg [[DBG14]]
// CHECK-NEXT:    [[TMP4:%.*]] = load i32, ptr [[I]], align 4, !dbg [[DBG15:![0-9]+]]
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr @sum, align 4, !dbg [[DBG16:![0-9]+]]
// CHECK-NEXT:    [[ADD2:%.*]] = add nsw i32 [[TMP5]], [[TMP4]], !dbg [[DBG16]]
// CHECK-NEXT:    store i32 [[ADD2]], ptr @sum, align 4, !dbg [[DBG16]]
// CHECK-NEXT:    call void @llvm.directive.region.exit(token [[TMP1]]), !dbg [[DBG17:![0-9]+]]
// CHECK-NEXT:    call void @llvm.directive.region.exit(token [[TMP0]]), !dbg [[DBG18:![0-9]+]]
// CHECK-NEXT:    ret void, !dbg [[DBG19:![0-9]+]]
//
void task_taskfor() {
  #pragma oss task
  {
    int sum_local = 0;
    #pragma oss task for
    for (int i = 0; i < 10; ++i) {
      sum_local += i;
      sum += i;
    }
  }
}

// CHECK-LABEL: @taskfor_task(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[I:%.*]] = alloca i32, align 4
// CHECK-NEXT:    store i32 0, ptr [[I]], align 4, !dbg [[DBG30:![0-9]+]]
// CHECK-NEXT:    [[TMP0:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OSS"([9 x i8] c"TASK.FOR\00"), "QUAL.OSS.SHARED"(ptr @sum, i32 undef), "QUAL.OSS.PRIVATE"(ptr [[I]], i32 undef), "QUAL.OSS.LOOP.IND.VAR"(ptr [[I]]), "QUAL.OSS.LOOP.LOWER.BOUND"(ptr @compute_lb.1), "QUAL.OSS.LOOP.UPPER.BOUND"(ptr @compute_ub.2), "QUAL.OSS.LOOP.STEP"(ptr @compute_step.3), "QUAL.OSS.LOOP.TYPE"(i64 0, i64 1, i64 1, i64 1, i64 1) ], !dbg [[DBG31:![0-9]+]]
// CHECK-NEXT:    [[SUM_LOCAL:%.*]] = alloca i32, align 4
// CHECK-NEXT:    store i32 0, ptr [[SUM_LOCAL]], align 4, !dbg [[DBG32:![0-9]+]]
// CHECK-NEXT:    [[TMP1:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OSS"([5 x i8] c"TASK\00"), "QUAL.OSS.SHARED"(ptr @sum, i32 undef), "QUAL.OSS.FIRSTPRIVATE"(ptr [[SUM_LOCAL]], i32 undef), "QUAL.OSS.FIRSTPRIVATE"(ptr [[I]], i32 undef) ], !dbg [[DBG33:![0-9]+]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[I]], align 4, !dbg [[DBG34:![0-9]+]]
// CHECK-NEXT:    [[TMP3:%.*]] = load i32, ptr [[SUM_LOCAL]], align 4, !dbg [[DBG35:![0-9]+]]
// CHECK-NEXT:    [[ADD:%.*]] = add nsw i32 [[TMP3]], [[TMP2]], !dbg [[DBG35]]
// CHECK-NEXT:    store i32 [[ADD]], ptr [[SUM_LOCAL]], align 4, !dbg [[DBG35]]
// CHECK-NEXT:    [[TMP4:%.*]] = load i32, ptr [[I]], align 4, !dbg [[DBG36:![0-9]+]]
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr @sum, align 4, !dbg [[DBG37:![0-9]+]]
// CHECK-NEXT:    [[ADD2:%.*]] = add nsw i32 [[TMP5]], [[TMP4]], !dbg [[DBG37]]
// CHECK-NEXT:    store i32 [[ADD2]], ptr @sum, align 4, !dbg [[DBG37]]
// CHECK-NEXT:    call void @llvm.directive.region.exit(token [[TMP1]]), !dbg [[DBG38:![0-9]+]]
// CHECK-NEXT:    call void @llvm.directive.region.exit(token [[TMP0]]), !dbg [[DBG39:![0-9]+]]
// CHECK-NEXT:    ret void, !dbg [[DBG40:![0-9]+]]
//
void taskfor_task() {
  #pragma oss task for
  for (int i = 0; i < 10; ++i) {
    int sum_local = 0;
    #pragma oss task
    {
      sum_local += i;
      sum += i;
    }
  }
}



