// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -verify -fompss-2 -disable-llvm-passes -ferror-limit 100 %s -S -emit-llvm -o - | FileCheck %s
// expected-no-diagnostics

__attribute__((noreturn)) void foo(void);
// CHECK-LABEL: @main(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OSS"([5 x i8] c"TASK\00") ], !dbg [[DBG9:![0-9]+]]
// CHECK-NEXT:    call void @foo() #[[ATTR3:[0-9]+]], !dbg [[DBG10:![0-9]+]]
// CHECK-NEXT:    call void @llvm.directive.region.exit(token [[TMP0]]), !dbg [[DBG11:![0-9]+]]
// CHECK-NEXT:    ret i32 0, !dbg [[DBG12:![0-9]+]]
//
int main() {
    #pragma oss task
    {
        foo();
    }
}


