// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --include-generated-funcs
// RUN: %clang_cc1 -verify -fompss-2 -fompss-2=libnodes -disable-llvm-passes -ferror-limit 100 %s -emit-llvm -o - | FileCheck %s
// expected-no-diagnostics

void foo(int i, int *q, int *p) {
    #pragma oss taskiter
    while (i < 10) {}
    #pragma oss taskiter
    while (p < q) {}
}




// CHECK-LABEL: @foo(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[I_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[Q_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[P_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    store i32 [[I:%.*]], ptr [[I_ADDR]], align 4
// CHECK-NEXT:    store ptr [[Q:%.*]], ptr [[Q_ADDR]], align 8
// CHECK-NEXT:    store ptr [[P:%.*]], ptr [[P_ADDR]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OSS"([15 x i8] c"TASKITER.WHILE\00"), "QUAL.OSS.FIRSTPRIVATE"(ptr [[I_ADDR]], i32 undef), "QUAL.OSS.WHILE.COND"(ptr @compute_while_cond, ptr [[I_ADDR]]) ], !dbg [[DBG9:![0-9]+]]
// CHECK-NEXT:    call void @llvm.directive.region.exit(token [[TMP0]]), !dbg [[DBG10:![0-9]+]]
// CHECK-NEXT:    [[TMP1:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OSS"([15 x i8] c"TASKITER.WHILE\00"), "QUAL.OSS.FIRSTPRIVATE"(ptr [[P_ADDR]], ptr undef), "QUAL.OSS.FIRSTPRIVATE"(ptr [[Q_ADDR]], ptr undef), "QUAL.OSS.WHILE.COND"(ptr @compute_while_cond.1, ptr [[P_ADDR]], ptr [[Q_ADDR]]) ], !dbg [[DBG11:![0-9]+]]
// CHECK-NEXT:    call void @llvm.directive.region.exit(token [[TMP1]]), !dbg [[DBG12:![0-9]+]]
// CHECK-NEXT:    ret void, !dbg [[DBG13:![0-9]+]]
//
//
// CHECK-LABEL: @compute_while_cond(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[I_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    store ptr [[I:%.*]], ptr [[I_ADDR]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[I]], align 4, !dbg [[DBG15:![0-9]+]]
// CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[TMP0]], 10, !dbg [[DBG17:![0-9]+]]
// CHECK-NEXT:    ret i1 [[CMP]], !dbg [[DBG18:![0-9]+]]
//
//
// CHECK-LABEL: @compute_while_cond.1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[P_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[Q_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    store ptr [[P:%.*]], ptr [[P_ADDR]], align 8
// CHECK-NEXT:    store ptr [[Q:%.*]], ptr [[Q_ADDR]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P]], align 8, !dbg [[DBG20:![0-9]+]]
// CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[Q]], align 8, !dbg [[DBG22:![0-9]+]]
// CHECK-NEXT:    [[CMP:%.*]] = icmp ult ptr [[TMP0]], [[TMP1]], !dbg [[DBG23:![0-9]+]]
// CHECK-NEXT:    ret i1 [[CMP]], !dbg [[DBG22]]
//
