// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -verify -fompss-2 -disable-llvm-passes -ferror-limit 100 %s -emit-llvm -o - | FileCheck %s
// expected-no-diagnostics

// A task body whose control flow never reaches the end (here, an infinite
// for-loop) leaves Clang's IR builder without an insertion point after the
// associated statement. The matching llvm.directive.region.exit intrinsic
// must still be emitted into a basic block so the IR verifier and the
// downstream OmpSs analysis/transform passes can find an entry/exit pair.

// CHECK-LABEL: @main(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca i32, align 4
// CHECK-NEXT:    store i32 0, ptr [[RETVAL]], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OSS"([5 x i8] c"TASK\00") ], !dbg [[DBG9:![0-9]+]]
// CHECK-NEXT:    br label [[FOR_COND:%.*]], !dbg [[DBG10:![0-9]+]]
// CHECK:       for.cond:
// CHECK-NEXT:    br label [[FOR_COND]], !dbg [[DBG10]], !llvm.loop [[LOOP11:![0-9]+]]
// CHECK:       [[BB:.*]]:
// CHECK-NEXT:    call void @llvm.directive.region.exit(token [[TMP0]]), !dbg [[DBG13:![0-9]+]]
// CHECK-NEXT:    ret i32 0, !dbg [[DBG14:![0-9]+]]
//
int main(void) {
    #pragma oss task
    for (;;);
    return 0;
}
