// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --function-signature
// RUN: %clang_cc1 -triple x86_64-gnu-linux -verify -fompss-2 -disable-llvm-passes -ferror-limit 100 %s -emit-llvm -o - | FileCheck %s --check-prefixes=LIN64
// RUN: %clang_cc1 -triple ppc64 -verify -fompss-2 -disable-llvm-passes -ferror-limit 100 %s -emit-llvm -o - | FileCheck %s --check-prefixes=PPC64
// RUN: %clang_cc1 -triple aarch64 -verify -fompss-2 -disable-llvm-passes -ferror-limit 100 %s -emit-llvm -o - | FileCheck %s --check-prefixes=AARCH64
// expected-no-diagnostics

#pragma oss task wait
void outline();

// LIN64-LABEL: define {{[^@]+}}@foo
// LIN64-SAME: () #[[ATTR0:[0-9]+]] !dbg [[DBG5:![0-9]+]] {
// LIN64-NEXT:  entry:
// LIN64-NEXT:    [[TMP0:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OSS"([5 x i8] c"TASK\00"), "QUAL.OSS.WAIT"(i1 true) ], !dbg [[DBG9:![0-9]+]]
// LIN64-NEXT:    call void @llvm.directive.region.exit(token [[TMP0]]), !dbg [[DBG10:![0-9]+]]
// LIN64-NEXT:    [[TMP1:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OSS"([5 x i8] c"TASK\00"), "QUAL.OSS.WAIT"(i1 true), "QUAL.OSS.DEVICE.DEVFUNC"([8 x i8] c"outline\00"), "QUAL.OSS.DECL.SOURCE"([16 x i8] c"task_wait.c:7:1\00") ], !dbg [[DBG11:![0-9]+]]
// LIN64-NEXT:    call void (...) @outline(), !dbg [[DBG11]]
// LIN64-NEXT:    call void @llvm.directive.region.exit(token [[TMP1]]), !dbg [[DBG11]]
// LIN64-NEXT:    ret void, !dbg [[DBG12:![0-9]+]]
//
// PPC64-LABEL: define {{[^@]+}}@foo
// PPC64-SAME: () #[[ATTR0:[0-9]+]] !dbg [[DBG5:![0-9]+]] {
// PPC64-NEXT:  entry:
// PPC64-NEXT:    [[TMP0:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OSS"([5 x i8] c"TASK\00"), "QUAL.OSS.WAIT"(i1 true) ], !dbg [[DBG9:![0-9]+]]
// PPC64-NEXT:    call void @llvm.directive.region.exit(token [[TMP0]]), !dbg [[DBG10:![0-9]+]]
// PPC64-NEXT:    [[TMP1:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OSS"([5 x i8] c"TASK\00"), "QUAL.OSS.WAIT"(i1 true), "QUAL.OSS.DEVICE.DEVFUNC"([8 x i8] c"outline\00"), "QUAL.OSS.DECL.SOURCE"([16 x i8] c"task_wait.c:7:1\00") ], !dbg [[DBG11:![0-9]+]]
// PPC64-NEXT:    call void @outline(), !dbg [[DBG11]]
// PPC64-NEXT:    call void @llvm.directive.region.exit(token [[TMP1]]), !dbg [[DBG11]]
// PPC64-NEXT:    ret void, !dbg [[DBG12:![0-9]+]]
//
// AARCH64-LABEL: define {{[^@]+}}@foo
// AARCH64-SAME: () #[[ATTR0:[0-9]+]] !dbg [[DBG5:![0-9]+]] {
// AARCH64-NEXT:  entry:
// AARCH64-NEXT:    [[TMP0:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OSS"([5 x i8] c"TASK\00"), "QUAL.OSS.WAIT"(i1 true) ], !dbg [[DBG9:![0-9]+]]
// AARCH64-NEXT:    call void @llvm.directive.region.exit(token [[TMP0]]), !dbg [[DBG10:![0-9]+]]
// AARCH64-NEXT:    [[TMP1:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OSS"([5 x i8] c"TASK\00"), "QUAL.OSS.WAIT"(i1 true), "QUAL.OSS.DEVICE.DEVFUNC"([8 x i8] c"outline\00"), "QUAL.OSS.DECL.SOURCE"([16 x i8] c"task_wait.c:7:1\00") ], !dbg [[DBG11:![0-9]+]]
// AARCH64-NEXT:    call void @outline(), !dbg [[DBG11]]
// AARCH64-NEXT:    call void @llvm.directive.region.exit(token [[TMP1]]), !dbg [[DBG11]]
// AARCH64-NEXT:    ret void, !dbg [[DBG12:![0-9]+]]
//
void foo() {
    #pragma oss task wait
    {}
    outline();
}


