// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --function-signature
// RUN: %clang_cc1 -triple x86_64-gnu-linux -verify -fompss-2 -disable-llvm-passes -ferror-limit 100 %s -emit-llvm -o - | FileCheck %s --check-prefixes=LIN64
// RUN: %clang_cc1 -triple ppc64 -verify -fompss-2 -disable-llvm-passes -ferror-limit 100 %s -emit-llvm -o - | FileCheck %s --check-prefixes=PPC64
// RUN: %clang_cc1 -triple aarch64 -verify -fompss-2 -disable-llvm-passes -ferror-limit 100 %s -emit-llvm -o - | FileCheck %s --check-prefixes=AARCH64
// expected-no-diagnostics

#pragma oss task device(smp)
void foo();
#pragma oss task device(cuda)
void foo1();
#pragma oss task device(opencl)
void foo2();
#pragma oss task device(fpga)
void foo3();

// LIN64-LABEL: define {{[^@]+}}@bar
// LIN64-SAME: () #[[ATTR0:[0-9]+]] !dbg [[DBG5:![0-9]+]] {
// LIN64-NEXT:  entry:
// LIN64-NEXT:    [[TMP0:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OSS"([5 x i8] c"TASK\00"), "QUAL.OSS.DEVICE"(i32 0), "QUAL.OSS.DEVICE.DEVFUNC"([4 x i8] c"foo\00"), "QUAL.OSS.DECL.SOURCE"([18 x i8] c"task_device.c:7:1\00") ], !dbg [[DBG9:![0-9]+]]
// LIN64-NEXT:    call void (...) @foo(), !dbg [[DBG9]]
// LIN64-NEXT:    call void @llvm.directive.region.exit(token [[TMP0]]), !dbg [[DBG9]]
// LIN64-NEXT:    [[TMP1:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OSS"([5 x i8] c"TASK\00"), "QUAL.OSS.DEVICE"(i32 1), "QUAL.OSS.DEVICE.DEVFUNC"([5 x i8] c"foo1\00"), "QUAL.OSS.DECL.SOURCE"([18 x i8] c"task_device.c:9:1\00") ], !dbg [[DBG10:![0-9]+]]
// LIN64-NEXT:    call void (...) @foo1(), !dbg [[DBG10]]
// LIN64-NEXT:    call void @llvm.directive.region.exit(token [[TMP1]]), !dbg [[DBG10]]
// LIN64-NEXT:    [[TMP2:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OSS"([5 x i8] c"TASK\00"), "QUAL.OSS.DEVICE"(i32 4), "QUAL.OSS.DEVICE.DEVFUNC"([5 x i8] c"foo2\00"), "QUAL.OSS.DECL.SOURCE"([19 x i8] c"task_device.c:11:1\00") ], !dbg [[DBG11:![0-9]+]]
// LIN64-NEXT:    call void (...) @foo2(), !dbg [[DBG11]]
// LIN64-NEXT:    call void @llvm.directive.region.exit(token [[TMP2]]), !dbg [[DBG11]]
// LIN64-NEXT:    [[TMP3:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OSS"([5 x i8] c"TASK\00"), "QUAL.OSS.DEVICE"(i32 5), "QUAL.OSS.DEVICE.DEVFUNC"([5 x i8] c"foo3\00"), "QUAL.OSS.DECL.SOURCE"([19 x i8] c"task_device.c:13:1\00") ], !dbg [[DBG12:![0-9]+]]
// LIN64-NEXT:    call void (...) @foo3(), !dbg [[DBG12]]
// LIN64-NEXT:    call void @llvm.directive.region.exit(token [[TMP3]]), !dbg [[DBG12]]
// LIN64-NEXT:    [[TMP4:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OSS"([5 x i8] c"TASK\00"), "QUAL.OSS.DEVICE"(i32 1) ], !dbg [[DBG13:![0-9]+]]
// LIN64-NEXT:    call void @llvm.directive.region.exit(token [[TMP4]]), !dbg [[DBG14:![0-9]+]]
// LIN64-NEXT:    [[TMP5:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OSS"([5 x i8] c"TASK\00"), "QUAL.OSS.DEVICE"(i32 4) ], !dbg [[DBG15:![0-9]+]]
// LIN64-NEXT:    call void @llvm.directive.region.exit(token [[TMP5]]), !dbg [[DBG16:![0-9]+]]
// LIN64-NEXT:    ret void, !dbg [[DBG17:![0-9]+]]
//
// PPC64-LABEL: define {{[^@]+}}@bar
// PPC64-SAME: () #[[ATTR0:[0-9]+]] !dbg [[DBG5:![0-9]+]] {
// PPC64-NEXT:  entry:
// PPC64-NEXT:    [[TMP0:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OSS"([5 x i8] c"TASK\00"), "QUAL.OSS.DEVICE"(i32 0), "QUAL.OSS.DEVICE.DEVFUNC"([4 x i8] c"foo\00"), "QUAL.OSS.DECL.SOURCE"([18 x i8] c"task_device.c:7:1\00") ], !dbg [[DBG9:![0-9]+]]
// PPC64-NEXT:    call void @foo(), !dbg [[DBG9]]
// PPC64-NEXT:    call void @llvm.directive.region.exit(token [[TMP0]]), !dbg [[DBG9]]
// PPC64-NEXT:    [[TMP1:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OSS"([5 x i8] c"TASK\00"), "QUAL.OSS.DEVICE"(i32 1), "QUAL.OSS.DEVICE.DEVFUNC"([5 x i8] c"foo1\00"), "QUAL.OSS.DECL.SOURCE"([18 x i8] c"task_device.c:9:1\00") ], !dbg [[DBG10:![0-9]+]]
// PPC64-NEXT:    call void @foo1(), !dbg [[DBG10]]
// PPC64-NEXT:    call void @llvm.directive.region.exit(token [[TMP1]]), !dbg [[DBG10]]
// PPC64-NEXT:    [[TMP2:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OSS"([5 x i8] c"TASK\00"), "QUAL.OSS.DEVICE"(i32 4), "QUAL.OSS.DEVICE.DEVFUNC"([5 x i8] c"foo2\00"), "QUAL.OSS.DECL.SOURCE"([19 x i8] c"task_device.c:11:1\00") ], !dbg [[DBG11:![0-9]+]]
// PPC64-NEXT:    call void @foo2(), !dbg [[DBG11]]
// PPC64-NEXT:    call void @llvm.directive.region.exit(token [[TMP2]]), !dbg [[DBG11]]
// PPC64-NEXT:    [[TMP3:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OSS"([5 x i8] c"TASK\00"), "QUAL.OSS.DEVICE"(i32 5), "QUAL.OSS.DEVICE.DEVFUNC"([5 x i8] c"foo3\00"), "QUAL.OSS.DECL.SOURCE"([19 x i8] c"task_device.c:13:1\00") ], !dbg [[DBG12:![0-9]+]]
// PPC64-NEXT:    call void @foo3(), !dbg [[DBG12]]
// PPC64-NEXT:    call void @llvm.directive.region.exit(token [[TMP3]]), !dbg [[DBG12]]
// PPC64-NEXT:    [[TMP4:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OSS"([5 x i8] c"TASK\00"), "QUAL.OSS.DEVICE"(i32 1) ], !dbg [[DBG13:![0-9]+]]
// PPC64-NEXT:    call void @llvm.directive.region.exit(token [[TMP4]]), !dbg [[DBG14:![0-9]+]]
// PPC64-NEXT:    [[TMP5:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OSS"([5 x i8] c"TASK\00"), "QUAL.OSS.DEVICE"(i32 4) ], !dbg [[DBG15:![0-9]+]]
// PPC64-NEXT:    call void @llvm.directive.region.exit(token [[TMP5]]), !dbg [[DBG16:![0-9]+]]
// PPC64-NEXT:    ret void, !dbg [[DBG17:![0-9]+]]
//
// AARCH64-LABEL: define {{[^@]+}}@bar
// AARCH64-SAME: () #[[ATTR0:[0-9]+]] !dbg [[DBG5:![0-9]+]] {
// AARCH64-NEXT:  entry:
// AARCH64-NEXT:    [[TMP0:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OSS"([5 x i8] c"TASK\00"), "QUAL.OSS.DEVICE"(i32 0), "QUAL.OSS.DEVICE.DEVFUNC"([4 x i8] c"foo\00"), "QUAL.OSS.DECL.SOURCE"([18 x i8] c"task_device.c:7:1\00") ], !dbg [[DBG9:![0-9]+]]
// AARCH64-NEXT:    call void @foo(), !dbg [[DBG9]]
// AARCH64-NEXT:    call void @llvm.directive.region.exit(token [[TMP0]]), !dbg [[DBG9]]
// AARCH64-NEXT:    [[TMP1:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OSS"([5 x i8] c"TASK\00"), "QUAL.OSS.DEVICE"(i32 1), "QUAL.OSS.DEVICE.DEVFUNC"([5 x i8] c"foo1\00"), "QUAL.OSS.DECL.SOURCE"([18 x i8] c"task_device.c:9:1\00") ], !dbg [[DBG10:![0-9]+]]
// AARCH64-NEXT:    call void @foo1(), !dbg [[DBG10]]
// AARCH64-NEXT:    call void @llvm.directive.region.exit(token [[TMP1]]), !dbg [[DBG10]]
// AARCH64-NEXT:    [[TMP2:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OSS"([5 x i8] c"TASK\00"), "QUAL.OSS.DEVICE"(i32 4), "QUAL.OSS.DEVICE.DEVFUNC"([5 x i8] c"foo2\00"), "QUAL.OSS.DECL.SOURCE"([19 x i8] c"task_device.c:11:1\00") ], !dbg [[DBG11:![0-9]+]]
// AARCH64-NEXT:    call void @foo2(), !dbg [[DBG11]]
// AARCH64-NEXT:    call void @llvm.directive.region.exit(token [[TMP2]]), !dbg [[DBG11]]
// AARCH64-NEXT:    [[TMP3:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OSS"([5 x i8] c"TASK\00"), "QUAL.OSS.DEVICE"(i32 5), "QUAL.OSS.DEVICE.DEVFUNC"([5 x i8] c"foo3\00"), "QUAL.OSS.DECL.SOURCE"([19 x i8] c"task_device.c:13:1\00") ], !dbg [[DBG12:![0-9]+]]
// AARCH64-NEXT:    call void @foo3(), !dbg [[DBG12]]
// AARCH64-NEXT:    call void @llvm.directive.region.exit(token [[TMP3]]), !dbg [[DBG12]]
// AARCH64-NEXT:    [[TMP4:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OSS"([5 x i8] c"TASK\00"), "QUAL.OSS.DEVICE"(i32 1) ], !dbg [[DBG13:![0-9]+]]
// AARCH64-NEXT:    call void @llvm.directive.region.exit(token [[TMP4]]), !dbg [[DBG14:![0-9]+]]
// AARCH64-NEXT:    [[TMP5:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OSS"([5 x i8] c"TASK\00"), "QUAL.OSS.DEVICE"(i32 4) ], !dbg [[DBG15:![0-9]+]]
// AARCH64-NEXT:    call void @llvm.directive.region.exit(token [[TMP5]]), !dbg [[DBG16:![0-9]+]]
// AARCH64-NEXT:    ret void, !dbg [[DBG17:![0-9]+]]
//
void bar() {
    foo();
    foo1();
    foo2();
    foo3();
    #pragma oss task device(cuda)
    {}
    #pragma oss task device(opencl)
    {}
}

