// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --include-generated-funcs
// RUN: %clang_cc1 -verify -fompss-2 -disable-llvm-passes -ferror-limit 100 %s -emit-llvm -o - | FileCheck %s
// expected-no-diagnostics

int main() {
    #pragma oss task
    {
        while (1) {
        }
    }
}
// CHECK-LABEL: @main(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca i32, align 4
// CHECK-NEXT:    store i32 0, ptr [[RETVAL]], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OSS"([5 x i8] c"TASK\00") ], !dbg [[DBG9:![0-9]+]]
// CHECK-NEXT:    [[TMP:%.*]] = alloca i1, align 1
// CHECK-NEXT:    br label [[WHILE_COND:%.*]], !dbg [[DBG10:![0-9]+]]
// CHECK:       while.cond:
// CHECK-NEXT:    store i1 true, ptr [[TMP]], align 1, !dbg [[DBG10]]
// CHECK-NEXT:    [[TMP1:%.*]] = load i1, ptr [[TMP]], align 1, !dbg [[DBG10]]
// CHECK-NEXT:    br i1 [[TMP1]], label [[WHILE_BODY:%.*]], label [[WHILE_END:%.*]], !dbg [[DBG10]]
// CHECK:       while.body:
// CHECK-NEXT:    br label [[WHILE_COND]], !dbg [[DBG10]], !llvm.loop [[LOOP11:![0-9]+]]
// CHECK:       while.end:
// CHECK-NEXT:    call void @llvm.directive.region.exit(token [[TMP0]]), !dbg [[DBG13:![0-9]+]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[RETVAL]], align 4, !dbg [[DBG14:![0-9]+]]
// CHECK-NEXT:    ret i32 [[TMP2]], !dbg [[DBG14]]
//
